#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0003-0010 0013-0014 0016-0037 0102-0104 0107-0110 0112 0115-0116 0120-0126 0130-0133 0135-0136 0172 0176-0377

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

SEP="$(printf '\001')"
ESC="$(printf '\002')"
# Command that handles readability line breaks
LB="0?"
# Phase 1 (search/mark): errors disabled by default,
# DBG1=1 enables error reporting, QF1=1 quits on failure
# OK1: with DBG1=1 also report fallback anchor successes
[ "$DBG1" = "1" ] && OK1= || OK1="0${ESC}${ESC}${ESC}?"
[ "$DBG1" = "1" ] && DBG1= || DBG1="0${ESC}?"
[ "$QF1" = "1" ] && QF1="${ESC}${SEP}vis 2${ESC}${SEP}q!1" || QF1=
# Phase 2 (edits): DBG2=1 disables errors, QF2=1 ignores them
[ "$DBG2" = "1" ] && DBG2="0${ESC}?" || DBG2=
[ "$QF2" = "1" ] && QF2= || QF2="${ESC}${SEP}vis 2${ESC}${SEP}q!1"
# Enters vi at failing code line in this script
# Designed for state inspection mid execution
[ "$INTR" = "1" ] && INTR="${ESC}${SEP}|sc|${ESC}${SEP}vis 2:0reg:e $0:83reg %@47:%f> %@p:&Q:b0:|sc! ${ESC}${ESC}${ESC}${SEP}|:vis 3${ESC}${SEP}q1" || INTR=

# Patch: vi.c
EXINIT="|sc! ${ESC}${SEP}|:vis 3${SEP}98reg${SEP}b0${SEP}%ya 98${SEP}?%;f> 	case 'w':
	case 'W':
		var = mv == 'W';
		for \\(i = 0; i < cnt; i\\+\\+\\)${ESC}${SEP}0${ESC}?${ESC}?${ESC}${SEP}0${ESC}?${ESC}?+2m 0${ESC}${ESC}${ESC}${SEP}1q${ESC}${SEP}%;f> 	case 'w':
	case 'W':
		var = mv == 'W';${ESC}${SEP}1${ESC}?${ESC}?${ESC}${SEP}1${ESC}?${ESC}?+2m 0${ESC}${ESC}${ESC}${SEP}${OK1}p OK vi.c:604:a1${SEP}${LB}
${SEP}0;1??!${DBG1:-ya!112${ESC}${SEP}prp${ESC}${SEP}p FAIL vi.c:604${ESC}${SEP}pr${INTR}${QF1}}${SEP}${LB}
${SEP}?%;f+ 		for \\(i = 0; i < cnt; i\\+\\+\\)
			if \\(lbuf_wordbeg\\(xb, var, vi_nlmode\\+1, row, off\\)\\)
				break;
		break;
	case '\\(':${ESC}${SEP}0${ESC}?${ESC}?${ESC}${SEP}0${ESC}?${ESC}?+1m 1${ESC}${ESC}${ESC}${SEP}1q${ESC}${SEP};0${ESC}${SEP}0reg${ESC}${SEP}.,\$f+ ^		for \\(i = 0; i < cnt; i\\+\\+\\)\$${ESC}${SEP}1${ESC}?${ESC}?${ESC}${SEP}1${ESC}?${ESC}?+1m 1${ESC}${ESC}${ESC}${SEP}${OK1}p OK vi.c:606:a1${ESC}${ESC}${ESC}${SEP}98reg${ESC}${ESC}${ESC}${SEP}1q${ESC}${SEP}98reg${ESC}${SEP};0${ESC}${SEP}0reg${ESC}${SEP}.,\$f+ ^			if \\(lbuf_wordbeg\\(xb, var, vi_nlmode\\+1, row, off\\)\\)\$${ESC}${SEP}2${ESC}?${ESC}?${ESC}${SEP}2${ESC}?${ESC}?m 1${ESC}${ESC}${ESC}${SEP}${OK1}p OK vi.c:606:a2${ESC}${ESC}${ESC}${SEP}98reg${ESC}${SEP}98reg${SEP}${LB}
${SEP}0;1;2??!${DBG1:-ya!112${ESC}${SEP}prp${ESC}${SEP}p FAIL vi.c:606${ESC}${SEP}pr${INTR}${QF1}}${SEP}${LB}
${SEP}${LB}
${SEP}'0a 		if (cmd >= 0 && cnt == 1)
			dir = 2;
		else
			dir = vi_nlmode+1;
		if (cmd == 'c') {
			/* vim: cw/cW acts like ce/cE (no trailing whitespace) */
			int prow = *row, poff = *off;
			for (i = 0; i < cnt; i++)
				if (lbuf_wordend(xb, var, dir, row, off))
					break;
			if (prow == *row)
				return mv == 'w' ? 'e' : 'E';
			*row = prow;
			*off = poff;
		}
${SEP}??!${DBG2:-ya!112${ESC}${SEP}prp${ESC}${SEP}p FAIL vi.c:604:m0${ESC}${SEP}pr${INTR}${QF2}}${SEP}${LB}
${SEP}'1s/vi_nlmode\\+1/dir/${SEP}??!${DBG2:-ya!112${ESC}${SEP}prp${ESC}${SEP}p FAIL vi.c:606:m1${ESC}${SEP}pr${INTR}${QF2}}${SEP}vis 2${SEP}b0${SEP}w${SEP}q" $VI -e 'vi.c'

exit 0
=== PATCH2VI DELTA ===
=== PATCH2VI PATCH ===
diff --git a/vi.c b/vi.c
index e53c93b8..c9149c1a 100644
--- a/vi.c
+++ b/vi.c
@@ -602,8 +602,23 @@ static int vi_region(int cmd, int *row, int *off)
 	case 'w':
 	case 'W':
 		var = mv == 'W';
+		if (cmd >= 0 && cnt == 1)
+			dir = 2;
+		else
+			dir = vi_nlmode+1;
+		if (cmd == 'c') {
+			/* vim: cw/cW acts like ce/cE (no trailing whitespace) */
+			int prow = *row, poff = *off;
+			for (i = 0; i < cnt; i++)
+				if (lbuf_wordend(xb, var, dir, row, off))
+					break;
+			if (prow == *row)
+				return mv == 'w' ? 'e' : 'E';
+			*row = prow;
+			*off = poff;
+		}
 		for (i = 0; i < cnt; i++)
-			if (lbuf_wordbeg(xb, var, vi_nlmode+1, row, off))
+			if (lbuf_wordbeg(xb, var, dir, row, off))
 				break;
 		break;
 	case '(':
