#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0001-0010 0013-0014 0016-0037 0102-0104 0107-0110 0112-0113 0115-0126 0130-0133 0135-0136 0172 0176-0377

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

SEP="$(printf '\001')"
# Command that handles readability line breaks
LB="0?"
# Phase 1 (search/mark): errors disabled by default,
# DBG1=1 enables error reporting, QF1=1 quits on failure
[ "$DBG1" = "1" ] && DBG1= || DBG1="0\?"
[ "$QF1" = "1" ] && QF1="\\${SEP}vis 2\\${SEP}q!1" || QF1=
# Phase 2 (edits): DBG2=1 disables errors, QF2=1 ignores them
[ "$DBG2" = "1" ] && DBG2="0\?" || DBG2=
[ "$QF2" = "1" ] && QF2= || QF2="\\${SEP}vis 2\\${SEP}q!1"
# Enters vi at failing code line in this script
# Designed for state inspection mid execution
[ "$INTR" = "1" ] && INTR="\\${SEP}|sc|\\${SEP}vis 2:0reg:e $0:83reg %@/:%f> %@p:&Q:b0:|sc! \\\\\\${SEP}|:vis 3\\${SEP}q1" || INTR=

# Patch: vi.c
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}98reg${SEP}b0${SEP}%ya b${SEP}%;f> 	case 'w':
	case 'W':
		var = mv == 'W';${SEP}??!${DBG1:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:604\\${SEP}pr${INTR}${QF1}}${SEP}${LB}
${SEP}+2m 0${SEP}%;f+ 		for \\\\(i = 0; i < cnt; i\\\\+\\\\+\\\\)
			if \\\\(lbuf_wordbeg\\\\(xb, var, vi_nlmode\\\\+1, row, off\\\\)\\\\)${SEP}??!${DBG1:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:606\\${SEP}pr${INTR}${QF1}}${SEP}${LB}
${SEP}+1m 1${SEP}${LB}
${SEP}'0a 		if (cmd >= 0 && cnt == 1)
			dir = 2;
		else
			dir = vi_nlmode+1;
		if (cmd == 'c') {
			/* vim: cw/cW acts like ce/cE (no trailing whitespace) */
			int prow = *row, poff = *off;
			for (i = 0; i < cnt; i++)
				if (lbuf_wordend(xb, var, dir, row, off))
					break;
			if (prow == *row)
				return mv == 'w' ? 'e' : 'E';
			*row = prow;
			*off = poff;
		}
${SEP}??!${DBG2:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:604:m0\\${SEP}pr${INTR}${QF2}}${SEP}${LB}
${SEP}'1s/vi_nlmode\\\\+1/dir/${SEP}??!${DBG2:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:606:m1\\${SEP}pr${INTR}${QF2}}${SEP}vis 2${SEP}b0${SEP}w${SEP}q" $VI -e 'vi.c'

exit 0
=== PATCH2VI DELTA ===
=== DELTA vi.c ===
=== GROUP 2 ===
-			if (lbuf_wordbeg(xb, var, vi_nlmode+1, row, off))
+			if (lbuf_wordbeg(xb, var, dir, row, off))
=== END ===
=== LEVEL 2 ===
=== pre_ctx ===
		for (i = 0; i < cnt; i++)
=== END ===
=== post_ctx ===
				break;
		break;
	case '(':
=== END ===
=== pattern ===
		for \(i = 0; i < cnt; i\+\+\)
			if \(lbuf_wordbeg\(xb, var, vi_nlmode\+1, row, off\)\)
=== END ===
=== END ===
=== PATCH2VI PATCH ===
diff --git a/vi.c b/vi.c
index d133d031..58a5d47a 100644
--- a/vi.c
+++ b/vi.c
@@ -602,8 +602,23 @@ static int vi_region(int cmd, int *row, int *off)
 	case 'w':
 	case 'W':
 		var = mv == 'W';
+		if (cmd >= 0 && cnt == 1)
+			dir = 2;
+		else
+			dir = vi_nlmode+1;
+		if (cmd == 'c') {
+			/* vim: cw/cW acts like ce/cE (no trailing whitespace) */
+			int prow = *row, poff = *off;
+			for (i = 0; i < cnt; i++)
+				if (lbuf_wordend(xb, var, dir, row, off))
+					break;
+			if (prow == *row)
+				return mv == 'w' ? 'e' : 'E';
+			*row = prow;
+			*off = poff;
+		}
 		for (i = 0; i < cnt; i++)
-			if (lbuf_wordbeg(xb, var, vi_nlmode+1, row, off))
+			if (lbuf_wordbeg(xb, var, dir, row, off))
 				break;
 		break;
 	case '(':
