#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0001-0010 0013-0014 0016-0037 0104 0107 0112 0121 0126-0130 0136 0177-0377

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

SEP="$(printf '\001')"
# Command that handles readability line breaks
LB="0?"
# Disable errors
[ "$DBG" = "1" ] && DBG="0\?" || DBG=
# Ignore errors
[ "$QF" = "1" ] && QF= || QF="\\${SEP}vis 2\\${SEP}q!1"
# Enters vi at failing code line in this script
# Designed for state inspection mid execution
[ "$INTR" = "1" ] && INTR="\\${SEP}|sc|\\${SEP}vis 2:e $0:83reg %@/:%f> %@p:&Q:b0:|sc! \\\\\\${SEP}|:vis 3\\${SEP}q1" || INTR=

# Patch: lbuf.c ren.c vi.c vi.h
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}b0${SEP}%;f> static int lbuf_replace\\\\(struct lbuf \\\\*lb, sbuf \\\\*sb, char \\\\*s, struct lopt \\\\*lo, int n_del, int n_ins\\\\)
\\\\{
	int i, pos = lo->pos;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL lbuf.c:83\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 	syn_blockhl_invalidate();
${SEP}b1${SEP}%;f> int ftidx;
int syn_blockhl;

${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ren.c:251\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a /* block-highlight pair cache, keyed by lbuf line pointer */
struct hl_cache_entry {
	char *ln;
	int gen;
	int blockhl;
	int blockatt;
	int ftidx;
};
#define HL_CACHE_BITS	10
#define HL_CACHE_SIZE	(1 << HL_CACHE_BITS)
#define HL_CACHE_MASK	(HL_CACHE_SIZE - 1)
#define HL_CACHE_PROBE	8
static struct hl_cache_entry hl_cache[HL_CACHE_SIZE];
static int hl_cache_gen = 1;
static struct lbuf *syn_lb;
static int syn_row;

static int hl_cache_hash(char *ln)
{
	return (int)(((size_t)ln >> 4) & HL_CACHE_MASK);
}

static struct hl_cache_entry *hl_cache_find(char *ln)
{
	if (!ln)
		return NULL;
	int h = hl_cache_hash(ln);
	for (int i = 0; i < HL_CACHE_PROBE; i++) {
		struct hl_cache_entry *e = &hl_cache[(h + i) & HL_CACHE_MASK];
		if (e->ln == ln && e->gen == hl_cache_gen)
			return e;
		if (!e->ln)
			return NULL;
	}
	return NULL;
}

static void hl_cache_set(char *ln, int blockhl, int blockatt_v, int fti)
{
	if (!ln)
		return;
	int h = hl_cache_hash(ln);
	struct hl_cache_entry *slot = &hl_cache[h];
	for (int i = 0; i < HL_CACHE_PROBE; i++) {
		struct hl_cache_entry *e = &hl_cache[(h + i) & HL_CACHE_MASK];
		if (!e->ln || e->ln == ln || e->gen != hl_cache_gen) {
			slot = e;
			break;
		}
	}
	slot->ln = ln;
	slot->gen = hl_cache_gen;
	slot->blockhl = blockhl;
	slot->blockatt = blockatt_v;
	slot->ftidx = fti;
}

void syn_blockhl_invalidate(void)
{
	hl_cache_gen++;
}

void syn_setrow(struct lbuf *lb, int row)
{
	syn_lb = lb;
	syn_row = row;
}

static int *hl_scan_att;
static int hl_scan_att_sz;
static int hl_scan_active;

/* extend the cache chain backward to row 0 or nearest cached row */
static void hl_scan_until(int target_row)
{
	if (hl_scan_active || target_row <= 0)
		return;
	int from = 0;
	for (int r = target_row - 1; r > 0; r--) {
		char *ln = lbuf_get(syn_lb, r);
		struct hl_cache_entry *e = hl_cache_find(ln);
		if (e && e->ftidx == ftidx) {
			from = r + 1;
			break;
		}
	}
	int saved_row = syn_row;
	int saved_blockhl = syn_blockhl;
	int saved_blockatt = blockatt;
	int saved_last_scdir = last_scdir;
	last_scdir = 0;
	hl_scan_active = 1;
	for (int r = from; r < target_row; r++) {
		char *ln = lbuf_get(syn_lb, r);
		if (!ln)
			break;
		int len = lbuf_s(ln)->len;
		if (len + 1 > hl_scan_att_sz) {
			hl_scan_att_sz = (len + 1) * 2;
			hl_scan_att = erealloc(hl_scan_att, hl_scan_att_sz * sizeof(int));
		}
		memset(hl_scan_att, 0, (len + 1) * sizeof(int));
		syn_row = r;
		syn_highlight(hl_scan_att, ln, len);
	}
	hl_scan_active = 0;
	syn_row = saved_row;
	syn_blockhl = saved_blockhl;
	blockatt = saved_blockatt;
	last_scdir = saved_last_scdir;
}

${SEP}.,\$;f> 
void syn_highlight\\\\(int \\\\*att, char \\\\*s, int n\\\\)
\\\\{${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ren.c:312\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3c 	int fti = ftidx, blockhl, blockca = -1, trusted = 0;
	char *cur_ln = NULL;
	if (syn_lb && syn_row >= 0 && syn_row < lbuf_len(syn_lb)) {
		cur_ln = lbuf_get(syn_lb, syn_row);
		if (syn_row == 0) {
			syn_blockhl = -1;
			blockatt = 0;
			trusted = 1;
		} else {
			char *prev_ln = lbuf_get(syn_lb, syn_row - 1);
			struct hl_cache_entry *e = hl_cache_find(prev_ln);
			if ((!e || e->ftidx != ftidx) && !hl_scan_active) {
				hl_scan_until(syn_row);
				e = hl_cache_find(prev_ln);
			}
			if (e && e->ftidx == ftidx) {
				syn_blockhl = e->blockhl;
				blockatt = e->blockatt;
				trusted = 1;
			}
		}
	}
	blockhl = syn_blockhl;
${SEP}.,\$;f> 				for \\\\(j = beg; j < end; j\\\\+\\\\+\\\\)
					att\\\\[j\\\\] = syn_merge\\\\(att\\\\[j\\\\], catt\\\\[i\\\\]\\\\);
			if \\\\(SYN_BSESET\\\\(catt\\\\[i\\\\]\\\\)\\\\) \\\\{${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ren.c:361\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3c 				int dn = !trusted && last_scdir > 0;
				if (syn_blockhl == hl && (SYN_BESET(catt[i]) || dn)) {
${SEP}.,\$;f> 					blockca = -1;
					syn_blockhl = blockca;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ren.c:364\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2${SEP}s/last_scdir > 0/dn/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ren.c:364\\${SEP}pr${INTR}${QF}}${SEP}.,\$;f> 	fti\\\\+\\\\+;
	if \\\\(ftmidx > fti && ftmap\\\\[fti-1\\\\]\\\\.ft == ftmap\\\\[fti\\\\]\\\\.ft\\\\)
		goto re;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ren.c:378\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3${SEP}s/ \\\\(b/ (!trusted && b/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ren.c:378\\${SEP}pr${INTR}${QF}}${SEP}.,\$f> 		syn_blockhl = -1;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ren.c:379\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}.a 	if (trusted && cur_ln)
		hl_cache_set(cur_ln, syn_blockhl, blockatt, ftidx);
${SEP}b2${SEP}%;f> static void vi_drawrow\\\\(int row\\\\)
\\\\{
	int l1, i, i1, lnnum = vi_lnnum;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:130\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 	int s_row = -1;
${SEP}.,\$;f> 		if \\\\(row != xrow\\\\+1 \\\\|\\\\| !c \\\\|\\\\| \\\\*c == '\\\\\\\\n'\\\\) \\\\{
			vi_rshift = \\\\(row > xrow\\\\+1 && c && \\\\*c != '\\\\\\\\n'\\\\);
			s = lbuf_get\\\\(xb, row - vi_rshift\\\\);${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:140\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 			s_row = row - vi_rshift;
${SEP}.,\$;f> 		return;
	\\\\}
	s = lbuf_get\\\\(xb, row\\\\);${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:170\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 	s_row = row;
${SEP}.,\$;f> 	skip:
	rstate \\\\+= row != xrow;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:173\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2${SEP}s/\\\\)/) {/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:173\\${SEP}pr${INTR}${QF}}${SEP}.,\$f> 		s = row \\\\? ch : ch\\\\+1;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:175\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+1c 		s_row = -1;
	} else if (lnnum && xled) {
${SEP}.,\$;f> 		vi_lncol = dir_context\\\\(s\\\\) < 0 \\\\? 0 : l1;
		memset\\\\(c, ' ', l1 - \\\\(c - tmp\\\\)\\\\);
		c\\\\[l1 - \\\\(c - tmp\\\\)\\\\] = '\\\\\\\\0';${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:193\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 		syn_setrow(xb, s_row);
${SEP}.,\$f> 		led_crender\\\\(s, row - xtop, l1, xleft, xleft \\\\+ xcols - l1\\\\)${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:194\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}.a 		syn_setrow(NULL, 0);
${SEP}.,\$;f> 		restore\\\\(ftidx\\\\)
		return;
	\\\\}${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:212\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 	if (s_row >= 0)
		syn_setrow(xb, s_row);
${SEP}.,\$f> 	led_crender\\\\(s, row - xtop, 0, xleft, xleft \\\\+ xcols\\\\)${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:213\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}.a 	syn_setrow(NULL, 0);
${SEP}b3${SEP}%;f> int syn_findhl\\\\(int id\\\\);
int syn_addhl\\\\(char \\\\*reg, int id\\\\);
void syn_init\\\\(void\\\\);${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.h:261\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a void syn_setrow(struct lbuf *lb, int row);
void syn_blockhl_invalidate(void);
${SEP}vis 2${SEP}b0${SEP}w${SEP}b1${SEP}w${SEP}b2${SEP}w${SEP}b3${SEP}w${SEP}q" $VI -e 'lbuf.c' 'ren.c' 'vi.c' 'vi.h'

exit 0
=== PATCH2VI DELTA ===
=== PATCH2VI PATCH ===
diff --git a/lbuf.c b/lbuf.c
index 0a13ff5a..bd86c6f4 100644
--- a/lbuf.c
+++ b/lbuf.c
@@ -81,6 +81,7 @@ static int linelength(char *s)
 static int lbuf_replace(struct lbuf *lb, sbuf *sb, char *s, struct lopt *lo, int n_del, int n_ins)
 {
 	int i, pos = lo->pos;
+	syn_blockhl_invalidate();
 	if (s) {
 		for (; *s; n_ins++) {
 			int l = linelength(s);
diff --git a/ren.c b/ren.c
index 86e24e4a..a9c8a5e7 100644
--- a/ren.c
+++ b/ren.c
@@ -249,6 +249,118 @@ static int blockatt;
 int ftidx;
 int syn_blockhl;
 
+/* block-highlight pair cache, keyed by lbuf line pointer */
+struct hl_cache_entry {
+	char *ln;
+	int gen;
+	int blockhl;
+	int blockatt;
+	int ftidx;
+};
+#define HL_CACHE_BITS	10
+#define HL_CACHE_SIZE	(1 << HL_CACHE_BITS)
+#define HL_CACHE_MASK	(HL_CACHE_SIZE - 1)
+#define HL_CACHE_PROBE	8
+static struct hl_cache_entry hl_cache[HL_CACHE_SIZE];
+static int hl_cache_gen = 1;
+static struct lbuf *syn_lb;
+static int syn_row;
+
+static int hl_cache_hash(char *ln)
+{
+	return (int)(((size_t)ln >> 4) & HL_CACHE_MASK);
+}
+
+static struct hl_cache_entry *hl_cache_find(char *ln)
+{
+	if (!ln)
+		return NULL;
+	int h = hl_cache_hash(ln);
+	for (int i = 0; i < HL_CACHE_PROBE; i++) {
+		struct hl_cache_entry *e = &hl_cache[(h + i) & HL_CACHE_MASK];
+		if (e->ln == ln && e->gen == hl_cache_gen)
+			return e;
+		if (!e->ln)
+			return NULL;
+	}
+	return NULL;
+}
+
+static void hl_cache_set(char *ln, int blockhl, int blockatt_v, int fti)
+{
+	if (!ln)
+		return;
+	int h = hl_cache_hash(ln);
+	struct hl_cache_entry *slot = &hl_cache[h];
+	for (int i = 0; i < HL_CACHE_PROBE; i++) {
+		struct hl_cache_entry *e = &hl_cache[(h + i) & HL_CACHE_MASK];
+		if (!e->ln || e->ln == ln || e->gen != hl_cache_gen) {
+			slot = e;
+			break;
+		}
+	}
+	slot->ln = ln;
+	slot->gen = hl_cache_gen;
+	slot->blockhl = blockhl;
+	slot->blockatt = blockatt_v;
+	slot->ftidx = fti;
+}
+
+void syn_blockhl_invalidate(void)
+{
+	hl_cache_gen++;
+}
+
+void syn_setrow(struct lbuf *lb, int row)
+{
+	syn_lb = lb;
+	syn_row = row;
+}
+
+static int *hl_scan_att;
+static int hl_scan_att_sz;
+static int hl_scan_active;
+
+/* extend the cache chain backward to row 0 or nearest cached row */
+static void hl_scan_until(int target_row)
+{
+	if (hl_scan_active || target_row <= 0)
+		return;
+	int from = 0;
+	for (int r = target_row - 1; r > 0; r--) {
+		char *ln = lbuf_get(syn_lb, r);
+		struct hl_cache_entry *e = hl_cache_find(ln);
+		if (e && e->ftidx == ftidx) {
+			from = r + 1;
+			break;
+		}
+	}
+	int saved_row = syn_row;
+	int saved_blockhl = syn_blockhl;
+	int saved_blockatt = blockatt;
+	int saved_last_scdir = last_scdir;
+	last_scdir = 0;
+	hl_scan_active = 1;
+	for (int r = from; r < target_row; r++) {
+		char *ln = lbuf_get(syn_lb, r);
+		if (!ln)
+			break;
+		int len = lbuf_s(ln)->len;
+		if (len + 1 > hl_scan_att_sz) {
+			hl_scan_att_sz = (len + 1) * 2;
+			hl_scan_att = erealloc(hl_scan_att, hl_scan_att_sz * sizeof(int));
+		}
+		memset(hl_scan_att, 0, (len + 1) * sizeof(int));
+		syn_row = r;
+		syn_highlight(hl_scan_att, ln, len);
+	}
+	hl_scan_active = 0;
+	syn_row = saved_row;
+	syn_blockhl = saved_blockhl;
+	blockatt = saved_blockatt;
+	last_scdir = saved_last_scdir;
+}
+
 static int syn_initft(int fti, int n, char *name, int flg)
 {
 	if (fti >= ftmidx)
@@ -309,7 +421,29 @@ int syn_merge(int old, int new)
 
 void syn_highlight(int *att, char *s, int n)
 {
-	int fti = ftidx, blockhl = syn_blockhl, blockca = -1;
+	int fti = ftidx, blockhl, blockca = -1, trusted = 0;
+	char *cur_ln = NULL;
+	if (syn_lb && syn_row >= 0 && syn_row < lbuf_len(syn_lb)) {
+		cur_ln = lbuf_get(syn_lb, syn_row);
+		if (syn_row == 0) {
+			syn_blockhl = -1;
+			blockatt = 0;
+			trusted = 1;
+		} else {
+			char *prev_ln = lbuf_get(syn_lb, syn_row - 1);
+			struct hl_cache_entry *e = hl_cache_find(prev_ln);
+			if ((!e || e->ftidx != ftidx) && !hl_scan_active) {
+				hl_scan_until(syn_row);
+				e = hl_cache_find(prev_ln);
+			}
+			if (e && e->ftidx == ftidx) {
+				syn_blockhl = e->blockhl;
+				blockatt = e->blockatt;
+				trusted = 1;
+			}
+		}
+	}
+	blockhl = syn_blockhl;
 	re:;
 	rset *rs = ftmap[fti].rs;
 	int subs[rs->nsubc], *catt, *iatt, sl, c;
@@ -358,10 +492,11 @@ void syn_highlight(int *att, char *s, int n)
 				for (j = beg; j < end; j++)
 					att[j] = syn_merge(att[j], catt[i]);
 			if (SYN_BSESET(catt[i])) {
-				if (syn_blockhl == hl && (SYN_BESET(catt[i]) || last_scdir > 0)) {
+				int dn = !trusted && last_scdir > 0;
+				if (syn_blockhl == hl && (SYN_BESET(catt[i]) || dn)) {
 					blockca = -1;
 					syn_blockhl = blockca;
-				} else if (syn_blockhl < 0 && (SYN_BSSET(catt[i]) || last_scdir > 0)) {
+				} else if (syn_blockhl < 0 && (SYN_BSSET(catt[i]) || dn)) {
 					syn_blockhl = hl;
 					blockca = catt[i];
 					blockatt = catt[0];
@@ -375,8 +510,10 @@ void syn_highlight(int *att, char *s, int n)
 	fti++;
 	if (ftmidx > fti && ftmap[fti-1].ft == ftmap[fti].ft)
 		goto re;
-	if (blockca >= 0 && SYN_BSSET(blockca) && !SYN_BESET(blockca) && last_scdir > 0)
+	if (!trusted && blockca >= 0 && SYN_BSSET(blockca) && !SYN_BESET(blockca) && last_scdir > 0)
 		syn_blockhl = -1;
+	if (trusted && cur_ln)
+		hl_cache_set(cur_ln, syn_blockhl, blockatt, ftidx);
 	if (syn_blockhl < 0 || blockhl < 0)
 		return;
 	for (j = 0; j < n; j++)
diff --git a/vi.c b/vi.c
index ed15bfc7..86ec1481 100644
--- a/vi.c
+++ b/vi.c
@@ -128,6 +128,7 @@ for (i = 0, ret = 0;; i++) { \
 static void vi_drawrow(int row)
 {
 	int l1, i, i1, lnnum = vi_lnnum;
+	int s_row = -1;
 	char *c, *s;
 	static char ch[5] = "~";
 	if (xmpt == 1 && !vi_status && row == xtop + xrows - 1)
@@ -138,6 +139,7 @@ static void vi_drawrow(int row)
 		if (row != xrow+1 || !c || *c == '\n') {
 			vi_rshift = (row > xrow+1 && c && *c != '\n');
 			s = lbuf_get(xb, row - vi_rshift);
+			s_row = row - vi_rshift;
 			goto skip;
 		}
 		char tmp[xcols+3], snum[32];
@@ -168,11 +170,13 @@ static void vi_drawrow(int row)
 		return;
 	}
 	s = lbuf_get(xb, row);
+	s_row = row;
 	skip:
 	rstate += row != xrow;
-	if (!s)
+	if (!s) {
 		s = row ? ch : ch+1;
-	else if (lnnum && xled) {
+		s_row = -1;
+	} else if (lnnum && xled) {
 		char tmp[32], tmp1[32], *p;
 		c = tmp, i = 0, i1 = 0;
 		if (lnnum == 1 || lnnum & 2) {
@@ -191,7 +195,9 @@ static void vi_drawrow(int row)
 		vi_lncol = dir_context(s) < 0 ? 0 : l1;
 		memset(c, ' ', l1 - (c - tmp));
 		c[l1 - (c - tmp)] = '\0';
+		syn_setrow(xb, s_row);
 		led_crender(s, row - xtop, l1, xleft, xleft + xcols - l1)
+		syn_setrow(NULL, 0);
 		preserve(int, syn_blockhl, syn_blockhl = -1;)
 		preserve(int, ftidx,)
 		syn_setft(nn_ft);
@@ -210,7 +216,10 @@ static void vi_drawrow(int row)
 		restore(ftidx)
 		return;
 	}
+	if (s_row >= 0)
+		syn_setrow(xb, s_row);
 	led_crender(s, row - xtop, 0, xleft, xleft + xcols)
+	syn_setrow(NULL, 0);
 	rstate = rstates;
 }
 
diff --git a/vi.h b/vi.h
index 96e23938..8c9bcdc4 100644
--- a/vi.h
+++ b/vi.h
@@ -259,6 +259,8 @@ void syn_reloadft(int hl, int flg);
 int syn_findhl(int id);
 int syn_addhl(char *reg, int id);
 void syn_init(void);
+void syn_setrow(struct lbuf *lb, int row);
+void syn_blockhl_invalidate(void);
 
 /* uc.c: utf-8 helper functions */
 extern unsigned char utf8_length[256];
