#!/bin/sh
# Generated by patch2vi from unified diff
# Separator: '@'
set -e

# Path to nextvi (adjust as needed)
VI=${VI:-vi}

# Verify that VI is nextvi
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi" >&2
    exit 1
fi

# Patch: ex.c
EXINIT="rcm:|sc! @|vis 6@1603a 	for (int i = 0; i < cmdnum; i++)
		ex_command(cmds[i])
.
@1591;32c , char **cmds, int cmdnum
.
@vis 4@wq" $VI -e 'ex.c'

# Patch: vi.c
EXINIT="rcm:|sc! @|vis 6@1823;27c , ex_cmds, cmdnum
.
@1816;46c c
.
@1814c 			else if (argv[i][j] == 'c') {
				if (argv[i][j+1]) {
					ex_cmds[cmdnum++] = argv[i] + j + 1;
					break;
				} else if (i + 1 < argc) {
					ex_cmds[cmdnum++] = argv[++i];
					break;
				} else {
					fprintf(stderr, \"Missing argument for -c\\n\");
					return EXIT_FAILURE;
				}
			} else {
.
@1794c 	int i, j, cmdnum = 0;
	char *ex_cmds[argc - 1];
.
@vis 4@wq" $VI -e 'vi.c'

# Patch: vi.h
EXINIT="rcm:|sc! @|vis 6@479;32c , char** cmds, int cmdnum
.
@vis 4@wq" $VI -e 'vi.h'
