#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0001-0010 0013-0014 0016-0037 0102 0104 0112-0113 0117-0121 0126 0131-0132 0136 0176-0377

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

SEP="$(printf '\001')"
# Comment to continue despite errors (errors are still printed)
QF="\\${SEP}vis 2\\${SEP}q!1"
# Command handling readability line breaks
LB="0?"
# Uncomment to enter interactive vi on patch failure
#INTR="\\${SEP}|sc|\\${SEP}vis 2:e $0:%f>:@Q:q!1"
# Uncomment to skip errors (0? = silent nop)
#DBG="0\?"

# Patch: ex.c
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}%;f> 	xgrec--;
\\\\}

${SEP}??!${DBG:-re p FAIL line 1714\\${SEP}p FAIL line 1714${INTR}${QF}}${SEP}${LB}
${SEP}+2a 
void ex_done(void)
{
	for (int i = 0; i < LEN(tempbufs); i++)
		if (tempbufs[i].lb) {
			free(tempbufs[i].path);
			lbuf_free(tempbufs[i].lb);
		}
	for (int i = 0; i < xbufcur; i++)
		bufs_free(i);
	rset_free(xkwdrs);
	free(bufs);
}
${SEP}vis 2${SEP}wq" $VI -e 'ex.c'

# Patch: regex.c
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}%f> 	unsigned int sdense\\\\[prog->sparsesz\\\\], sparsesz = 0;${SEP}??!${DBG:-re p FAIL line 638\\${SEP}p FAIL line 638${INTR}${QF}}${SEP}${LB}
${SEP}.a 	memset(sdense, 0, sizeof(int) * prog->sparsesz);
${SEP}vis 2${SEP}wq" $VI -e 'regex.c'

# Patch: ren.c
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}%f> ren_state rstates${SEP}??!${DBG:-re p FAIL line 88\\${SEP}p FAIL line 88${INTR}${QF}}${SEP}${LB}
${SEP}.a void ren_done(void)
{
	rset_free(dir_rslr);
	rset_free(dir_rsrl);
	rset_free(dir_rsctx);
	for (int i = 0; i < LEN(rstates); i++) {
		if (rstate[i].col) {
			free(rstate[i].col - 2);
			free(rstate[i].pos);
		}
	}
}

${SEP}.,\$;f> 		pats\\\\[i\\\\] = fts\\\\[i\\\\]\\\\.pat;
	syn_ftrs = rset_make\\\\(i, pats, 0\\\\);
\\\\}${SEP}??!${DBG:-re p FAIL line 410\\${SEP}p FAIL line 410${INTR}${QF}}${SEP}${LB}
${SEP}+2a 
void syn_done(void)
{
	for (; ftmidx >= 0; ftmidx--)
		rset_free(ftmap[ftmidx].rs);
	rset_free(syn_ftrs);
}
${SEP}vis 2${SEP}wq" $VI -e 'ren.c'

# Patch: vi.h
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}%f> /\\\\* text direction \\\\*/${SEP}??!${DBG:-re p FAIL line 218\\${SEP}p FAIL line 218${INTR}${QF}}${SEP}${LB}
${SEP}.a void dir_done(void);
${SEP}.,\$f> syn_init${SEP}??!${DBG:-re p FAIL line 259\\${SEP}p FAIL line 259${INTR}${QF}}${SEP}${LB}
${SEP}.a void syn_done(void);
${SEP}.,\$f> ex_init${SEP}??!${DBG:-re p FAIL line 477\\${SEP}p FAIL line 477${INTR}${QF}}${SEP}${LB}
${SEP}.a void ex_done(void);
${SEP}vis 2${SEP}wq" $VI -e 'vi.h'

exit 0
=== PATCH2VI DELTA ===
=== DELTA regex.c ===
GROUP 1
+	memset(sdense, 0, sizeof(int) * prog->sparsesz);
pattern:
	unsigned int sdense\[prog->sparsesz\], sparsesz = 0;
edit_cmd_rel:
a 	memset(sdense, 0, sizeof(int) * prog->sparsesz);
=== END DELTA ===
=== DELTA ren.c ===
GROUP 1
+void ren_done(void)
+{
+	rset_free(dir_rslr);
+	rset_free(dir_rsrl);
+	rset_free(dir_rsctx);
+	for (int i = 0; i < LEN(rstates); i++) {
+		if (rstate[i].col) {
+			free(rstate[i].col - 2);
+			free(rstate[i].pos);
+		}
+	}
+}
+
pattern:
ren_state rstates
edit_cmd_rel:
a void ren_done(void)
{
	rset_free(dir_rslr);
	rset_free(dir_rsrl);
	rset_free(dir_rsctx);
	for (int i = 0; i < LEN(rstates); i++) {
		if (rstate[i].col) {
			free(rstate[i].col - 2);
			free(rstate[i].pos);
		}
	}
}

=== END DELTA ===
=== DELTA vi.h ===
GROUP 1
+void dir_done(void);
pattern:
/\* text direction \*/
edit_cmd_rel:
a void dir_done(void);
GROUP 2
+void syn_done(void);
pattern:
syn_init
edit_cmd_rel:
a void syn_done(void);
GROUP 3
+void ex_done(void);
pattern:
ex_init
edit_cmd_rel:
a void ex_done(void);
=== END DELTA ===
=== PATCH2VI PATCH ===
diff --git a/ex.c b/ex.c
index 45b561b5..df4b36fe 100644
--- a/ex.c
+++ b/ex.c
@@ -1712,6 +1712,19 @@ void ex(void)
 	xgrec--;
 }
 
+
+void ex_done(void)
+{
+	for (int i = 0; i < LEN(tempbufs); i++)
+		if (tempbufs[i].lb) {
+			free(tempbufs[i].path);
+			lbuf_free(tempbufs[i].lb);
+		}
+	for (int i = 0; i < xbufcur; i++)
+		bufs_free(i);
+	rset_free(xkwdrs);
+	free(bufs);
+}
 void ex_init(char **files, int n)
 {
 	xbufsalloc = MAX(n, xbufsalloc);
diff --git a/regex.c b/regex.c
index ff88bb41..42399e6a 100644
--- a/regex.c
+++ b/regex.c
@@ -636,6 +636,7 @@ static int re_pikevm(rcode *prog, const char *s, const char **subp, int nsubc, i
 	int si = 0, clistidx = 0, nlistidx, mcont = MATCH;
 	int eol_ch = flg & REG_NEWLINE ? '\n' : 0;
 	unsigned int sdense[prog->sparsesz], sparsesz = 0;
+	memset(sdense, 0, sizeof(int) * prog->sparsesz);
 	char nsubs[prog->sub];
 	for (i = 0; i < prog->laidx; i++)
 		lb[i] = NULL;
diff --git a/ren.c b/ren.c
index a98fc3fa..34883c30 100644
--- a/ren.c
+++ b/ren.c
@@ -86,6 +86,19 @@ static int ren_cwid(char *s, int pos)
 }
 
 ren_state rstates[3]; /* 0 = current line, 1 = all other lines, 2 = aux rendering */
+void ren_done(void)
+{
+	rset_free(dir_rslr);
+	rset_free(dir_rsrl);
+	rset_free(dir_rsctx);
+	for (int i = 0; i < LEN(rstates); i++) {
+		if (rstate[i].col) {
+			free(rstate[i].col - 2);
+			free(rstate[i].pos);
+		}
+	}
+}
+
 ren_state *rstate = rstates;
 
 /* specify the screen position of the characters in s */
@@ -408,3 +421,10 @@ void syn_init(void)
 		pats[i] = fts[i].pat;
 	syn_ftrs = rset_make(i, pats, 0);
 }
+
+void syn_done(void)
+{
+	for (; ftmidx >= 0; ftmidx--)
+		rset_free(ftmap[ftmidx].rs);
+	rset_free(syn_ftrs);
+}
diff --git a/vi.h b/vi.h
index 59f3543e..381578f9 100644
--- a/vi.h
+++ b/vi.h
@@ -216,6 +216,7 @@ int ren_noeol(char *s, int p);
 int ren_off(char *s, int p);
 char *ren_translate(char *s, char *ln);
 /* text direction */
+void dir_done(void);
 int dir_context(char *s);
 void dir_init(void);
 /* syntax highlighting */
@@ -257,6 +258,7 @@ void syn_reloadft(int hl, int flg);
 int syn_findhl(int id);
 int syn_addhl(char *reg, int id);
 void syn_init(void);
+void syn_done(void);
 
 /* uc.c: utf-8 helper functions */
 extern unsigned char utf8_length[256];
@@ -475,6 +477,7 @@ void ex_cprint(char *line, char *ft, int r, int c, int left, int flg);
 #define ex_cprint2(line, ft, r, c, left, flg) { RS(2, ex_cprint(line, ft, r, c, left, flg)); }
 #define ex_print(line, ft) { RS(2, ex_cprint(line, ft, -1, 0, 0, 1)); }
 void ex_init(char **files, int n);
+void ex_done(void);
 void ex_bufpostfix(struct buf *p, int clear);
 int ex_krs(rset **krs, int *dir);
 void ex_krsset(char *kwd, int dir);
