#!/bin/sh
# Generated by patch2vi from unified diff
# Separator: '@'
set -e

# Path to nextvi (adjust as needed)
VI=${VI:-vi}

# Verify that VI is nextvi
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi" >&2
    exit 1
fi

# Patch: ex.c
EXINIT="rcm:|sc! @|vis 6@%;f> 	if \\\\(\\\\(s = getenv\\\\(\"EXINIT\"\\\\)\\\\)\\\\)
		ex_command\\\\(s\\\\)
\\\\}@;=
@.+2a 
void ex_done(void)
{
	for (int i = 0; i < LEN(tempbufs); i++)
		if (tempbufs[i].lb) {
			free(tempbufs[i].path);
			lbuf_free(tempbufs[i].lb);
		}
	for (int i = 0; i < xbufcur; i++)
		bufs_free(i);
	rset_free(xkwdrs);
	free(bufs);
}
.
@vis 4@wq" $VI -e 'ex.c'

# Patch: regex.c
EXINIT="rcm:|sc! @|vis 6@%;f> 	int si = 0, clistidx = 0, nlistidx, mcont = MATCH;
	int eol_ch = flg & REG_NEWLINE \\\\? '\\\\\\\\n' : 0;
	unsigned int sdense\\\\[prog->sparsesz\\\\], sparsesz = 0;@;=
@.+2a 	memset(sdense, 0, sizeof(int) * prog->sparsesz);
.
@vis 4@wq" $VI -e 'regex.c'

# Patch: ren.c
EXINIT="rcm:|sc! @|vis 6@%;f> ren_state rstates\\\\[3\\\\]; /\\\\* 0 = current line, 1 = all other lines, 2 = aux rendering \\\\*/
ren_state \\\\*rstate = rstates;
@;=
@.+2a void ren_done(void)
{
	rset_free(dir_rslr);
	rset_free(dir_rsrl);
	rset_free(dir_rsctx);
	for (int i = 0; i < LEN(rstates); i++) {
		if (rstate[i].col) {
			free(rstate[i].col - 2);
			free(rstate[i].pos);
		}
	}
}

.
@.,$;f+ 		pats\\\\[i\\\\] = fts\\\\[i\\\\]\\\\.pat;
	syn_ftrs = rset_make\\\\(i, pats, 0\\\\);
\\\\}@;=
@.+2a 
void syn_done(void)
{
	for (; ftmidx >= 0; ftmidx--)
		rset_free(ftmap[ftmidx].rs);
	rset_free(syn_ftrs);
}
.
@vis 4@wq" $VI -e 'ren.c'

# Patch: vi.c
EXINIT="rcm:|sc! @|vis 6@%;f> 	ex_regput\\\\(tolower\\\\(c\\\\), s, isupper\\\\(c\\\\)\\\\);
\\\\}
@;=
@.+2a static void vi_regdone(void)
{
	for (int i = 0; i < LEN(xregs); i++)
		if (xregs[i])
			sbuf_free(xregs[i])
}

.
@.,$;f+ 		ex\\\\(\\\\);
	else
		vi\\\\(1\\\\);@;=
@.+2a 	ex_done();
.
@.-1@>	term_done\\(\\);>a 	free(ibuf);
	rset_free(fsincl);
.
@.,$;f+ 		term_pos\\\\(xrows - !vi_status, 0\\\\);
		term_kill\\\\(\\\\);
	\\\\}@;=
@.+2a 	vi_regdone();
	syn_done();
	ren_done();
	led_done();
.
@vis 4@wq" $VI -e 'vi.c'

# Patch: vi.h
EXINIT="rcm:|sc! @|vis 6@%;f> /\\\\* text direction \\\\*/
int dir_context\\\\(char \\\\*s\\\\);
void dir_init\\\\(void\\\\);@;=
@.+2a void dir_done(void);
.
@.,$;f+ int syn_findhl\\\\(int id\\\\);
int syn_addhl\\\\(char \\\\*reg, int id\\\\);
void syn_init\\\\(void\\\\);@;=
@.+2a void syn_done(void);
.
@.,$;f+ #define ex_print\\\\(line, ft\\\\) \\\\{ RS\\\\(2, ex_cprint\\\\(line, ft, -1, 0, 0, 1\\\\)\\\\); \\\\}
void ex_init\\\\(char \\\\*\\\\*files, int n\\\\);
void ex_bufpostfix\\\\(struct buf \\\\*p, int clear\\\\);@;=
@.+2a void ex_done(void);
.
@vis 4@wq" $VI -e 'vi.h'
