#!/bin/sh
EXINIT="se noled|:1!wc -l *.h\|sort|\$k a|\$! wc -l *.c\|sort"
EXINIT="${EXINIT}|1|&G|&O+---------------------------------------+"
EXINIT="${EXINIT}|%s/ /	/"
EXINIT="${EXINIT}|2,\$g//&I\\\| "
EXINIT="${EXINIT}|2,\$g//&A	\\\||2|&kr+|ya"
EXINIT="${EXINIT}|/vi\.h/|&A definitions/aux	\\|"
EXINIT="${EXINIT}|/kmap\.h/|&A keymap translation	\\|"
EXINIT="${EXINIT}|/conf\.c/|&A hl/ft/td config	\\|"
EXINIT="${EXINIT}|/term\.c/|&A low level IO		\\|"
EXINIT="${EXINIT}|/ren\.c/|&A positioning/syntax	\\|"
EXINIT="${EXINIT}|/lbuf\.c/|&A file/line buffer	\\|"
EXINIT="${EXINIT}|/uc\.c/|&A UTF-8 support		\\|"
EXINIT="${EXINIT}|/regex\.c/|&A extended RE		\\|"
EXINIT="${EXINIT}|/led\.c/|&A insert mode/output	\\|"
EXINIT="${EXINIT}|/ex\.c/|&A ex options/commands	\\|"
EXINIT="${EXINIT}|/vi\.c/|&A normal mode/general	\\|"
EXINIT="${EXINIT}|/total/|&A wc -l *.c\|sort	\\|"
EXINIT="${EXINIT}|\$|pu|'a|-1|pu"
EXINIT="${EXINIT}|se pr=A|1,\$p|pu a \!cat|q!"
vi -em
