#!/bin/sh
EXINIT="se noled:1!wc -l *.h|sort:\$k a:\$!wc -l *.c|sort"
EXINIT="${EXINIT}:1:&G:&O_:ya:g/^[0-9]/&I :1"
EXINIT="${EXINIT}:/vi\.h/:&A | definitions/aux"
EXINIT="${EXINIT}:0:/kmap\.h/:&A | keymap translation"
EXINIT="${EXINIT}:0:/conf\.c/:&A | hl/ft/td config"
EXINIT="${EXINIT}:0:/term\.c/:&A | low level IO"
EXINIT="${EXINIT}:0:/ren\.c/:&A | positioning/syntax"
EXINIT="${EXINIT}:0:/lbuf\.c/:&A | file/line buffer"
EXINIT="${EXINIT}:0:/uc\.c/:&A | UTF-8 support"
EXINIT="${EXINIT}:0:/regex\.c/:&A | extended RE"
EXINIT="${EXINIT}:0:/led\.c/:&A | insert mode/output"
EXINIT="${EXINIT}:0:/\<ex\.c\>/:&A | ex options/commands"
EXINIT="${EXINIT}:0:/vi\.c/:&A | normal mode/general"
EXINIT="${EXINIT}:0:/total/:&A | wc -l *.c\(basort"
EXINIT="${EXINIT}:\$:pu:'a:-1:pu"
EXINIT="${EXINIT}:se led:se vis=6:1,\$p:se vis=4:q!" vi -em
