#!/bin/sh
# Generated by patch2vi from unified diff
# Available separators: 0001 0002 0003 0004 0005 0006 0007 0010 0013 0014 0016 0017 0020 0021 0022 0023 0024 0025 0026 0027 0030 0031 0032 0033 0034 0035 0036 0037 0107 0110 0112 0120 0121 0123 0124 0126 0130 0131 0132 0136 0176 0177 0200 0201 0202 0203 0204 0205 0206 0207 0210 0211 0212 0213 0214 0215 0216 0217 0220 0221 0222 0223 0224 0225 0226 0227 0230 0231 0232 0233 0234 0235 0236 0237 0240 0241 0242 0243 0244 0245 0246 0247 0250 0251 0252 0253 0254 0255 0256 0257 0260 0261 0262 0263 0264 0265 0266 0267 0270 0271 0272 0273 0274 0275 0276 0277 0300 0301 0302 0303 0304 0305 0306 0307 0310 0311 0312 0313 0314 0315 0316 0317 0320 0321 0322 0323 0324 0325 0326 0327 0330 0331 0332 0333 0334 0335 0336 0337 0340 0341 0342 0343 0344 0345 0346 0347 0350 0351 0352 0353 0354 0355 0356 0357 0360 0361 0362 0363 0364 0365 0366 0367 0370 0371 0372 0373 0374 0375 0376 0377
set -e

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

# Path to nextvi (adjust as needed)
VI=${VI:-vi}

# Uncomment to enter interactive vi on patch failure
#DBG="|sc|vis 2:e $0:@Q:q!1"
# Uncomment to skip errors (. = silent nop)
#DBG="."
# Set QF=. to continue despite errors (errors are still printed)
#QF=.

# Verify that VI is nextvi
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi" >&2
    exit 1
fi

# Patch: led.c
SEP="$(printf '\001')"
QF=${QF-"$(printf 'vis 2\\\001q! 1')"}
EXINIT="rcm:|sc! \\\\${SEP}|vis 3${SEP}%;f> 
${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1\\${SEP}${QF}}${SEP};=
${SEP}.a #define LEDBACK 300
#define LEDFORW 300

.
${SEP}.,\$;f> 	if \\\\(!xled\\\\)
		return;
	ren_state \\\\*r = ren_position\\\\(s0\\\\);${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 148\\${SEP}${QF}}${SEP};=
${SEP}+2a 	int fcbeg = cbeg - LEDBACK < 0 ? 0 : cbeg - LEDBACK;
	int fcend = cend + LEDFORW;
	int fcterm = fcend - fcbeg; /* fake the render dimensions */
.
${SEP}.,\$;f> 	char \\\\*bound = NULL;
	char \\\\*\\\\*chrs = r->chrs;	/\\\\* chrs\\\\[i\\\\]: the i-th character in s0 \\\\*/
	int off\\\\[cterm\\\\+1\\\\];	/\\\\* off\\\\[i\\\\]: the character at screen position i \\\\*/${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 154\\${SEP}${QF}}${SEP};=
${SEP}+3,#+2c 	int att[fcterm+1];	/* att[i]: the attributes of i-th character */
	int stt[fcterm+1];	/* stt[i]: remap off indexes */
	int ctt[fcterm+1];	/* ctt[i]: cterm bound attrs */
.
${SEP}.,\$;f> 			off\\\\[c - cbeg\\\\] = c <= r->cmax \\\\? r->col\\\\[c\\\\] : -1;
	\\\\}
	if \\\\(r->cmax > cterm \\\\|\\\\| cbeg\\\\) \\\\{${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 167\\${SEP}${QF}}${SEP};=
${SEP}+2a 		c = 0;
.
${SEP}.,\$;f> 		if \\\\(o >= 0 && r->cmax > cterm && r->pos\\\\[o\\\\] \\\\+ r->wid\\\\[o\\\\] > cend\\\\)
			while \\\\(off\\\\[i\\\\] == o\\\\)
				off\\\\[ctx < 0 \\\\? i\\\\+\\\\+ : i--\\\\] = -1;${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 178\\${SEP}${QF}}${SEP};=
${SEP}+3c 		l = cbeg <= r->cmax ? r->col[cbeg] : -1;
		for (o = 0; l > 0 && l <= n && o < LEDBACK; o++) {
			if (r->pos[l] < cbeg && c < fcterm) {
				atti++;
				att[c++] = l;
			}
			l -= ctx;
		}
		for (i = 0; i < cterm;) {
.
${SEP}.,\$;f> 				for \\\\(; off\\\\[i\\\\] == o; i\\\\+\\\\+\\\\);
			\\\\}
		\\\\}${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 183\\${SEP}${QF}}${SEP};=
${SEP}+2a 		l = cend <= r->cmax ? r->col[cend] : -1;
		for (o = 0; l > 0 && l <= n && o < LEDFORW; o++) {
			if (r->pos[l] >= cend && c < fcterm) {
				att[c++] = l;
			}
			l += ctx;
		}
.
${SEP}.,\$;f> 		sbufn_null\\\\(bsb\\\\)
		bound = bsb->s;
	\\\\}${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 205\\${SEP}${QF}}${SEP};=
${SEP}+3${SEP}s/ c/ fc/${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 205\\${SEP}${QF}}${SEP}.,\$f> 	if \\\\(xhl\\\\)${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 207\\${SEP}${QF}}${SEP};=
${SEP}+1${SEP}s/ c/ fc/${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 207\\${SEP}${QF}}${SEP}.,\$;f> 			if \\\\(!bound\\\\)
				att\\\\[p->off\\\\] = syn_merge\\\\(p->att, att\\\\[p->off\\\\]\\\\);
			else if \\\\(c && stt\\\\[0\\\\] <= p->off && stt\\\\[c-1\\\\] >= p->off\\\\) \\\\{${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 217\\${SEP}${QF}}${SEP};=
${SEP}+3${SEP}s/0/atti/${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 217\\${SEP}${QF}}${SEP}vis 2${SEP}wq" $VI -e 'led.c'

exit 0
=== PATCH2VI DELTA ===
=== DELTA led.c ===
--- /tmp/patch2vi_dFNhGc_led.c.diff.orig
+++ /tmp/patch2vi_dFNhGc_led.c.diff
@@ -7,7 +7,7 @@
 === SEARCH COMMAND ===
 %f>
 === SEARCH PATTERN (offset: 1) ===
-/\* line editing and drawing \*/
+
 --- extra (delete to include) ---
 
 static sbuf \*suggestsb;
=== PATCH2VI PATCH ===
diff --git a/led.c b/led.c
index 7aba6ef6..8c05446f 100644
--- a/led.c
+++ b/led.c
@@ -1,4 +1,7 @@
 /* line editing and drawing */
+#define LEDBACK 300
+#define LEDFORW 300
+
 
 static sbuf *suggestsb;
 static sbuf *acsb;
@@ -146,14 +149,17 @@ void led_render(char *s0, int cbeg, int cend)
 	if (!xled)
 		return;
 	ren_state *r = ren_position(s0);
+	int fcbeg = cbeg - LEDBACK < 0 ? 0 : cbeg - LEDBACK;
+	int fcend = cend + LEDFORW;
+	int fcterm = fcend - fcbeg; /* fake the render dimensions */
 	int j, c, l, i, o, n = r->n;
 	int att_old = 0, atti = 0, cterm = cend - cbeg;
 	char *bound = NULL;
 	char **chrs = r->chrs;	/* chrs[i]: the i-th character in s0 */
 	int off[cterm+1];	/* off[i]: the character at screen position i */
-	int att[cterm+1];	/* att[i]: the attributes of i-th character */
-	int stt[cterm+1];	/* stt[i]: remap off indexes */
-	int ctt[cterm+1];	/* ctt[i]: cterm bound attrs */
+	int att[fcterm+1];	/* att[i]: the attributes of i-th character */
+	int stt[fcterm+1];	/* stt[i]: remap off indexes */
+	int ctt[fcterm+1];	/* ctt[i]: cterm bound attrs */
 	int ctx = r->ctx;
 	off[cterm] = -1;
 	if (ctx < 0) {
@@ -165,6 +171,7 @@ void led_render(char *s0, int cbeg, int cend)
 			off[c - cbeg] = c <= r->cmax ? r->col[c] : -1;
 	}
 	if (r->cmax > cterm || cbeg) {
+		c = 0;
 		i = ctx < 0 ? cterm-1 : 0;
 		o = off[i];
 		if (o >= 0 && cbeg && r->pos[o] < cbeg)
@@ -175,12 +182,27 @@ void led_render(char *s0, int cbeg, int cend)
 		if (o >= 0 && r->cmax > cterm && r->pos[o] + r->wid[o] > cend)
 			while (off[i] == o)
 				off[ctx < 0 ? i++ : i--] = -1;
-		for (i = 0, c = 0; i < cterm;) {
+		l = cbeg <= r->cmax ? r->col[cbeg] : -1;
+		for (o = 0; l > 0 && l <= n && o < LEDBACK; o++) {
+			if (r->pos[l] < cbeg && c < fcterm) {
+				atti++;
+				att[c++] = l;
+			}
+			l -= ctx;
+		}
+		for (i = 0; i < cterm;) {
 			if ((o = off[i++]) >= 0) {
 				att[c++] = o;
 				for (; off[i] == o; i++);
 			}
 		}
+		l = cend <= r->cmax ? r->col[cend] : -1;
+		for (o = 0; l > 0 && l <= n && o < LEDFORW; o++) {
+			if (r->pos[l] >= cend && c < fcterm) {
+				att[c++] = l;
+			}
+			l += ctx;
+		}
 		stt[0] = 0;
 		for (i = 1; i < c; i++) {
 			int key0 = att[i];
@@ -202,9 +224,9 @@ void led_render(char *s0, int cbeg, int cend)
 		sbufn_null(bsb)
 		bound = bsb->s;
 	}
-	memset(att, 0, MIN(n, cterm+1) * sizeof(att[0]));
+	memset(att, 0, MIN(n, fcterm+1) * sizeof(att[0]));
 	if (xhl)
-		syn_highlight(att, bound ? bound : s0, MIN(n, cterm));
+		syn_highlight(att, bound ? bound : s0, MIN(n, fcterm));
 	free(bound);
 	if (led_attsb && xhl) {
 		led_att *p = (led_att*)led_attsb->s;
@@ -214,7 +236,7 @@ void led_render(char *s0, int cbeg, int cend)
 			if (!bound)
 				att[p->off] = syn_merge(p->att, att[p->off]);
 			else if (c && stt[0] <= p->off && stt[c-1] >= p->off) {
-				i = p->off - stt[0];
+				i = p->off - stt[atti];
 				if (i < c && stt[i] == p->off) {
 					att[i] = syn_merge(p->att, att[i]);
 					continue; /* text not reordered */
