#!/bin/sh
# Generated by patch2vi from unified diff
# Available separators: 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0x0b 0x0c 0x0e 0x0f 0x10 0x11 0x12 0x13 0x14 0x15 0x16 0x17 0x18 0x19 0x1a 0x1b 0x1c 0x1d 0x1e 0x1f 0x4a 0x4b 0x50 0x51 0x54 0x56 0x58 0x5a 0x7e 0x7f 0x80 0x81 0x82 0x83 0x84 0x85 0x86 0x87 0x88 0x89 0x8a 0x8b 0x8c 0x8d 0x8e 0x8f 0x90 0x91 0x92 0x93 0x94 0x95 0x96 0x97 0x98 0x99 0x9a 0x9b 0x9c 0x9d 0x9e 0x9f 0xa0 0xa1 0xa2 0xa3 0xa4 0xa5 0xa6 0xa7 0xa8 0xa9 0xaa 0xab 0xac 0xad 0xae 0xaf 0xb0 0xb1 0xb2 0xb3 0xb4 0xb5 0xb6 0xb7 0xb8 0xb9 0xba 0xbb 0xbc 0xbd 0xbe 0xbf 0xc0 0xc1 0xc2 0xc3 0xc4 0xc5 0xc6 0xc7 0xc8 0xc9 0xca 0xcb 0xcc 0xcd 0xce 0xcf 0xd0 0xd1 0xd2 0xd3 0xd4 0xd5 0xd6 0xd7 0xd8 0xd9 0xda 0xdb 0xdc 0xdd 0xde 0xdf 0xe0 0xe1 0xe2 0xe3 0xe4 0xe5 0xe6 0xe7 0xe8 0xe9 0xea 0xeb 0xec 0xed 0xee 0xef 0xf0 0xf1 0xf2 0xf3 0xf4 0xf5 0xf6 0xf7 0xf8 0xf9 0xfa 0xfb 0xfc 0xfd 0xfe 0xff
set -e

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

# Path to nextvi (adjust as needed)
VI=${VI:-vi}

# Uncomment to enter interactive vi on patch failure
#DBG="|sc|vis 2:e $0:@Q:q!1"
# Uncomment to skip errors (. = silent nop)
#DBG="."
# Set QF=. to continue despite errors (errors are still printed)
#QF=.

# Verify that VI is nextvi
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi" >&2
    exit 1
fi

# Patch: conf.c
SEP="$(printf '\x01')"
QF=${QF-"$(printf 'vis 2\\\x01q! 1')"}
EXINIT="rcm:|sc! \\\\${SEP}|vis 3${SEP}%;f> \\\\(\\\\?:\\\\(\\\\[,;\\\\]#\\\\?\\\\)\\\\[ \\\\\\\\t\\\\]\\\\*\\\\(\\\\(\\\\?:\\\\\\\\\\\\\\\\\\\\|\\\\.\\\\*\\\\?\\\\(\\\\?:\\\\(\\\\?<\\\\^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\)\\\\\\\\\\\\\\\\\\\\|\\\\|\\\\\$\\\\)\\\\[ \\\\\\\\t\\\\]\\\\*\\\\)\\\\*\\\\(\\\\?:\\\\(\\\\?:<\\\\.\\\\*\\\\?\\\\(\\\\?:\\\\(\\\\?<\\\\^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\)<\\\\|\\\\\$\\\\)\\\\|>\\\\.\\\\*\\\\?\\\\(\\\\?:\\\\(\\\\?<\\\\^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\)>\\\\|\\\\\$\\\\)\\\\)\\\\|\\\\\\\\
\\\\(\\\\?:'\\\\[a-z'\`\\\\[\\\\\\\\\\\\\\\\\\\\]\\\\*\\\\]\\\\)\\\\|\\\\(\\\\[\\\\.\\\\\$\\\\]\\\\|\\\\[0-9 \\\\\\\\t\\\\]\\\\*\\\\)\\\\?\\\\)\\\\)\\\\(\\\\?:\\\\(\\\\[-\\\\*-\\\\+/%\\\\]\\\\)\\\\[ \\\\\\\\t\\\\]\\\\*\\\\(\\\\[0-9\\\\]\\\\+\\\\)\\\\[ \\\\\\\\t\\\\]\\\\*\\\\)\\\\*\\\\(\\\\?:\\\\[ \\\\\\\\t\\\\]\\\\*\\\\\\\\\\\\\\\\\\\\|\\\\.\\\\*\\\\?\\\\(\\\\?:\\\\(\\\\?<\\\\^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\)\\\\\\\\\\\\\\\\\\\\|\\\\|\\\\\$\\\\)\\\\)\\\\*\\\\[ \\\\\\\\t\\\\]\\\\*\\\\)\\\\*\\\\)\\\\\\\\
\\\\(\\\\(pac\\\\|pr\\\\|ai\\\\|ish\\\\|err\\\\|ic\\\\|grp\\\\|mpt\\\\|rcm\\\\|shape\\\\|seq\\\\|ts\\\\|td\\\\|order\\\\|hl\\\\[lwpr\\\\]\\\\?\\\\|left\\\\|lim\\\\|led\\\\|vis\\\\)\\\\\\\\${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 261\\${SEP}${QF}}${SEP};=
${SEP}+3${SEP}s/mj\\\\]/j]|md?/${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 261\\${SEP}${QF}}${SEP}vis 2${SEP}wq" $VI -e 'conf.c'

# Patch: ex.c
SEP="$(printf '\x01')"
QF=${QF-"$(printf 'vis 2\\\x01q! 1')"}
EXINIT="rcm:|sc! \\\\${SEP}|vis 3${SEP}%;f> 	return NULL;
\\\\)

${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1445\\${SEP}${QF}}${SEP};=
${SEP}+2a static void
modal_dispatch(char *tape)
{
	char *s = tape;
	sbuf_smake(out, 64)
	while (*s) {
		while (*s == ' ') s++;
		if (!*s) break;
		char *end = walk(s);
		if (*s == '(' && s[1] == '\$') {
			char cmd[512];
			char *p = s + 2;
			char *cap = end - 1;
			int len = (int)(cap - p);
			if (len > 0 && len < (int)sizeof(cmd) - 1) {
				memcpy(cmd, p, len);
				cmd[len] = '\\\\0';
				ex_exec(cmd);
			}
		} else {
			sbuf_mem(out, s, end - s)
			sbuf_chr(out, ' ')
		}
		s = end;
	}
	if (out->s_n > 0) {
		sbufn_null(out)
		ex_print(out->s, NULL)
	}
	free(out->s);
}

static void *
ec_modal(char *loc, char *cmd, char *arg)
{
	/* reset modal state */
	flip = 0;
	src_ = bank_a; dst_ = bank_b;
	rules_ = rules; dict_ = dict;
	stack_ = stack;
	memset(regs, 0, sizeof(regs));
	bank_a[0] = bank_b[0] = 0;
	quiet = 1;

	/* load rules from lbuf range into src_ */
	char *ptr = src_;
	if (loc[0] && lbuf_len(xb)) {
		int beg = 0, end = 0, o1 = 0, o2 = -1;
		if (ex_region(loc, &beg, &end, &o1, &o2))
			return xrerr;
		for (int i = beg; i < end; i++) {
			char *ln = lbuf_get(xb, i);
			if (ln) {
				ptr = mem_import(ln, ptr);
				if (ptr < src_ + sizeof(bank_a) - 1)
					*ptr++ = ' ';
			}
		}
	}

	/* append arg (initial tape) to src_ */
	if (*arg)
		ptr = mem_import(arg, ptr);

	/* trim trailing whitespace and null-terminate */
	while (ptr > src_ && *(ptr - 1) <= ' ') ptr--;
	*ptr = '\\\\0';

	/* set up output capture */
	sbuf_smake(out, 64)
	modal_output = out;

	/* rewrite loop */
	int rw = 0, lim = cycles;
	cycles = 0x200000;
	while (rewrite() && ++rw)
		if (!--cycles) {
			cycles = lim;
			modal_output = NULL;
			free(out->s);
			return \"modal: rewrites exceeded\";
		}
	cycles = lim;
	modal_output = NULL;

	/* flush string output captured via device_write */
	if (out->s_n > 0) {
		sbufn_null(out)
		ex_print(out->s, NULL)
	}
	free(out->s);

	/* dispatch (\$cmd...) forms and print residue */
	modal_dispatch(src_);
	return NULL;
}

.
${SEP}.,\$;f> 	\\\\{\"g!\", ec_glob\\\\},
	\\\\{\"g\", ec_glob\\\\},
	EO\\\\(mpt\\\\),${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1494\\${SEP}${QF}}${SEP};=
${SEP}+2a 	{\"md\", ec_modal},
.
${SEP}vis 2${SEP}wq" $VI -e 'ex.c'

# Patch: vi.c
SEP="$(printf '\x01')"
QF=${QF-"$(printf 'vis 2\\\x01q! 1')"}
EXINIT="rcm:|sc! \\\\${SEP}|vis 3${SEP}%;f> #include <sys/wait\\\\.h>
#include \"vi\\\\.h\"
#include \"conf\\\\.c\"${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 17\\${SEP}${QF}}${SEP};=
${SEP}+2a #include \"modal.c\"
.
${SEP}vis 2${SEP}wq" $VI -e 'vi.c'

exit 0
=== PATCH2VI DELTA ===
=== PATCH2VI PATCH ===
diff --git a/conf.c b/conf.c
index fcab3ea4..c3a84af9 100644
--- a/conf.c
+++ b/conf.c
@@ -258,7 +258,7 @@ return|select|switch|type|var))\\>", A(GR1, BL1 | SYN_BD, YE1)},
 (?:([,;]#?)[ \t]*((?:\\|.*?(?:(?<^\\\\)\\||$)[ \t]*)*(?:(?:<.*?(?:(?<^\\\\)<|$)|>.*?(?:(?<^\\\\)>|$))|\
 (?:'[a-z'`[\\]*])|([.$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*([0-9]+)[ \t]*)*(?:[ \t]*\\|.*?(?:(?<^\\\\)\\||$))*[ \t]*)*)\
 ((pac|pr|ai|ish|err|ic|grp|mpt|rcm|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
-|[@&!=dmj]|\\?\\?\?!?|\\?!|b[psx]?|p[uh]?|ac?|e[f!]?!?|f[-+><tdp]?|inc|i|sc!?|\
+|[@&!=dj]|md?|\\?\\?\?!?|\\?!|b[psx]?|p[uh]?|ac?|e[f!]?!?|f[-+><tdp]?|inc|i|sc!?|\
 (?:g!?|s)[ \t]?(.)?|q!?|reg?\\+?|rd?|w(?:q!|[q!])?|u[czb]?|x!?|ya!?|cm!?|cd?)?",
 		A(BL1 | SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1)},
 	{ex_ft, "\\\\(.)", A(AY1 | SYN_BD, YE)},
diff --git a/ex.c b/ex.c
index a5f4fe52..f39058ce 100644
--- a/ex.c
+++ b/ex.c
@@ -1443,6 +1443,103 @@ _EO(left,
 	return NULL;
 )
 
+static void
+modal_dispatch(char *tape)
+{
+	char *s = tape;
+	sbuf_smake(out, 64)
+	while (*s) {
+		while (*s == ' ') s++;
+		if (!*s) break;
+		char *end = walk(s);
+		if (*s == '(' && s[1] == '$') {
+			char cmd[512];
+			char *p = s + 2;
+			char *cap = end - 1;
+			int len = (int)(cap - p);
+			if (len > 0 && len < (int)sizeof(cmd) - 1) {
+				memcpy(cmd, p, len);
+				cmd[len] = '\0';
+				ex_exec(cmd);
+			}
+		} else {
+			sbuf_mem(out, s, end - s)
+			sbuf_chr(out, ' ')
+		}
+		s = end;
+	}
+	if (out->s_n > 0) {
+		sbufn_null(out)
+		ex_print(out->s, NULL)
+	}
+	free(out->s);
+}
+
+static void *
+ec_modal(char *loc, char *cmd, char *arg)
+{
+	/* reset modal state */
+	flip = 0;
+	src_ = bank_a; dst_ = bank_b;
+	rules_ = rules; dict_ = dict;
+	stack_ = stack;
+	memset(regs, 0, sizeof(regs));
+	bank_a[0] = bank_b[0] = 0;
+	quiet = 1;
+
+	/* load rules from lbuf range into src_ */
+	char *ptr = src_;
+	if (loc[0] && lbuf_len(xb)) {
+		int beg = 0, end = 0, o1 = 0, o2 = -1;
+		if (ex_region(loc, &beg, &end, &o1, &o2))
+			return xrerr;
+		for (int i = beg; i < end; i++) {
+			char *ln = lbuf_get(xb, i);
+			if (ln) {
+				ptr = mem_import(ln, ptr);
+				if (ptr < src_ + sizeof(bank_a) - 1)
+					*ptr++ = ' ';
+			}
+		}
+	}
+
+	/* append arg (initial tape) to src_ */
+	if (*arg)
+		ptr = mem_import(arg, ptr);
+
+	/* trim trailing whitespace and null-terminate */
+	while (ptr > src_ && *(ptr - 1) <= ' ') ptr--;
+	*ptr = '\0';
+
+	/* set up output capture */
+	sbuf_smake(out, 64)
+	modal_output = out;
+
+	/* rewrite loop */
+	int rw = 0, lim = cycles;
+	cycles = 0x200000;
+	while (rewrite() && ++rw)
+		if (!--cycles) {
+			cycles = lim;
+			modal_output = NULL;
+			free(out->s);
+			return "modal: rewrites exceeded";
+		}
+	cycles = lim;
+	modal_output = NULL;
+
+	/* flush string output captured via device_write */
+	if (out->s_n > 0) {
+		sbufn_null(out)
+		ex_print(out->s, NULL)
+	}
+	free(out->s);
+
+	/* dispatch ($cmd...) forms and print residue */
+	modal_dispatch(src_);
+	return NULL;
+}
+
 #undef EO
 #define EO(opt) {#opt, eo_##opt}
 
@@ -1492,6 +1589,7 @@ static struct excmd {
 	{"g!", ec_glob},
 	{"g", ec_glob},
 	EO(mpt),
+	{"md", ec_modal},
 	{"m", ec_mark},
 	{"q!", ec_quit},
 	{"q", ec_quit},
diff --git a/vi.c b/vi.c
index 00929032..aedc522d 100644
--- a/vi.c
+++ b/vi.c
@@ -15,6 +15,7 @@
 #include <sys/wait.h>
 #include "vi.h"
 #include "conf.c"
+#include "modal.c"
 #include "ex.c"
 #include "lbuf.c"
 #include "led.c"
