#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0001-0010 0013-0014 0016-0037 0112 0121 0126 0132 0176-0177 0201-0223 0225-0341 0343-0377

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

SEP="$(printf '\001')"
# Command that handles readability line breaks
LB="0?"
# Disable errors
[ "$DBG" = "1" ] && DBG="0\?" || DBG=
# Ignore errors
[ "$QF" = "1" ] && QF= || QF="\\${SEP}vis 2\\${SEP}q!1"
# Enters vi at failing code line in this script
# Designed for state inspection mid execution
[ "$INTR" = "1" ] && INTR="\\${SEP}|sc|\\${SEP}vis 2:e $0:83reg %@/:%f> %@p:@Q:b0:|sc! \\\\\\${SEP}|:vis 3\\${SEP}q1" || INTR=

# Patch: conf.c
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}%f> \\\\(\\\\(.*pac.*\\\\)\\\\\\\\${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 293\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}.${SEP}s/t\\\\|s/t|ms|s/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 293\\${SEP}pr${INTR}${QF}}${SEP}vis 2${SEP}wq" $VI -e 'conf.c'

# Patch: ex.c
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}i int xms = 1;			/* mouse in normal mode */
${SEP}%;f> 	return NULL;
\\\\)

${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 1461\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a _EO(ms,
	xms = !*arg ? !xms : eo_val(arg);
	if (xms)
		write(1, \"\\\\x1b[?1000h\\\\x1b[?1006h\", 16); /* mouse on */
	else
		write(1, \"\\\\x1b[?1000l\\\\x1b[?1006l\", 16); /* mouse off */
	return NULL;
)

${SEP}.,\$;f> 	\\\\{\"g!\", ec_glob\\\\},
	\\\\{\"g\", ec_glob\\\\},
	EO\\\\(mpt\\\\),${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 1510\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 	EO(ms),
${SEP}vis 2${SEP}wq" $VI -e 'ex.c'

# Patch: led.c
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}%;f> 	return pos - xleft;
\\\\}

${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 98\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a /* map terminal column number to cursor horizontal position (inverse of led_pos) */
int led_col(char *s, int col)
{
	if (dir_context(s) < 0)
		return xleft + xcols - col - 1;
	return col + xleft;
}

${SEP}.,\$;f> 	\\\\}
	preserve\\\\(int, xleft, xleft = 0;\\\\)
	preserve\\\\(int, xtd, xtd = 2;\\\\)${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 666\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 	term_mouse_off();
${SEP}.,\$f> 	if \\\\(key == '\\\\\\\\n' && flg & 1\\\\) \\\\{${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 670\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}.i 	term_mouse_on();
${SEP}.,\$f> 	ins_state is;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 684\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}.a 	term_mouse_off();
${SEP}.,\$;f> 			free\\\\(postref\\\\);
			xrow = crow;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 697\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+1a 			term_mouse_on();
${SEP}vis 2${SEP}wq" $VI -e 'led.c'

# Patch: term.c
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}i int xmouse_col, xmouse_row;
void term_mouse_on(void)
{
	if (xms)
		write(1, \"\\\\x1b[?1000h\\\\x1b[?1006h\", 16);
}

void term_mouse_off(void)
{
	if (xms)
		write(1, \"\\\\x1b[?1000l\\\\x1b[?1006l\", 16);
}

${SEP}%;f> 	\\\\}
	xcols = xcols \\\\? xcols : 80;
	xrows = xrows \\\\? xrows : 25;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 33\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 	term_mouse_on();
${SEP}.,\$;f> \\\\{
	if \\\\(!term_sbuf\\\\)
		return;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 39\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 	term_mouse_off();
${SEP}.,\$;f> 	term_push\\\\(s, 1\\\\);
\\\\}

${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 149\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a /* Block-read one byte from stdin and append to ibuf.
 * Returns the byte value, or -1 on failure. */
static int mouse_pull(void)
{
	struct pollfd pfd = {STDIN_FILENO, POLLIN};
	unsigned char c;
	if (poll(&pfd, 1, -1) <= 0)
		return -1;
	if (read(STDIN_FILENO, &c, 1) <= 0)
		return -1;
	if (ibuf_cnt + 1 >= ibuf_sz) {
		ibuf_sz = ibuf_cnt + 128;
		ibuf = erealloc(ibuf, ibuf_sz);
	}
	ibuf[ibuf_cnt++] = c;
	return c;
}

/* Try to parse a mouse event from ibuf starting at ibuf_pos.
 * Reads bytes one-by-one with a blocking poll, appending each to ibuf.
 * Works whether or not the caller has already queued '[' and classifier
 * via pushback — absent bytes are pulled from stdin as needed.
 * On a valid complete mouse event, advances ibuf_pos past the sequence.
 * On invalid / non-mouse, leaves everything in ibuf and returns 0 so
 * term_read() consumes the bytes normally.
 * Returns: 1 = press, 2 = release, 3 = scroll up, 4 = scroll down, 0 = no match. */
int term_try_mouse(void)
{
	while (ibuf_pos >= ibuf_cnt)
		if (mouse_pull() < 0)
			return 0;
	if (ibuf[ibuf_pos] != '[')
		return 0;
	while (ibuf_pos + 1 >= ibuf_cnt)
		if (mouse_pull() < 0)
			return 0;
	/* X10 basic: ESC [ M b x y */
	if (ibuf[ibuf_pos + 1] == 'M') {
		while (ibuf_pos + 4 >= ibuf_cnt)
			if (mouse_pull() < 0)
				return 0;
		int btn = ibuf[ibuf_pos + 2] - 32;
		xmouse_col = ibuf[ibuf_pos + 3] - 32 - 1;
		xmouse_row = ibuf[ibuf_pos + 4] - 32 - 1;
		ibuf_pos += 5;
		return (btn & 3) == 3 ? 2 : 1; /* 3 = button release */
	}
	/* SGR 1006: ESC [ < btn ; col ; row M/m */
	if (ibuf[ibuf_pos + 1] == '<') {
		unsigned int i = ibuf_pos + 2;
		while (1) {
			while (i >= ibuf_cnt)
				if (mouse_pull() < 0)
					return 0;
			if (ibuf[i] == 'M' || ibuf[i] == 'm')
				break;
			if (!((ibuf[i] >= '0' && ibuf[i] <= '9') || ibuf[i] == ';'))
				return 0; /* bad byte — leave data in ibuf for term_read */
			i++;
		}
		unsigned int j = ibuf_pos + 2;
		int btn = 0, x = 0, y = 0;
		while (j < i && ibuf[j] >= '0' && ibuf[j] <= '9')
			btn = btn * 10 + (ibuf[j++] - '0');
		if (j < i && ibuf[j] == ';') {
			j++;
			while (j < i && ibuf[j] >= '0' && ibuf[j] <= '9')
				x = x * 10 + (ibuf[j++] - '0');
		}
		if (j < i && ibuf[j] == ';') {
			j++;
			while (j < i && ibuf[j] >= '0' && ibuf[j] <= '9')
				y = y * 10 + (ibuf[j++] - '0');
		}
		int release = (ibuf[i] == 'm');
		ibuf_pos = i + 1;
		if (btn == 64 || btn == 65)
			return btn == 64 ? 3 : 4; /* scroll up / down */
		xmouse_col = x - 1;
		xmouse_row = y - 1;
		return release ? 2 : 1;
	}
	return 0;
}

${SEP}vis 2${SEP}wq" $VI -e 'term.c'

# Patch: vi.c
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}%;f> 	vi_drawmsg_mpt\\\\(vi_msg\\\\)
\\\\}

${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 556\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a static void vi_scrollforward(int cnt);
static void vi_scrollbackward(int cnt);

${SEP}.,\$;f> 		return mv;
	\\\\}
	mv = term_read\\\\(TK_CTL\\\\('l'\\\\)\\\\);${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 572\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 	if (mv == 27 && xms) {
		int r = term_try_mouse();
		if (r == 1) {
			char *mln;
			int p;
			*row = xtop + xmouse_row;
			if (*row >= lbuf_len(xb))
				*row = lbuf_len(xb) - 1;
			if (*row < 0)
				*row = 0;
			mln = lbuf_get(xb, *row);
			p = mln ? led_col(mln, MAX(0, xmouse_col - vi_lncol)) : 0;
			*off = mln ? vi_col2off(xb, *row, MAX(0, p)) : 0;
			return mv;
		}
		if (r == 3 || r == 4) {
			if (r == 3)
				vi_scrollbackward(MAX(1, vi_scrolley));
			else
				vi_scrollforward(MAX(1, vi_scrolley));
			vi_mod |= 4;
			return -1;
		} else if (r == 2)	/* stray release from a prior click; restart */
			return -1;
	}
${SEP}vis 2${SEP}wq" $VI -e 'vi.c'

# Patch: vi.h
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}%f> int term_read\\\\(int winch\\\\);${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 321\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}.a int term_try_mouse(void);
void term_mouse_on(void);
void term_mouse_off(void);
${SEP}.,\$f> int led_pos\\\\(char \\\\*s, int pos\\\\);${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 392\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}.a int led_col(char *s, int col);
${SEP}.,\$f> /\\\\* ex options \\\\*/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 403\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}.i /* mouse state */
extern int xmouse_col, xmouse_row;
${SEP}.,\$f> /\\\\* global variables \\\\*/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL line 426\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}.i extern int xms;
${SEP}vis 2${SEP}wq" $VI -e 'vi.h'

exit 0
=== PATCH2VI DELTA ===
=== DELTA conf.c ===
GROUP 1
-((pac|pr|ai|ish|err|ic|grp|mpt|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
+((pac|pr|ai|ish|err|ic|grp|mpt|ms|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
pattern:
\(\(.*pac.*\)\\
edit_cmd_rel:
+0
s/t\|s/t|ms|s/
=== END DELTA ===
=== DELTA ex.c ===
GROUP 1
+int xms = 1;			/* mouse in normal mode */
strategy: abs
=== END DELTA ===
=== DELTA led.c ===
GROUP 3
+	term_mouse_on();
pattern:
	if \(key == '\\n' && flg & 1\) \{
edit_cmd_rel:
i 	term_mouse_on();
GROUP 4
+	term_mouse_off();
pattern:
	ins_state is;
edit_cmd_rel:
a 	term_mouse_off();
GROUP 5
+			term_mouse_on();
pattern:
			free\(postref\);
			xrow = crow;
edit_cmd_rel:
+1a 			term_mouse_on();
=== END DELTA ===
=== DELTA term.c ===
GROUP 1
+int xmouse_col, xmouse_row;
+void term_mouse_on(void)
+{
+	if (xms)
+		write(1, "\x1b[?1000h\x1b[?1006h", 16);
+}
+
+void term_mouse_off(void)
+{
+	if (xms)
+		write(1, "\x1b[?1000l\x1b[?1006l", 16);
+}
+
strategy: abs
=== END DELTA ===
=== DELTA vi.h ===
GROUP 1
+int term_try_mouse(void);
+void term_mouse_on(void);
+void term_mouse_off(void);
pattern:
int term_read\(int winch\);
edit_cmd_rel:
a int term_try_mouse(void);
void term_mouse_on(void);
void term_mouse_off(void);
GROUP 2
+int led_col(char *s, int col);
pattern:
int led_pos\(char \*s, int pos\);
edit_cmd_rel:
a int led_col(char *s, int col);
GROUP 3
+/* mouse state */
+extern int xmouse_col, xmouse_row;
pattern:
/\* ex options \*/
edit_cmd_rel:
i /* mouse state */
extern int xmouse_col, xmouse_row;
GROUP 4
+extern int xms;
pattern:
/\* global variables \*/
edit_cmd_rel:
i extern int xms;
=== END DELTA ===
=== PATCH2VI PATCH ===
diff --git a/conf.c b/conf.c
index be2bf4a2..8638298e 100644
--- a/conf.c
+++ b/conf.c
@@ -290,7 +290,7 @@ return|select|switch|type|var))\\>", A(GR1, BL1 | SYN_BD, YE1)},
 (?:'[a-z'`[\\]*])|([.%$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*[0-9]+[ \t]*)*(?:[ \t]*\\|.*?(?:(?<^\\\\)\\||$)[ \t]*)*)[ \t]*\
 (?:([,;]#?)[ \t]*((?:\\|.*?(?:(?<^\\\\)\\||$)[ \t]*)*(?:(?:<.*?(?:(?<^\\\\)<|$)|>.*?(?:(?<^\\\\)>|$))|\
 (?:'[a-z'`[\\]*])|([.$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*([0-9]+)[ \t]*)*(?:[ \t]*\\|.*?(?:(?<^\\\\)\\||$))*[ \t]*)*)\
-((pac|pr|ai|ish|err|ic|grp|mpt|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
+((pac|pr|ai|ish|err|ic|grp|mpt|ms|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
 |[@&!=dmj]|\\?\\?\?!?|\\?!|b[psx]?|p[uh]?|ac?|e[f!]?!?|f[-+><tdp]?|inc|i|sc!?|\
 (?:g!?|s)[ \t]?(.)?|q!?|reg?\\+?|rd?|w(?:q!|[q!])?|u[czbd]|x!?|ya!?|cm!?|cd?)?",
 		A(BL1 | SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1)},
diff --git a/ex.c b/ex.c
index 23903a3e..4874eaf3 100644
--- a/ex.c
+++ b/ex.c
@@ -1,3 +1,4 @@
+int xms = 1;			/* mouse in normal mode */
 int xleft;			/* the first visible column */
 int xvis;			/* startup flags */
 int xai = 1;			/* autoindent option */
@@ -1459,6 +1460,15 @@ _EO(left,
 	return NULL;
 )
 
+_EO(ms,
+	xms = !*arg ? !xms : eo_val(arg);
+	if (xms)
+		write(1, "\x1b[?1000h\x1b[?1006h", 16); /* mouse on */
+	else
+		write(1, "\x1b[?1000l\x1b[?1006l", 16); /* mouse off */
+	return NULL;
+)
+
 #undef EO
 #define EO(opt) {#opt, eo_##opt}
 
@@ -1508,6 +1518,7 @@ static struct excmd {
 	{"g!", ec_glob},
 	{"g", ec_glob},
 	EO(mpt),
+	EO(ms),
 	{"m", ec_mark},
 	{"q!", ec_quit},
 	{"q", ec_quit},
diff --git a/led.c b/led.c
index 6a5e065f..3224aa01 100644
--- a/led.c
+++ b/led.c
@@ -96,6 +96,14 @@ int led_pos(char *s, int pos)
 	return pos - xleft;
 }
 
+/* map terminal column number to cursor horizontal position (inverse of led_pos) */
+int led_col(char *s, int col)
+{
+	if (dir_context(s) < 0)
+		return xleft + xcols - col - 1;
+	return col + xleft;
+}
+
 #define print_ch1(out) sbuf_mem(out, chrs[o], l)
 #define print_ch2(out) sbuf_mem(out, *chrs[o] == ' ' ? "_" : chrs[o], l)
 
@@ -664,10 +672,12 @@ int led_prompt(sbuf *sb, char *insert, int *kmap, ins_state *is, int ps, int flg
 	}
 	preserve(int, xleft, xleft = 0;)
 	preserve(int, xtd, xtd = 2;)
+	term_mouse_off();
 	key = led_line(sb, ps, n, &post, 0, &postref, -1,
 			&off, kmap, is, 0, xrow, xtop, flg);
 	restore(xtd)
 	restore(xleft)
+	term_mouse_on();
 	if (key == '\n' && flg & 1) {
 		lbuf_dedup(tempbufs[0].lb, sb->s + n, sb->s_n - n)
 		temp_pos(0, -1, 0, 0);
@@ -682,6 +692,7 @@ int led_input(sbuf *sb, char *post, int postn, int row, int flg, int *pren)
 	int n, key, ps = 0, crow = xrow, ctop = xtop;
 	char *postref = NULL;
 	ins_state is;
+	term_mouse_off();
 	while (1) {
 		ins_init(is)
 		key = led_line(sb, ps, sb->s_n, &post, postn, &postref,
@@ -695,6 +706,7 @@ int led_input(sbuf *sb, char *post, int postn, int row, int flg, int *pren)
 				sb->s[*pren] = *post;
 			free(postref);
 			xrow = crow;
+			term_mouse_on();
 			return key;
 		}
 		sbuf_chr(sb, key)
diff --git a/term.c b/term.c
index 68990b78..69513f5b 100644
--- a/term.c
+++ b/term.c
@@ -1,3 +1,16 @@
+int xmouse_col, xmouse_row;
+void term_mouse_on(void)
+{
+	if (xms)
+		write(1, "\x1b[?1000h\x1b[?1006h", 16);
+}
+
+void term_mouse_off(void)
+{
+	if (xms)
+		write(1, "\x1b[?1000l\x1b[?1006l", 16);
+}
+
 static struct termios termios;
 sbuf *term_sbuf;
 int term_record;
@@ -31,12 +44,14 @@ void term_init(void)
 	}
 	xcols = xcols ? xcols : 80;
 	xrows = xrows ? xrows : 25;
+	term_mouse_on();
 }
 
 void term_done(void)
 {
 	if (!term_sbuf)
 		return;
+	term_mouse_off();
 	term_commit();
 	sbuf_free(term_sbuf)
 	tcsetattr(0, 0, &termios);
@@ -147,6 +162,91 @@ void term_back(int c)
 	term_push(s, 1);
 }
 
+/* Block-read one byte from stdin and append to ibuf.
+ * Returns the byte value, or -1 on failure. */
+static int mouse_pull(void)
+{
+	struct pollfd pfd = {STDIN_FILENO, POLLIN};
+	unsigned char c;
+	if (poll(&pfd, 1, -1) <= 0)
+		return -1;
+	if (read(STDIN_FILENO, &c, 1) <= 0)
+		return -1;
+	if (ibuf_cnt + 1 >= ibuf_sz) {
+		ibuf_sz = ibuf_cnt + 128;
+		ibuf = erealloc(ibuf, ibuf_sz);
+	}
+	ibuf[ibuf_cnt++] = c;
+	return c;
+}
+
+/* Try to parse a mouse event from ibuf starting at ibuf_pos.
+ * Reads bytes one-by-one with a blocking poll, appending each to ibuf.
+ * Works whether or not the caller has already queued '[' and classifier
+ * via pushback — absent bytes are pulled from stdin as needed.
+ * On a valid complete mouse event, advances ibuf_pos past the sequence.
+ * On invalid / non-mouse, leaves everything in ibuf and returns 0 so
+ * term_read() consumes the bytes normally.
+ * Returns: 1 = press, 2 = release, 3 = scroll up, 4 = scroll down, 0 = no match. */
+int term_try_mouse(void)
+{
+	while (ibuf_pos >= ibuf_cnt)
+		if (mouse_pull() < 0)
+			return 0;
+	if (ibuf[ibuf_pos] != '[')
+		return 0;
+	while (ibuf_pos + 1 >= ibuf_cnt)
+		if (mouse_pull() < 0)
+			return 0;
+	/* X10 basic: ESC [ M b x y */
+	if (ibuf[ibuf_pos + 1] == 'M') {
+		while (ibuf_pos + 4 >= ibuf_cnt)
+			if (mouse_pull() < 0)
+				return 0;
+		int btn = ibuf[ibuf_pos + 2] - 32;
+		xmouse_col = ibuf[ibuf_pos + 3] - 32 - 1;
+		xmouse_row = ibuf[ibuf_pos + 4] - 32 - 1;
+		ibuf_pos += 5;
+		return (btn & 3) == 3 ? 2 : 1; /* 3 = button release */
+	}
+	/* SGR 1006: ESC [ < btn ; col ; row M/m */
+	if (ibuf[ibuf_pos + 1] == '<') {
+		unsigned int i = ibuf_pos + 2;
+		while (1) {
+			while (i >= ibuf_cnt)
+				if (mouse_pull() < 0)
+					return 0;
+			if (ibuf[i] == 'M' || ibuf[i] == 'm')
+				break;
+			if (!((ibuf[i] >= '0' && ibuf[i] <= '9') || ibuf[i] == ';'))
+				return 0; /* bad byte — leave data in ibuf for term_read */
+			i++;
+		}
+		unsigned int j = ibuf_pos + 2;
+		int btn = 0, x = 0, y = 0;
+		while (j < i && ibuf[j] >= '0' && ibuf[j] <= '9')
+			btn = btn * 10 + (ibuf[j++] - '0');
+		if (j < i && ibuf[j] == ';') {
+			j++;
+			while (j < i && ibuf[j] >= '0' && ibuf[j] <= '9')
+				x = x * 10 + (ibuf[j++] - '0');
+		}
+		if (j < i && ibuf[j] == ';') {
+			j++;
+			while (j < i && ibuf[j] >= '0' && ibuf[j] <= '9')
+				y = y * 10 + (ibuf[j++] - '0');
+		}
+		int release = (ibuf[i] == 'm');
+		ibuf_pos = i + 1;
+		if (btn == 64 || btn == 65)
+			return btn == 64 ? 3 : 4; /* scroll up / down */
+		xmouse_col = x - 1;
+		xmouse_row = y - 1;
+		return release ? 2 : 1;
+	}
+	return 0;
+}
+
 int term_read(int winch)
 {
 	static struct pollfd ufd = {STDIN_FILENO, POLLIN};
diff --git a/vi.c b/vi.c
index 956e58e2..4dc591e4 100644
--- a/vi.c
+++ b/vi.c
@@ -554,6 +554,9 @@ static void vc_status(int type)
 	vi_drawmsg_mpt(vi_msg)
 }
 
+static void vi_scrollforward(int cnt);
+static void vi_scrollbackward(int cnt);
+
 /* read a motion */
 static int vi_motion(int vc, int *row, int *off)
 {
@@ -570,6 +573,31 @@ static int vi_motion(int vc, int *row, int *off)
 		return mv;
 	}
 	mv = term_read(TK_CTL('l'));
+	if (mv == 27 && xms) {
+		int r = term_try_mouse();
+		if (r == 1) {
+			char *mln;
+			int p;
+			*row = xtop + xmouse_row;
+			if (*row >= lbuf_len(xb))
+				*row = lbuf_len(xb) - 1;
+			if (*row < 0)
+				*row = 0;
+			mln = lbuf_get(xb, *row);
+			p = mln ? led_col(mln, MAX(0, xmouse_col - vi_lncol)) : 0;
+			*off = mln ? vi_col2off(xb, *row, MAX(0, p)) : 0;
+			return mv;
+		}
+		if (r == 3 || r == 4) {
+			if (r == 3)
+				vi_scrollbackward(MAX(1, vi_scrolley));
+			else
+				vi_scrollforward(MAX(1, vi_scrolley));
+			vi_mod |= 4;
+			return -1;
+		} else if (r == 2)	/* stray release from a prior click; restart */
+			return -1;
+	}
 	switch (mv) {
 	case ',':
 	case ';':
diff --git a/vi.h b/vi.h
index 59f3543e..29493525 100644
--- a/vi.h
+++ b/vi.h
@@ -319,6 +319,9 @@ void term_pos(int r, int c);
 void term_kill(void);
 void term_room(int n);
 int term_read(int winch);
+int term_try_mouse(void);
+void term_mouse_on(void);
+void term_mouse_off(void);
 void term_commit(void);
 char *term_att(int att);
 void term_push(char *s, unsigned int n);
@@ -390,6 +393,7 @@ void led_render(char *s0, int cbeg, int cend);
 #define led_crender(msg, row, col, beg, end) _led_render(msg, row, col, beg, end, term_kill();)
 char *led_read(int *kmap, int c);
 int led_pos(char *s, int pos);
+int led_col(char *s, int col);
 void led_done(void);
 
 /* ex.c: command mode */
@@ -401,6 +405,8 @@ struct buf {
 	long mtime;			/* modification time */
 	signed char td;			/* text direction */
 };
+/* mouse state */
+extern int xmouse_col, xmouse_row;
 /* ex options */
 extern int xleft;
 extern int xvis;
@@ -424,6 +430,7 @@ extern int xpr;
 extern int xlim;
 extern int xseq;
 extern int xerr;
+extern int xms;
 /* global variables */
 extern int xquit;
 extern int xrow, xoff, xtop;
