# nextvi patch2vi utility functions
#
# Source on demand:   . ./patch2vi.sh
# Then call:          patch2vi_wrapper -d input.patch [output.sh]
#                     gitdiff2vi [flags] [output.sh]
#                     edelta file [inplace]
#                     redelta input.sh
#                     extract_patches [file.sh]
#                     extract_compats [file.sh]
#                     reindex [file.sh | 1]
#                     migrate_deltas
#                     run_patches [1]
#                     conv [1]
#
# Requires the ./patch2vi binary in the current directory.

P2VI=./patch2vi
P2VITMP=/tmp/p2vi.tmp.$$

# --- helpers -----------------------------------------------------------------

# Is this one of our generated scripts?
p2v_ours() { head -2 "$1" | grep -q "Generated by patch2vi"; }

# Every generated script in the current directory, one per line.
p2v_scripts() {
	for s in *.sh
	do
		p2v_ours "$s" && printf '%s\n' "$s"
	done
	return 0
}

# Replace a script's embedded patch (everything past the marker) with $2.
# Its own temp file, since $2 is often $P2VITMP.
p2v_splice() {
	sed '/^=== PATCH2VI PATCH ===$/q' "$1" > "$P2VITMP.splice"
	cat "$2" >> "$P2VITMP.splice"
	cp "$P2VITMP.splice" "$1"
	rm -f "$P2VITMP.splice"
	chmod +x "$1"	# written by sed, not by patch2vi's own -o
}

# Untracked files are invisible to git diff, so they are staged as
# intent-to-add before a diff and dropped again after it.
p2v_newfiles() { git ls-files --others --exclude-standard; }
p2v_addnew() {
	[ -n "$1" ] && printf '%s\n' $1 | xargs git add -N
	return 0
}
p2v_dropnew() {
	if [ -n "$1" ]; then
		printf '%s\n' $1 | xargs git reset -q HEAD --
		printf '%s\n' $1 | xargs rm -f
	fi
	return 0
}

# The diff a just-run script produced, into $1, tree restored afterwards.
p2v_snapdiff() {
	new=$(p2v_newfiles)
	p2v_addnew "$new"
	git diff > "$1"
	git checkout . >/dev/null 2>&1
	p2v_dropnew "$new"
}

# --- conversion --------------------------------------------------------------

# Convert a .patch file to a nextvi shell script.
# Usage: patch2vi_wrapper <flag> input.patch [output.sh]
patch2vi_wrapper() {
	if [ -z "$1" ]; then
		echo "Usage: patch2vi_wrapper <flag> input.patch [output.sh]" >&2
		return 1
	fi
	if [ -n "$3" ]; then
		output="$3"
	else
		# Replace .patch extension with .sh, or append .sh if no .patch ext
		case "$2" in
			*.patch) output="${2%.patch}.sh" ;;
			*) output="${2}.sh" ;;
		esac
	fi
	$P2VI "$1" -o "$output" "$2"	# -o already makes it executable
	echo "Generated: $output"
}

# Regenerate $2 from the patch it already carries, with only that patch applied:
# real modifications are stashed first so the fuzzer validates against the
# original tree. New files (which have no pre-patch original) and $2 itself stay.
# Intent-to-add (git add -N) entries break both stash push and pop, so they are
# unstaged around the stash. -o rewrites $2 in place, atomically.
patch2vi_stashed() {
	ita=$(git diff --name-only --diff-filter=A -- ":!$2")
	[ -n "$ita" ] && git reset -q -- $ita
	stashed=$(git diff --name-only --diff-filter=MD -- ":!$2")
	[ -n "$stashed" ] && git stash push -q -- $stashed
	$P2VI "$1" -o "$2" "$2"
	[ -n "$stashed" ] && git stash pop -q
	[ -n "$ita" ] && git add -N -- $ita
	echo "Generated: $2" >&2
}

# Convert the current git diff to a nextvi shell script.
# Usage: gitdiff2vi [flags] [output.sh]
# If output.sh is omitted, writes to stdout.
gitdiff2vi() {
	if [ -z "$2" ]; then
		git diff | $P2VI $1
		return
	fi
	git diff -- ":!$2" > "$P2VITMP"
	case "$1" in
	-d*)	p2v_splice "$2" "$P2VITMP" ;;	# keep the stored deltas
	# start from the bare diff; -o keeps the mode of a file that already
	# exists, so the executable bit has to be set here
	*)	cp "$P2VITMP" "$2"; chmod +x "$2" ;;
	esac
	rm -f "$P2VITMP"
	patch2vi_stashed "$1" "$2"
}

# Edit embedded deltas in a nextvi shell script, in place.
# Usage: edelta file [inplace]
edelta() {
	if [ ! -x $P2VI ]; then
		git checkout patch2vi
		./build_patch2vi.sh build
		git checkout patches
	fi
	if [ "$2" ]; then
		$P2VI -i -o "$1" "$1"	# discard the stored deltas
	else
		$P2VI -d -o "$1" "$1"	# re-apply them
	fi
}

# Regenerate the embedded delta of a script from the current staged diff.
# Usage: redelta input.sh
redelta() {
	if [ -z "$1" ]; then
		echo "Usage: redelta input.sh" >&2
		return 1
	fi
	git add .
	git diff --staged > "$P2VITMP"
	git reset
	p2v_splice "$1" "$P2VITMP"
	rm -f "$P2VITMP"
	patch2vi_stashed -d "$1"
}

# --- bulk operations ---------------------------------------------------------

# Write each generated script's embedded patch out as <script>.patch. Nothing is
# run and no file but the .patch is touched, so this works on a dirty tree and
# on scripts that no longer apply. To have the .patch files reflect what the
# scripts actually do instead, reindex first: that refreshes every embedded
# patch from a real run, and this then writes those out.
# Usage: extract_patches [file.sh]
extract_patches() (
	set -e
	case "$1" in
	"")	list=$(p2v_scripts) ;;
	*)	p2v_ours "$1" || exit 1; list="$1" ;;
	esac
	for s in $list
	do
		out="${s%.sh}.patch"
		sed '1,/^=== PATCH2VI PATCH ===$/d' "$s" > "$out"
		if [ -s "$out" ]; then
			printf "%s\n" "EXTRACTED: $out"
		else	# no patch section, or an empty one
			rm -f "$out"
			printf "%s\n" "EMPTY: $s" >&2
		fi
	done
)

# Write every compat block a generated script carries out as a standalone
# .patch (its === COMPAT PATCH === diff, verbatim, exactly what its author
# handed to -co) and convert each one into its own runnable script. Both land
# in ./compat/ so the results stay out of p2v_scripts: they are generated
# scripts too, and reindex/run_patches must not pick them up as patches of
# their own. A block whose diff no longer applies to the tree still converts,
# with whatever fuzz patch2vi needs; a block with an empty diff is skipped.
# Naming: compat/<script>-<n>-<origin>.patch, numbered in storage order, since
# one script may carry several blocks from the same origin.
# Usage: extract_compats [file.sh]
extract_compats() (
	set -e
	case "$1" in
	"")	list=$(p2v_scripts) ;;
	*)	p2v_ours "$1" || exit 1; list="$1" ;;
	esac
	mkdir -p compat
	for s in $list
	do
		for p in $(awk -v base="compat/${s%.sh}" '
		/^=== PATCH2VI COMPAT /	{
			n++
			src = ""
			for (i = 1; i <= NF; i++)
				if (substr($i, 1, 4) == "src=")
					src = substr($i, 5)
			sub(/\.sh$/, "", src)
			out = base "-" n (src == "" ? "" : "-" src) ".patch"
			incb = 1
			inpat = 0
			next
		}
		incb && $0 == "=== COMPAT PATCH ===" {
			inpat = 1
			printf "" > out	# an empty diff still makes the file
			print out
			next
		}
		incb && inpat && $0 == "=== END ===" { inpat = 0; next }
		incb && $0 == "=== END COMPAT ===" { incb = 0; next }
		inpat			{ print > out }
		' "$s")
		do
			if [ ! -s "$p" ]; then
				rm -f "$p"
				printf "%s\n" "EMPTY: $p" >&2
				continue
			fi
			printf "%s\n" "EXTRACTED: $p"
			$P2VI -o "${p%.patch}.sh" "$p"
			printf "%s\n" "GENERATED: ${p%.patch}.sh"
		done
	done
)

# Re-run patch2vi-generated script(s) and refresh their embedded patch from the
# resulting diff. With a file arg, only that script; otherwise all of them
# (pass 1 to also rebuild via ./cbuild.sh after each).
# Usage: reindex [file.sh | 1]
reindex() (
	set -e
	rebuild=
	case "$1" in
	"")	list=$(p2v_scripts) ;;
	1)	list=$(p2v_scripts); rebuild=1 ;;
	*)	p2v_ours "$1" || exit 1; list="$1" ;;
	esac
	for s in $list
	do
		printf "%s\n" "SCRIPT: $s"
		"./$s"
		[ -n "$rebuild" ] && ./cbuild.sh build
		p2v_snapdiff "$P2VITMP"
		p2v_splice "$s" "$P2VITMP"
		rm -f "$P2VITMP"
		git add "$s"
		printf "\n"
	done
	rm -f tmp *.orig *.rej
)

# DESTRUCTIVE. Discards the stored delta in every patch2vi-generated script and
# regenerates it from scratch in the new format. Only for migrating to a format
# whose breaking changes cannot be reconciled otherwise. Rare.
# Usage: migrate_deltas
migrate_deltas() (
	set -e
	export P2VI_EX='q'
	for s in $(p2v_scripts)
	do
		edelta "$s" 1
	done
)

# Run every patch2vi-generated script, restoring the tree after each one. Pass 1
# to also rebuild via ./cbuild.sh after each, which is what turns this into a
# smoke test of the patch set. Writing the .patch files is not its job:
# "reindex && extract_patches" refreshes them from what the scripts actually do.
# Usage: run_patches [1]
run_patches() (
	set -e
	for s in $(p2v_scripts)
	do
		printf "%s\n" "RUNNING: $s"
		"./$s"
		[ "$1" = "1" ] && ./cbuild.sh build
		# extracted patches are not the run's leavings: keep them
		new=$(p2v_newfiles | grep -v '\.patch$' || true)
		git checkout . >/dev/null 2>&1
		p2v_dropnew "$new"
		printf "\n"
	done
)

# Run every patch2vi-generated script and commit each script's refreshed
# embedded delta. With arg 1, set P2VI_EX='q' and squash all commits back into
# a single staged change at the end.
# Usage: conv [1]
conv() (
	set -e
	n=0
	if [ -n "$1" ]; then
		export P2VI_EX='q'
	fi
	for s in $(p2v_scripts)
	do
		"./$s"
		new=$(p2v_newfiles)
		p2v_addnew "$new"
		gitdiff2vi -d "$s"
		git add "$s"
		if ! git diff --cached --quiet; then
			git commit -m "$s: conv"
			n=$((n+1))
		fi
		git reset --hard
		if [ -n "$new" ]; then
			printf '%s\n' $new | xargs rm -f
		fi
	done
	if [ -n "$1" ] && [ $n -gt 0 ]; then
		git reset HEAD~$n
		git add .
	fi
)
