#!/bin/sh

p2v_usage() {
	cat <<'EOF'
Nextvi patch2vi utility functions

Source on demand:   . ./patch2vi.sh
Then call:          patch2vi_wrapper -d input.patch [output.sh]
                    gitdiff2vi [flags] [output.sh]
                    edelta file [inplace]
                    regen input.sh
                    rebuild target.sh
                    extract_patches [file.sh]
                    extract_compats [file.sh]
                    view_patch file.sh
                    recompat target.sh [origin.sh]
                    reindex [file.sh | 1]
                    discard_deltas [file.sh]
                    discard_compats [file.sh]
                    run_patches [1]
                    regen_all [1]

Requires the ./patch2vi binary in the current directory.
EOF
}

# $0 is the script's own path only when it was run, never when it was sourced.
case "$0" in
*patch2vi.sh)	p2v_usage >&2; exit 1 ;;
esac

P2VI=./patch2vi
P2VITMP=/tmp/p2vi.tmp.$$

# --- helpers -----------------------------------------------------------------

# Diagnostics, on stderr, only with P2V_DEBUG set in the environment.
p2v_dbg() {
	[ -n "$P2V_DEBUG" ] && printf 'DBG: %s\n' "$*" >&2
	return 0
}

# Is this one of our generated scripts?
p2v_ours() { head -2 "$1" | grep -q "Generated by patch2vi"; }

# Every generated script in the current directory, one per line.
p2v_scripts() {
	for s in *.sh
	do
		p2v_ours "$s" && printf '%s\n' "$s"
	done
	return 0
}

# Replace a script's embedded patch (everything past the marker) with $2.
# Its own temp file, since $2 is often $P2VITMP.
p2v_splice() {
	sed '/^=== PATCH2VI PATCH ===$/q' "$1" > "$P2VITMP.splice"
	cat "$2" >> "$P2VITMP.splice"
	cp "$P2VITMP.splice" "$1"
	rm -f "$P2VITMP.splice"
	chmod +x "$1"	# written by sed, not by patch2vi's own -o
}

# Untracked files are invisible to git diff, so they are staged as
# intent-to-add before a diff and dropped again after it.
p2v_newfiles() { git ls-files --others --exclude-standard; }
p2v_addnew() {
	[ -n "$1" ] && printf '%s\n' $1 | xargs git add -N
	return 0
}
p2v_dropnew() {
	if [ -n "$1" ]; then
		printf '%s\n' $1 | xargs git reset -q HEAD --
		printf '%s\n' $1 | xargs rm -f
	fi
	return 0
}

# The sources a patch may touch: everything but our own scripts and the files
# extracted from them. Word-split on purpose, it is a git pathspec list.
P2V_SRC=":!*.sh :!*.patch :!compat"

# patch2vi opens /dev/tty for its editor, which a pipeline or a CI job does not
# have; script(1) then supplies one. Paths with spaces do not survive this.
p2v_tty() {
	if { : >/dev/tty; } 2>/dev/null; then
		"$@"
	else
		script -qec "$*" /dev/null
	fi
}

# Undo a script run: sources back to HEAD, leavings dropped. Scoped to the
# sources, so a script this very run rewrote is not reverted along with them.
p2v_restore() {
	new=$(p2v_newfiles | grep -v '^compat/' || true)
	git checkout -- $P2V_SRC >/dev/null 2>&1
	p2v_dropnew "$new"
}

# Write the working tree's sources to a tree object, the index left alone.
# Snapshots taken this way diff with git diff-tree, so files a run adds or
# removes come out right, unlike a diff of two copied directories.
p2v_snaptree() {
	rm -f "$P2VITMP.idx"
	GIT_INDEX_FILE="$P2VITMP.idx" git add -A -- $P2V_SRC
	GIT_INDEX_FILE="$P2VITMP.idx" git write-tree
	rm -f "$P2VITMP.idx"
}

# The src= of every compat block $1 carries, one per line, in storage order.
p2v_compatsrc() {
	sed -n 's/^=== PATCH2VI COMPAT .*src=\([^ ]*\).*/\1/p' "$1"
}

# $1 without the stored compat blocks whose src= is $2, on stdout; with no $2,
# without any of them. A block is only the record of a resolution: the ex
# commands that carry it out sit in the emitted body, so a stripped script has
# to be re-emitted ($P2VI -od) before it runs as one that never had them.
p2v_stripcompat() {
	awk -v src="$2" '
	/^=== PATCH2VI COMPAT /	{
		if (src == "")
			skip = 1
		else for (i = 1; i <= NF; i++)
			if ($i == "src=" src)
				skip = 1
	}
	!skip			{ print }
	/^=== END COMPAT ===$/	{ skip = 0 }
	' "$1"
}

# Split the compat blocks of $1 into directory $2: block N's verbatim
# === COMPAT PATCH === diff lands in $2/N.patch, and one "N <origin>" line per
# block goes to stdout, in storage order. A block with an empty diff still gets
# its (empty) file, so the numbering never drifts from the stored order.
p2v_splitcompat() {
	awk -v dir="$2" '
	/^=== PATCH2VI COMPAT /	{
		n++
		src = ""
		for (i = 1; i <= NF; i++)
			if (substr($i, 1, 4) == "src=")
				src = substr($i, 5)
		out = dir "/" n ".patch"
		printf "" > out
		print n " " src
		incb = 1
		inpat = 0
		next
	}
	incb && $0 == "=== COMPAT PATCH ===" { inpat = 1; next }
	incb && inpat && $0 == "=== END ===" { inpat = 0; next }
	incb && $0 == "=== END COMPAT ===" { incb = 0; next }
	inpat			{ print > out }
	' "$1"
}

# The diff a just-run script produced, into $1, tree restored afterwards.
p2v_snapdiff() {
	new=$(p2v_newfiles)
	p2v_addnew "$new"
	git diff > "$1"
	git checkout . >/dev/null 2>&1
	p2v_dropnew "$new"
}

# --- conversion --------------------------------------------------------------

# Convert a .patch file to a nextvi shell script.
# Usage: patch2vi_wrapper <flag> input.patch [output.sh]
patch2vi_wrapper() {
	if [ -z "$1" ]; then
		echo "Usage: patch2vi_wrapper <flag> input.patch [output.sh]" >&2
		return 1
	fi
	if [ -n "$3" ]; then
		output="$3"
	else
		# Replace .patch extension with .sh, or append .sh if no .patch ext
		case "$2" in
			*.patch) output="${2%.patch}.sh" ;;
			*) output="${2}.sh" ;;
		esac
	fi
	$P2VI "$1" -o "$output" "$2"	# -o already makes it executable
	echo "Generated: $output"
}

# Run "$@" (from $2 on) with the tree back at HEAD, so patch2vi validates its
# fuzz against the original sources rather than against an already patched tree.
# New files (which have no pre-patch original) and $1 itself stay. Intent-to-add
# (git add -N) entries break both stash push and pop, so they are unstaged
# around the stash. The tree is restored even when the command fails, whose
# status is what this returns.
p2v_stashed_run() {
	keep="$1"
	shift
	ita=$(git diff --name-only --diff-filter=A -- ":!$keep")
	[ -n "$ita" ] && git reset -q -- $ita
	stashed=$(git diff --name-only --diff-filter=MD -- ":!$keep")
	[ -n "$stashed" ] && git stash push -q -- $stashed
	"$@"
	p2v_st=$?
	[ -n "$stashed" ] && git stash pop -q
	[ -n "$ita" ] && git add -N -- $ita
	return $p2v_st
}

# Regenerate $2 from the patch it already carries, with only that patch applied.
# -o rewrites $2 in place, atomically.
patch2vi_stashed() {
	p2v_stashed_run "$2" $P2VI "$1" -o "$2" "$2"
	echo "Generated: $2" >&2
}

# Convert the current git diff to a nextvi shell script.
# Usage: gitdiff2vi [flags] [output.sh]
# If output.sh is omitted, writes to stdout.
gitdiff2vi() {
	if [ -z "$2" ]; then
		git diff | $P2VI $1
		return
	fi
	git diff -- ":!$2" > "$P2VITMP"
	case "$1" in
	-d*)	p2v_splice "$2" "$P2VITMP" ;;	# keep the stored deltas
	# start from the bare diff; -o keeps the mode of a file that already
	# exists, so the executable bit has to be set here
	*)	cp "$P2VITMP" "$2"; chmod +x "$2" ;;
	esac
	rm -f "$P2VITMP"
	patch2vi_stashed "$1" "$2"
}

# Edit embedded deltas in a nextvi shell script, in place.
# Usage: edelta file [inplace]
edelta() {
	if [ ! -x $P2VI ]; then
		git checkout patch2vi
		./build_patch2vi.sh build
		git checkout patches
	fi
	if [ "$2" ]; then
		$P2VI -i -o "$1" "$1"	# discard the stored deltas
	else
		$P2VI -od "$1"		# re-apply them, in place
	fi
}

# Regenerate a script from the whole working tree, in place. Everything is
# staged first, so files the tree gained are in the diff too: that is what this
# has over gitdiff2vi, whose plain git diff cannot see an untracked file.
# Usage: regen input.sh
regen() {
	if [ -z "$1" ]; then
		echo "Usage: regen input.sh" >&2
		return 1
	fi
	git add .
	# the script's own diff is not part of the patch it carries
	git diff --staged -- ":!$1" > "$P2VITMP"
	git reset -q
	p2v_splice "$1" "$P2VITMP"
	rm -f "$P2VITMP"
	patch2vi_stashed -d "$1"
}

# The -co pass of rebuild: every saved block back onto the script, in storage
# order, one -co call each (a block is one diff, and one call stores one block,
# so the count comes out as it went in). Run with the tree at HEAD.
#
# Deriving a block replays the origin, and a replay writes the sections it edits
# out, so the tree does not come back clean on its own. The sources go back to
# HEAD afterwards and the files the pass brought into being are dropped - only
# those, the ones already there are the caller's and are left alone. This has to
# happen before the caller's stash comes home, or it lands on top of the
# replay's leavings.
# Usage: p2v_reapply workdir target.sh
p2v_reapply() {
	p2v_newfiles | sort > "$1/pre"
	p2v_st2=0
	if [ -n "$P2V_DEBUG" ]; then
		p2v_dbg "reapply: workdir=[$1] target=[$2]"
		p2v_dbg "reapply: IFS bytes: $(printf '%s' "$IFS" | od -An -c | tr -s ' ')"
		p2v_dbg "reapply: manifest $1/blocks:"
		od -c "$1/blocks" >&2
	fi
	while read -r n origin
	do
		p2v_dbg "read: n=[$n] origin=[$origin]"
		if [ -z "$origin" ]; then
			printf "%s\n" "NO ORIGIN: block $n of $2, dropped" >&2
			continue
		fi
		if [ ! -s "$1/$n.patch" ]; then
			printf "%s\n" "EMPTY: block $n of $2 from $origin, dropped" >&2
			continue
		fi
		printf "%s\n" "COMPAT: $2 <- $origin (block $n)" >&2
		if ! p2v_tty $P2VI -oco "$origin" "$2" "$1/$n.patch"; then
			p2v_st2=1
			break
		fi
	done < "$1/blocks"
	git checkout -- $P2V_SRC >/dev/null 2>&1
	p2v_newfiles | sort > "$1/post"
	left=$(comm -13 "$1/pre" "$1/post")
	[ -n "$left" ] && printf '%s\n' $left | xargs rm -f
	return $p2v_st2
}

# Regenerate a script whole: its base patch and its compat blocks both.
#
# regen refreshes the base patch and re-emits the body, but the compat blocks
# come back out of storage exactly as they went in, gates and all, and those
# gates were derived against the base as it read then. Once the base moves under
# them they probe for text that is no longer there. So the blocks are taken off
# first, the base is regenerated without them, and each block's stored
# === COMPAT PATCH === diff is handed back to -co, which derives fresh gates
# against the base that now exists. The stored diff being verbatim is what makes
# this possible: it comes back out as the patch its author handed in.
#
# Only the diffs survive, not the blocks' own delta customizations, as with
# recompat. A stored diff whose pre-image the new base no longer has is a hard
# error from -co, and then the script is put back the way it was: resolve that
# collision by hand and hand the result to -co instead.
# Usage: rebuild target.sh
rebuild() (
	if [ -z "$1" ]; then
		echo "Usage: rebuild target.sh" >&2
		return 1
	fi
	target="$1"
	p2v_ours "$target" || return 1
	export P2VI_EX="${P2VI_EX:-led:q}"	# -d and -co imply the editor; led keeps it from drawing
	work="$P2VITMP.rebuild"
	rm -rf "$work"
	mkdir -p "$work"
	cp "$target" "$work/orig.sh"
	p2v_splitcompat "$target" "$work" > "$work/blocks"
	p2v_dbg "rebuild: shell=[$0] work=[$work] P2VITMP=[$P2VITMP]"
	p2v_dbg "rebuild: headers in target: $(grep -c '^=== PATCH2VI COMPAT ' "$target")"
	p2v_dbg "rebuild: manifest lines: $(wc -l < "$work/blocks")"
	p2v_stripcompat "$target" > "$work/bare.sh"
	cp "$work/bare.sh" "$target"
	chmod +x "$target"		# written by awk, not by -o
	regen "$target"			# base only: the blocks are off
	p2v_dbg "rebuild: after regen, target md5: $(md5sum "$target")"
	p2v_stashed_run "$target" p2v_reapply "$work" "$target"
	st=$?
	p2v_dbg "rebuild: reapply status=$st"
	if [ "$st" -ne 0 ]; then
		cp "$work/orig.sh" "$target"
		chmod +x "$target"
		rm -rf "$work"
		printf "%s\n" "FAILED: $target left as it was" >&2
		return 1
	fi
	rm -rf "$work"
	printf "%s\n" "REBUILT: $target"
)

# --- bulk operations ---------------------------------------------------------

# Write each generated script's embedded patch out as <script>.patch. Nothing is
# run and no file but the .patch is touched, so this works on a dirty tree and
# on scripts that no longer apply. To have the .patch files reflect what the
# scripts actually do instead, reindex first: that refreshes every embedded
# patch from a real run, and this then writes those out.
# Usage: extract_patches [file.sh]
extract_patches() (
	set -e
	case "$1" in
	"")	list=$(p2v_scripts) ;;
	*)	p2v_ours "$1" || exit 1; list="$1" ;;
	esac
	for s in $list
	do
		out="${s%.sh}.patch"
		sed '1,/^=== PATCH2VI PATCH ===$/d' "$s" > "$out"
		if [ -s "$out" ]; then
			printf "%s\n" "EXTRACTED: $out"
		else	# no patch section, or an empty one
			rm -f "$out"
			printf "%s\n" "EMPTY: $s" >&2
		fi
	done
)

# Write every compat block a generated script carries out as a standalone
# .patch (its === COMPAT PATCH === diff, verbatim, exactly what its author
# handed to -co) and convert each one into its own runnable script. Both land
# in ./compat/ so the results stay out of p2v_scripts: they are generated
# scripts too, and reindex/run_patches must not pick them up as patches of
# their own. A block whose diff no longer applies to the tree still converts,
# with whatever fuzz patch2vi needs; a block with an empty diff is skipped.
# Naming: compat/<script>-<n>-<origin>.patch, numbered in storage order, since
# one script may carry several blocks from the same origin.
# Usage: extract_compats [file.sh]
extract_compats() (
	set -e
	case "$1" in
	"")	list=$(p2v_scripts) ;;
	*)	p2v_ours "$1" || exit 1; list="$1" ;;
	esac
	mkdir -p compat
	for s in $list
	do
		for p in $(awk -v base="compat/${s%.sh}" '
		/^=== PATCH2VI COMPAT /	{
			n++
			src = ""
			for (i = 1; i <= NF; i++)
				if (substr($i, 1, 4) == "src=")
					src = substr($i, 5)
			sub(/\.sh$/, "", src)
			out = base "-" n (src == "" ? "" : "-" src) ".patch"
			incb = 1
			inpat = 0
			next
		}
		incb && $0 == "=== COMPAT PATCH ===" {
			inpat = 1
			printf "" > out	# an empty diff still makes the file
			print out
			next
		}
		incb && inpat && $0 == "=== END ===" { inpat = 0; next }
		incb && $0 == "=== END COMPAT ===" { incb = 0; next }
		inpat			{ print > out }
		' "$s")
		do
			if [ ! -s "$p" ]; then
				rm -f "$p"
				printf "%s\n" "EMPTY: $p" >&2
				continue
			fi
			printf "%s\n" "EXTRACTED: $p"
			$P2VI -r -o "${p%.patch}.sh" "$p"
			printf "%s\n" "GENERATED: ${p%.patch}.sh"
		done
	done
)

# Read-only companion to extract_patches/extract_compats: everything a single
# generated script carries - its embedded patch first, then every compat block's
# diff, in storage order - concatenated into one .patch and opened in an editor.
# Nothing in the tree is touched and no runnable script is produced, so this
# works on a dirty tree and on scripts that no longer apply.
#
# The file lands in /tmp, or in the current directory when /tmp is not writable.
# Sections are separated by a comment banner, which diff readers and syntax
# highlighters skip over, so the result still reads as a patch.
# Usage: view_patch file.sh
view_patch() (
	set -e
	if [ -z "$1" ]; then
		echo "Usage: view_patch file.sh" >&2
		return 1
	fi
	p2v_ours "$1"
	base=${1##*/}
	base=${base%.sh}
	out="/tmp/$base.patch"
	if ! { : > "$out"; } 2>/dev/null; then
		out="$base.patch"
		: > "$out"
	fi
	printf "%s\n" "# === $1: embedded patch ===" >> "$out"
	sed '1,/^=== PATCH2VI PATCH ===$/d' "$1" >> "$out"
	awk -v out="$out" '
	/^=== PATCH2VI COMPAT /	{
		n++
		src = ""
		for (i = 1; i <= NF; i++)
			if (substr($i, 1, 4) == "src=")
				src = substr($i, 5)
		incb = 1
		inpat = 0
		next
	}
	incb && $0 == "=== COMPAT PATCH ===" {
		inpat = 1
		print "# === compat " n (src == "" ? "" : " from " src) " ===" >> out
		next
	}
	incb && inpat && $0 == "=== END ===" { inpat = 0; next }
	incb && $0 == "=== END COMPAT ===" { incb = 0; next }
	inpat			{ print >> out }
	' "$1"
	printf "%s\n" "VIEWING: $out" >&2
	if [ -x ./vi ]; then
		p2v_tty "${EDITOR:-./vi}" "$out"
	else
		p2v_tty "${EDITOR:-vi}" "$out"
	fi
)

# Collapse the compat blocks a script carries from one origin into a single one.
#
# A compat fix grows by addition: run origin.sh and target.sh, edit the sources
# until the collision is resolved again, and hand that edit to -co, which stacks
# another block on the target. Blocks stay stacked, so the stack is the history
# of the fix, and this turns it back into the one block it is meant to be.
#
# Nothing is read out of the old blocks, only the two trees the scripts really
# produce: A, the collision with every block from origin.sh stripped out, and B,
# the same run with all of them in. Their diff is the whole resolution as it
# stands today, and -co re-derives its gates from that, which is what makes a
# collapse survive a patch2vi whose patterns now collide differently.
#
# The tree is restored, target.sh is rewritten in place: commit it afterwards.
# With no origin, every origin the target has more than one block from.
# Usage: recompat target.sh [origin.sh]
recompat() (
	set -e
	if [ -z "$1" ]; then
		echo "Usage: recompat target.sh [origin.sh]" >&2
		return 1
	fi
	target="$1"
	p2v_ours "$target"
	if [ -n "$2" ]; then
		list="$2"
	else	# an origin with a single block is already collapsed
		list=$(p2v_compatsrc "$target" | sort | uniq -d)
		if [ -z "$list" ]; then
			printf "%s\n" "NOTHING TO COLLAPSE: $target" >&2
			return 0
		fi
	fi
	export P2VI_EX="${P2VI_EX:-led:q}"	# -d and -co imply the editor; led keeps it from drawing
	work="$P2VITMP.recompat"
	for origin in $list
	do
		p2v_ours "$origin"
		n=$(p2v_compatsrc "$target" | grep -c "^$origin$") || n=0
		if [ "$n" -eq 0 ]; then
			printf "%s\n" "NO BLOCKS: $target from $origin" >&2
			continue
		fi
		rm -rf "$work"
		mkdir -p "$work"
		p2v_restore
		# A: the collision on its own
		p2v_stripcompat "$target" "$origin" > "$work/bare.sh"
		chmod +x "$work/bare.sh"
		p2v_tty $P2VI -od "$work/bare.sh"
		"./$origin"
		"$work/bare.sh"
		a=$(p2v_snaptree)
		p2v_restore
		# B: the collision with every block from this origin resolving it
		"./$origin"
		"./$target"
		b=$(p2v_snaptree)
		git diff-tree -p "$a" "$b" > "$work/compat.patch"
		p2v_restore
		if [ ! -s "$work/compat.patch" ]; then
			printf "%s\n" "EMPTY: $origin resolves nothing, $target kept" >&2
			continue
		fi
		p2v_stripcompat "$target" "$origin" > "$work/new.sh"
		cp "$work/new.sh" "$target"
		chmod +x "$target"		# written by awk, not by -o
		p2v_tty $P2VI -od "$target"	# re-emit without the old blocks
		p2v_tty $P2VI -oco "$origin" "$target" "$work/compat.patch"
		p2v_restore
		printf "%s\n" "COLLAPSED: $target <- $origin, $n blocks into 1"
	done
	rm -rf "$work"
)

# Re-run patch2vi-generated script(s) and refresh their embedded patch from the
# resulting diff. With a file arg, only that script; otherwise all of them
# (pass 1 to also build via ./cbuild.sh after each).
# Usage: reindex [file.sh | 1]
reindex() (
	set -e
	dobuild=
	case "$1" in
	"")	list=$(p2v_scripts) ;;
	1)	list=$(p2v_scripts); dobuild=1 ;;
	*)	p2v_ours "$1" || exit 1; list="$1" ;;
	esac
	for s in $list
	do
		printf "%s\n" "SCRIPT: $s"
		"./$s"
		[ -n "$dobuild" ] && ./cbuild.sh build
		p2v_snapdiff "$P2VITMP"
		p2v_splice "$s" "$P2VITMP"
		rm -f "$P2VITMP"
		git add "$s"
		printf "\n"
	done
	rm -f tmp *.orig *.rej
)

# DESTRUCTIVE. Discards the stored delta and regenerates the script from scratch
# in the new format. With a file arg, only that script; otherwise all of them.
# Only for migrating to a format whose breaking changes cannot be reconciled
# otherwise. Rare.
# Usage: discard_deltas [file.sh]
discard_deltas() (
	set -e
	case "$1" in
	"")	list=$(p2v_scripts) ;;
	*)	p2v_ours "$1" || exit 1; list="$1" ;;
	esac
	export P2VI_EX="${P2VI_EX:-led:q}"	# -i implies the editor; do not stop in it, or draw it
	for s in $list
	do
		edelta "$s" 1
	done
)

# DESTRUCTIVE. Drops every compat block a generated script carries: the stored
# === PATCH2VI COMPAT === regions go, then the script is regenerated from what
# is left, which is what takes the blocks' gates and bodies out of it. Stored
# deltas are kept, so only the compat side is lost - extract_compats first if
# the diffs are worth keeping. With a file arg, only that script; otherwise all
# of them.
# Usage: discard_compats [file.sh]
discard_compats() (
	set -e
	case "$1" in
	"")	list=$(p2v_scripts) ;;
	*)	p2v_ours "$1" || exit 1; list="$1" ;;
	esac
	export P2VI_EX="${P2VI_EX:-led:q}"	# -d implies the editor; do not stop in it, or draw it
	for s in $list
	do
		grep -q '^=== PATCH2VI COMPAT ' "$s" || continue
		awk '
		/^=== PATCH2VI COMPAT /	{ skip = 1 }
		!skip			{ print }
		/^=== END COMPAT ===$/	{ skip = 0 }
		' "$s" > "$P2VITMP.compat"
		cp "$P2VITMP.compat" "$s"
		rm -f "$P2VITMP.compat"
		chmod +x "$s"	# written by awk, not by patch2vi's own -o
		$P2VI -od "$s"
		printf "%s\n" "DISCARDED: $s"
	done
)

# Run every patch2vi-generated script, restoring the tree after each one. Pass 1
# to also rebuild via ./cbuild.sh after each, which is what turns this into a
# smoke test of the patch set. Writing the .patch files is not its job:
# "reindex && extract_patches" refreshes them from what the scripts actually do.
# Usage: run_patches [1]
run_patches() (
	set -e
	for s in $(p2v_scripts)
	do
		printf "%s\n" "RUNNING: $s"
		"./$s"
		[ "$1" = "1" ] && ./cbuild.sh build
		# extracted patches are not the run's leavings: keep them
		new=$(p2v_newfiles | grep -v '\.patch$' || true)
		git checkout . >/dev/null 2>&1
		p2v_dropnew "$new"
		printf "\n"
	done
)

# regen over every generated script, each one committed. A deeper reindex:
# reindex only splices a fresh diff into the patch section and leaves the body
# alone, this re-emits the body from that diff as well. Compat blocks ride along
# as stored, they are not re-derived - that is recompat's job.
# With arg 1, set P2VI_EX='q' and squash all commits back into a single staged
# change at the end.
# Usage: regen_all [1]
regen_all() (
	set -e
	n=0
	if [ -n "$1" ]; then
		export P2VI_EX='q'
	fi
	for s in $(p2v_scripts)
	do
		"./$s"
		new=$(p2v_newfiles)
		p2v_addnew "$new"
		gitdiff2vi -d "$s"
		git add "$s"
		if ! git diff --cached --quiet; then
			git commit -m "$s: regen"
			n=$((n+1))
		fi
		git reset --hard
		if [ -n "$new" ]; then
			printf '%s\n' $new | xargs rm -f
		fi
	done
	if [ -n "$1" ] && [ $n -gt 0 ]; then
		git reset HEAD~$n
		git add .
	fi
)
