#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0001-0010 0013-0014 0016-0037 0102-0104 0107-0110 0112 0115 0120-0121 0123 0126 0131-0132 0136 0172 0176-0377

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

SEP="$(printf '\001')"
# Comment to continue despite errors (errors are still printed)
QF="\\${SEP}vis 2\\${SEP}q!1"
# Command handling readability line breaks
LB="0?"
# Uncomment to enter interactive vi on patch failure
#INTR="\\${SEP}|sc|\\${SEP}vis 2:e $0:%f>:@Q:q!1"
# Uncomment to skip errors (0? = silent nop)
#DBG="0\?"

# Patch: ex.c
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}i char readonly = 0;		/* commandline readonly option */
${SEP}%f> 	bufs\\\\[i\\\\]\\\\.mtime = -1;${SEP}??!${DBG:-re p FAIL line 118\\${SEP}p FAIL line 118${INTR}${QF}}${SEP}${LB}
${SEP}.a 	bufs[i].readonly = readonly;
${SEP}.,\$;f> 		bufs_switch\\\\(bufs_open\\\\(arg\\\\+cd, len\\\\)\\\\);
		cd = 3; /\\\\* XXX: quick hack to indicate new lbuf \\\\*/
	\\\\}${SEP}??!${DBG:-re p FAIL line 372\\${SEP}p FAIL line 372${INTR}${QF}}${SEP}${LB}
${SEP}+2a 	if (access(arg, F_OK) == 0 && access(arg, W_OK) == -1)
		ex_buf->readonly = 1;
${SEP}.,\$;f> 		free\\\\(ibuf\\\\.s\\\\);
	\\\\} else \\\\{
		if \\\\(!strchr\\\\(cmd, '!'\\\\)\\\\) \\\\{${SEP}??!${DBG:-re p FAIL line 691\\${SEP}p FAIL line 691${INTR}${QF}}${SEP}${LB}
${SEP}+2a 			if (ex_buf->readonly)
				return \"write failed: readonly option is set\";
${SEP}.,\$;f> 	return xkwdrs \\\\? NULL : xserr;
\\\\}

${SEP}??!${DBG:-re p FAIL line 1431\\${SEP}p FAIL line 1431${INTR}${QF}}${SEP}${LB}
${SEP}+2a static void *ec_readonly(char *loc, char *cmd, char *arg)
{
	ex_buf->readonly = !ex_buf->readonly;
	return NULL;
}

${SEP}.,\$f> 	\\\\{\"rd\", ec_undoredo\\\\},${SEP}??!${DBG:-re p FAIL line 1517\\${SEP}p FAIL line 1517${INTR}${QF}}${SEP}${LB}
${SEP}.a 	{\"ro\", ec_readonly},
${SEP}vis 2${SEP}wq" $VI -e 'ex.c'

# Patch: vi.c
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}%;f> 			else if \\\\(argv\\\\[i\\\\]\\\\[j\\\\] == 'a'\\\\)
				xvis \\\\|= 8;${SEP}??!${DBG:-re p FAIL line 1853\\${SEP}p FAIL line 1853${INTR}${QF}}${SEP}${LB}
${SEP}+1a 			else if (argv[i][j] == 'R')
				readonly = 1;
${SEP}.,\$f> 				fprintf\\\\(stderr, \"Unknown option: -%c\\\\\\\\n\", argv\\\\[i\\\\]\\\\[j\\\\]\\\\);${SEP}??!${DBG:-re p FAIL line 1858\\${SEP}p FAIL line 1858${INTR}${QF}}${SEP}${LB}
${SEP}+1${SEP}s/(\\\\[-a.*m)/\\\\1R/${SEP}??!${DBG:-re p FAIL line 1858\\${SEP}p FAIL line 1858${INTR}${QF}}${SEP}vis 2${SEP}wq" $VI -e 'vi.c'

# Patch: vi.h
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}%f> 	signed char td;			/\\\\* text direction \\\\*/${SEP}??!${DBG:-re p FAIL line 402\\${SEP}p FAIL line 402${INTR}${QF}}${SEP}${LB}
${SEP}.a 	char readonly;			/* read only */
${SEP}\$a extern char readonly;
${SEP}vis 2${SEP}wq" $VI -e 'vi.h'

exit 0
=== PATCH2VI DELTA ===
=== DELTA ex.c ===
GROUP 1
+char readonly = 0;		/* commandline readonly option */
strategy: abs
GROUP 2
+	bufs[i].readonly = readonly;
pattern:
	bufs\[i\]\.mtime = -1;
edit_cmd_rel:
a 	bufs[i].readonly = readonly;
GROUP 6
+	{"ro", ec_readonly},
pattern:
	\{"rd", ec_undoredo\},
edit_cmd_rel:
a 	{"ro", ec_readonly},
=== END DELTA ===
=== DELTA vi.c ===
GROUP 1
+			else if (argv[i][j] == 'R')
+				readonly = 1;
pattern:
			else if \(argv\[i\]\[j\] == 'a'\)
				xvis \|= 8;
edit_cmd_rel:
+1a 			else if (argv[i][j] == 'R')
				readonly = 1;
GROUP 2
-				fprintf(stderr, "Nextvi-5.0 Usage: %s [-aemsv] [file ...]\n", argv[0]);
+				fprintf(stderr, "Nextvi-5.0 Usage: %s [-aeRmsv] [file ...]\n", argv[0]);
pattern:
				fprintf\(stderr, "Unknown option: -%c\\n", argv\[i\]\[j\]\);
edit_cmd_relc:
+1
.;46c R
edit_cmd_rel:
+1
s/(\[-a.*m)/\1R/
=== END DELTA ===
=== DELTA vi.h ===
GROUP 1
+	char readonly;			/* read only */
pattern:
	signed char td;			/\* text direction \*/
edit_cmd_rel:
a 	char readonly;			/* read only */
GROUP 2
+extern char readonly;
strategy: abs
edit_cmd_abs:
\$a extern char readonly;
=== END DELTA ===
=== PATCH2VI PATCH ===
diff --git a/ex.c b/ex.c
index d8a2c535..68f08ea9 100644
--- a/ex.c
+++ b/ex.c
@@ -1,3 +1,4 @@
+char readonly = 0;		/* commandline readonly option */
 int xleft;			/* the first visible column */
 int xvis;			/* startup flags */
 int xai = 1;			/* autoindent option */
@@ -116,6 +117,7 @@ static int bufs_open(const char *path, int len)
 	bufs[i].top = 0;
 	bufs[i].td = +1;
 	bufs[i].mtime = -1;
+	bufs[i].readonly = readonly;
 	return i;
 }
 
@@ -370,6 +372,8 @@ static void *ec_edit(char *loc, char *cmd, char *arg)
 		bufs_switch(bufs_open(arg+cd, len));
 		cd = 3; /* XXX: quick hack to indicate new lbuf */
 	}
+	if (access(arg, F_OK) == 0 && access(arg, W_OK) == -1)
+		ex_buf->readonly = 1;
 	readfile(rd =)
 	if (cd == 3 || (!rd && fd >= 0)) {
 		ex_bufpostfix(ex_buf, arg[0]);
@@ -689,6 +693,8 @@ static void *ec_write(char *loc, char *cmd, char *arg)
 		free(ibuf.s);
 	} else {
 		if (!strchr(cmd, '!')) {
+			if (ex_buf->readonly)
+				return "write failed: readonly option is set";
 			if (!strcmp(xb_path, path) && mtime(path) > ex_buf->mtime)
 				return "write failed: file changed";
 			if (arg[0] && mtime(path) >= 0)
@@ -1429,6 +1435,12 @@ static void *ec_krsset(char *loc, char *cmd, char *arg)
 	return xkwdrs ? NULL : xserr;
 }
 
+static void *ec_readonly(char *loc, char *cmd, char *arg)
+{
+	ex_buf->readonly = !ex_buf->readonly;
+	return NULL;
+}
+
 static int eo_val(char *arg)
 {
 	int val = atoi(arg);
@@ -1515,6 +1527,7 @@ static struct excmd {
 	{"reg", ec_regprint},
 	{"re", ec_krsset},
 	{"rd", ec_undoredo},
+	{"ro", ec_readonly},
 	{"r", ec_read},
 	{"wq!", ec_write},
 	{"wq", ec_write},
diff --git a/vi.c b/vi.c
index 276e096a..6cc810a1 100644
--- a/vi.c
+++ b/vi.c
@@ -1851,11 +1851,13 @@ int main(int argc, char *argv[])
 				xvis |= 4;
 			else if (argv[i][j] == 'a')
 				xvis |= 8;
+			else if (argv[i][j] == 'R')
+				readonly = 1;
 			else if (argv[i][j] == 'v')
 				xvis = 0;
 			else {
 				fprintf(stderr, "Unknown option: -%c\n", argv[i][j]);
-				fprintf(stderr, "Nextvi-5.0 Usage: %s [-aemsv] [file ...]\n", argv[0]);
+				fprintf(stderr, "Nextvi-5.0 Usage: %s [-aeRmsv] [file ...]\n", argv[0]);
 				return EXIT_FAILURE;
 			}
 		}
diff --git a/vi.h b/vi.h
index 59f3543e..19b25815 100644
--- a/vi.h
+++ b/vi.h
@@ -400,6 +400,7 @@ struct buf {
 	int plen, row, off, top;
 	long mtime;			/* modification time */
 	signed char td;			/* text direction */
+	char readonly;			/* read only */
 };
 /* ex options */
 extern int xleft;
@@ -538,3 +539,4 @@ extern int vi_lncol;
 /* filesystem */
 extern rset *fsincl;
 void dir_calc(char *path);
+extern char readonly;
