#!/bin/sh
# Generated by patch2vi from unified diff
# Available separators: 0001-0010 0013-0014 0016-0037 0102-0104 0107-0110 0112-0113 0115-0116 0120-0132 0136 0153 0176-0377
set -e

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

# Path to nextvi (adjust as needed)
VI=${VI:-vi}

# Uncomment to enter interactive vi on patch failure
#DBG="|sc|vis 2:e $0:@Q:q!1"
# Uncomment to skip errors (. = silent nop)
#DBG="."
# Set QF=. to continue despite errors (errors are still printed)
#QF=.

# Verify that VI is nextvi
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi" >&2
    exit 1
fi

# Patch: ex.c
SEP="$(printf '\001')"
QF=${QF-"$(printf 'vis 2\\\001q! 1')"}
EXINIT="rcm:|sc! \\\\${SEP}|vis 3${SEP}25a int xrec;			/* input recoding register */
.
${SEP}%f> EO\\\\(pac\\\\)${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1382\\${SEP}${QF}}${SEP};=
${SEP}+2a EO(rec)
.
${SEP}.,\$;f> 	\\\\{\"q!\", ec_quit\\\\},
	\\\\{\"q\", ec_quit\\\\},
	EO\\\\(rcm\\\\),${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1446\\${SEP}${QF}}${SEP};=
${SEP}+2a 	EO(rec),
.
${SEP}vis 2${SEP}wq" $VI -e 'ex.c'

# Patch: term.c
SEP="$(printf '\001')"
QF=${QF-"$(printf 'vis 2\\\001q! 1')"}
EXINIT="rcm:|sc! \\\\${SEP}|vis 3${SEP}%;f> 		ret:
		ibuf_cnt = 1;
		ibuf_pos = 0;${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 180\\${SEP}${QF}}${SEP};=
${SEP}+2a 		if (xrec && *ibuf) {
			char buf[2];
			buf[0] = *ibuf;
			buf[1] = '\\\\0';
			ex_regput(xrec, buf, 1);
		}
.
${SEP}vis 2${SEP}wq" $VI -e 'term.c'

# Patch: vi.h
SEP="$(printf '\001')"
QF=${QF-"$(printf 'vis 2\\\001q! 1')"}
EXINIT="rcm:|sc! \\\\${SEP}|vis 3${SEP}%f> /\\\\* global variables \\\\*/${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 437\\${SEP}${QF}}${SEP};=
${SEP}.i extern int xrec;
.
${SEP}vis 2${SEP}wq" $VI -e 'vi.h'

exit 0
=== PATCH2VI DELTA ===
=== DELTA ex.c ===
--- /tmp/patch2vi_7AaEO5_ex.c.diff.orig	2026-04-11 14:30:53.777406815 +0000
+++ /tmp/patch2vi_7AaEO5_ex.c.diff	2026-04-11 14:31:06.714938933 +0000
@@ -1,7 +1,7 @@
 === GROUP 1/3 (line 25) ===
 +int xrec;			/* input recoding register */
 === COMMAND STRATEGY (default: rel) ===
-#abs
+abs
 25a
 #rel
 %;f>
@@ -25,9 +25,7 @@
 #rel
 .,\$;f>
 === SEARCH PATTERN (offset: 3) ===
-EO\(pac\) EO\(pr\) EO\(ai\) EO\(err\) EO\(ish\) EO\(ic\) EO\(grp\) EO\(mpt\) EO\(rcm\)
-EO\(shape\) EO\(seq\) EO\(ts\) EO\(td\) EO\(order\) EO\(hll\) EO\(hlw\)
-EO\(hlp\) EO\(hlr\) EO\(hl\) EO\(lim\) EO\(led\) EO\(vis\)
+EO\(pac\)
 --- extra (delete to include) ---
 
 _EO\(left,
=== DELTA vi.h ===
--- /tmp/patch2vi_ATqlSq_vi.h.diff.orig	2026-04-11 14:32:24.354554278 +0000
+++ /tmp/patch2vi_ATqlSq_vi.h.diff	2026-04-11 14:32:32.939936236 +0000
@@ -5,13 +5,7 @@
 437a
 #rel
 %;f>
-=== SEARCH PATTERN (offset: 3) ===
-extern int xlim;
-extern int xseq;
-extern int xerr;
---- extra (delete to include) ---
+=== SEARCH PATTERN (offset: 0) ===
 /\* global variables \*/
-extern int xquit;
-extern int xrow, xoff, xtop;
 === END GROUP ===
 
=== PATCH2VI PATCH ===
diff --git a/ex.c b/ex.c
index 81878d89..741c4aa7 100644
--- a/ex.c
+++ b/ex.c
@@ -23,6 +23,7 @@ int xerr = 1;			/* error handling -
 				bit 1: print errors, bit 2: early return, bit 3: ignore errors */
 int xrcm = 1;			/* range command model -
 				0: exec at command parse 1: exec at command */
+int xrec;			/* input recoding register */
 
 int xquit;			/* exit if positive, force quit if negative */
 int xrow, xoff, xtop;		/* current row, column, and top row */
@@ -1380,6 +1381,7 @@ static void *eo_##opt(char *loc, char *cmd, char *arg) { inner }
 EO(pac) EO(pr) EO(ai) EO(err) EO(ish) EO(ic) EO(grp) EO(mpt) EO(rcm)
 EO(shape) EO(seq) EO(ts) EO(td) EO(order) EO(hll) EO(hlw)
 EO(hlp) EO(hlr) EO(hl) EO(lim) EO(led) EO(vis)
+EO(rec)
 
 _EO(left,
 	if (*loc)
@@ -1444,6 +1446,7 @@ static struct excmd {
 	{"q!", ec_quit},
 	{"q", ec_quit},
 	EO(rcm),
+	EO(rec),
 	{"reg+", ec_regprint},
 	{"reg", ec_regprint},
 	{"rd", ec_undoredo},
diff --git a/term.c b/term.c
index 8c674664..9a1ddb71 100644
--- a/term.c
+++ b/term.c
@@ -178,6 +178,12 @@ int term_read(int winch)
 		ret:
 		ibuf_cnt = 1;
 		ibuf_pos = 0;
+		if (xrec && *ibuf) {
+			char buf[2];
+			buf[0] = *ibuf;
+			buf[1] = '\0';
+			ex_regput(xrec, buf, 1);
+		}
 	}
 	if (icmd_pos < sizeof(icmd))
 		icmd[icmd_pos++] = ibuf[ibuf_pos];
diff --git a/vi.h b/vi.h
index 4726dfbf..723e6c78 100644
--- a/vi.h
+++ b/vi.h
@@ -435,6 +435,7 @@ extern int xpr;
 extern int xlim;
 extern int xseq;
 extern int xerr;
+extern int xrec;
 /* global variables */
 extern int xquit;
 extern int xrow, xoff, xtop;
