#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0001-0010 0013-0014 0016-0037 0112-0113 0120-0121 0124 0126 0130 0132 0176-0377

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

SEP="$(printf '\001')"
# Command that handles readability line breaks
LB="0?"
# Phase 1 (search/mark): errors disabled by default,
# DBG1=1 enables error reporting, QF1=1 quits on failure
[ "$DBG1" = "1" ] && DBG1= || DBG1="0\?"
[ "$QF1" = "1" ] && QF1="\\${SEP}vis 2\\${SEP}q!1" || QF1=
# Phase 2 (edits): DBG2=1 disables errors, QF2=1 ignores them
[ "$DBG2" = "1" ] && DBG2="0\?" || DBG2=
[ "$QF2" = "1" ] && QF2= || QF2="\\${SEP}vis 2\\${SEP}q!1"
# Enters vi at failing code line in this script
# Designed for state inspection mid execution
[ "$INTR" = "1" ] && INTR="\\${SEP}|sc|\\${SEP}vis 2:0reg:e $0:83reg %@/:%f> %@p:&Q:b0:|sc! \\\\\\${SEP}|:vis 3\\${SEP}q1" || INTR=

# Patch: conf.c ex.c term.c vi.h
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}98reg${SEP}b0${SEP}%ya b${SEP};0${SEP}0reg${SEP}.,\$f> \\\\|\\\\(\\\\[\\\\.%\\\\\$\\\\]\\\\|\\\\[0-9 \\\\\\\\t\\\\]\\\\*\\\\)\\\\?\\\\)\\\\)\\\\(\\\\?:\\\\(\\\\[-\\\\*-\\\\+/%\\\\]\\\\)\\\\[ \\\\\\\\t\\\\]\\\\*\\\\[0-9\\\\]\\\\+\\\\[ \\\\\\\\t\\\\]\\\\*\\\\)\\\\*\\\\(\\\\?:\\\\[ \\\\\\\\t\\\\]\\\\*\\\\\\\\\\\\\\\\\\\\|\\\\.\\\\*\\\\?\\\\(\\\\?:\\\\(\\\\?<\\\\^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\)\\\\\\\\\\\\\\\\\\\\|\\\\|\\\\\$\\\\)\\\\[ \\\\\\\\t\\\\]\\\\*\\\\)\\\\*\\\\)\\\\[ \\\\\\\\t\\\\]\\\\*\\\\\\\\${SEP}??!${DBG1:-ya!p\\${SEP}prp\\${SEP}p FAIL conf.c:295\\${SEP}pr${INTR}${QF1}}${SEP}98reg${SEP}${LB}
${SEP}+3m 0${SEP}${LB}
${SEP}'0s/t\\\\|s/t|rec|s/${SEP}??!${DBG2:-ya!p\\${SEP}prp\\${SEP}p FAIL conf.c:295:m0\\${SEP}pr${INTR}${QF2}}${SEP}b1${SEP}%ya b${SEP};0${SEP}0reg${SEP}.,\$f> EO\\\\(pac\\\\)${SEP}??!${DBG1:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1496\\${SEP}pr${INTR}${QF1}}${SEP}98reg${SEP}${LB}
${SEP}+2m 0${SEP};0${SEP}0reg${SEP}.,\$f+ 	\\\\{\"q\", ec_quit\\\\},${SEP}??!${DBG1:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1564\\${SEP}pr${INTR}${QF1}}${SEP}98reg${SEP}${LB}
${SEP}m 1${SEP}${LB}
${SEP}1i int xrec;			/* input recoding register */
${SEP}??!${DBG2:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:0:m\\${SEP}pr${INTR}${QF2}}${SEP}${LB}
${SEP}'0a EO(rec)
${SEP}??!${DBG2:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1496:m0\\${SEP}pr${INTR}${QF2}}${SEP}${LB}
${SEP}'1a 	EO(rec),
${SEP}??!${DBG2:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1564:m1\\${SEP}pr${INTR}${QF2}}${SEP}b2${SEP}%ya b${SEP}%;f> 		ret:
		ibuf_cnt = 1;
		ibuf_pos = 0;${SEP}??!${DBG1:-ya!p\\${SEP}prp\\${SEP}p FAIL term.c:172\\${SEP}pr${INTR}${QF1}}${SEP}${LB}
${SEP}+2m 0${SEP}${LB}
${SEP}'0a 		if (xrec && *ibuf) {
			char buf[2];
			buf[0] = *ibuf;
			buf[1] = '\\\\0';
			ex_regput(xrec, buf, 1);
		}
${SEP}??!${DBG2:-ya!p\\${SEP}prp\\${SEP}p FAIL term.c:172:m0\\${SEP}pr${INTR}${QF2}}${SEP}b3${SEP}%ya b${SEP};0${SEP}0reg${SEP}.,\$f> /\\\\* global variables \\\\*/${SEP}??!${DBG1:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.h:430\\${SEP}pr${INTR}${QF1}}${SEP}98reg${SEP}${LB}
${SEP}m 0${SEP}${LB}
${SEP}'0i extern int xrec;
${SEP}??!${DBG2:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.h:430:m0\\${SEP}pr${INTR}${QF2}}${SEP}vis 2${SEP}b0${SEP}w${SEP}b1${SEP}w${SEP}b2${SEP}w${SEP}b3${SEP}w${SEP}q" $VI -e 'conf.c' 'ex.c' 'term.c' 'vi.h'

exit 0
=== PATCH2VI DELTA ===
=== DELTA conf.c ===
=== GROUP 1 ===
-((pac|pr|ai|ish|err|ic|grp|mpt|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
+((pac|pr|ai|ish|err|ic|grp|mpt|rec|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
=== END ===
=== LEVEL 2 ===
=== pre_ctx ===
(?:'[0-9]+)|([.%$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*[0-9]+[ \t]*)*(?:[ \t]*\\|.*?(?:(?<^\\\\)\\||$)[ \t]*)*)[ \t]*\
(?:([,;]#?)[ \t]*((?:\\|.*?(?:(?<^\\\\)\\||$)[ \t]*)*(?:(?:<.*?(?:(?<^\\\\)<|$)|>.*?(?:(?<^\\\\)>|$))|\
(?:'[0-9]+)|([.$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*([0-9]+)[ \t]*)*(?:[ \t]*\\|.*?(?:(?<^\\\\)\\||$))*[ \t]*)*)\
=== END ===
=== post_ctx ===
|[@&!dmj]|=\\?{0,1}|\\?{1,2}[?!]?|b[psx]?|p[uh]?|ac?|e[f!]?!?|f[-+><tdp]?|inc|i|sc!?|\
(?:g!?|s)[ \t]?(.)?|q!?|reg?\\+?|rd?|w(?:q!|[q!])?|u[czbd]|x!?|ya!?|cm!?|cd?)?",
		A(BL1 | SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1)},
=== END ===
=== pattern ===
\|\(\[\.%\$\]\|\[0-9 \\t\]\*\)\?\)\)\(\?:\(\[-\*-\+/%\]\)\[ \\t\]\*\[0-9\]\+\[ \\t\]\*\)\*\(\?:\[ \\t\]\*\\\\\|\.\*\?\(\?:\(\?<\^\\\\\\\\\)\\\\\|\|\$\)\[ \\t\]\*\)\*\)\[ \\t\]\*\\
=== END ===
=== END ===
=== DELTA ex.c ===
=== GROUP 1 ===
+int xrec;			/* input recoding register */
=== END ===
=== LEVEL 2 ===
=== post_ctx ===
int xleft;			/* the first visible column */
int xvis;			/* startup flags */
int xai = 1;			/* autoindent option */
=== END ===
=== strategy ===
abs
=== END ===
=== GROUP 2 ===
+EO(rec)
=== END ===
=== LEVEL 2 ===
=== pre_ctx ===
EO(pac) EO(pr) EO(ai) EO(err) EO(ish) EO(ic) EO(mpt)
EO(shape) EO(seq) EO(ts) EO(td) EO(order) EO(hll) EO(hlw)
EO(hlp) EO(hlr) EO(hl) EO(lim) EO(led) EO(vis)
=== END ===
=== post_ctx ===

_EO(grp, xgrp = (!*arg ? !xgrp : eo_val(arg)) * 2; return NULL;)

=== END ===
=== pattern ===
EO\(pac\)
=== END ===
=== GROUP 3 ===
+	EO(rec),
=== END ===
=== LEVEL 2 ===
=== pre_ctx ===
	{"m", ec_mark},
	{"q!", ec_quit},
	{"q", ec_quit},
=== END ===
=== post_ctx ===
	{"reg+", ec_regprint},
	{"reg", ec_regprint},
	{"re", ec_krsset},
=== END ===
=== pattern ===
	\{"q", ec_quit\},
=== END ===
=== edit_cmd_rel ===
a 	EO(rec),
=== END ===
=== END ===
=== DELTA vi.h ===
=== GROUP 1 ===
+extern int xrec;
=== END ===
=== LEVEL 2 ===
=== pre_ctx ===
extern int xlim;
extern int xseq;
extern int xerr;
=== END ===
=== post_ctx ===
/* global variables */
extern int xquit;
extern int xrow, xoff, xtop;
=== END ===
=== pattern ===
/\* global variables \*/
=== END ===
=== edit_cmd_rel ===
i extern int xrec;
=== END ===
=== END ===
=== PATCH2VI PATCH ===
diff --git a/conf.c b/conf.c
index d8967839..1e55f19a 100644
--- a/conf.c
+++ b/conf.c
@@ -292,7 +292,7 @@ return|select|switch|type|var))\\>", A(GR1, BL1 | SYN_BD, YE1)},
 (?:'[0-9]+)|([.%$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*[0-9]+[ \t]*)*(?:[ \t]*\\|.*?(?:(?<^\\\\)\\||$)[ \t]*)*)[ \t]*\
 (?:([,;]#?)[ \t]*((?:\\|.*?(?:(?<^\\\\)\\||$)[ \t]*)*(?:(?:<.*?(?:(?<^\\\\)<|$)|>.*?(?:(?<^\\\\)>|$))|\
 (?:'[0-9]+)|([.$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*([0-9]+)[ \t]*)*(?:[ \t]*\\|.*?(?:(?<^\\\\)\\||$))*[ \t]*)*)\
-((pac|pr|ai|ish|err|ic|grp|mpt|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
+((pac|pr|ai|ish|err|ic|grp|mpt|rec|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
 |[@&!dmj]|=\\?{0,1}|\\?{1,2}[?!]?|b[psx]?|p[uh]?|ac?|e[f!]?!?|f[-+><tdp]?|inc|i|sc!?|\
 (?:g!?|s)[ \t]?(.)?|q!?|reg?\\+?|rd?|w(?:q!|[q!])?|u[czbd]|x!?|ya!?|cm!?|cd?)?",
 		A(BL1 | SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1)},
diff --git a/ex.c b/ex.c
index bc6a6269..c851af57 100644
--- a/ex.c
+++ b/ex.c
@@ -1,3 +1,4 @@
+int xrec;			/* input recoding register */
 int xleft;			/* the first visible column */
 int xvis;			/* startup flags */
 int xai = 1;			/* autoindent option */
@@ -1494,6 +1495,7 @@ static void *eo_##opt(char *loc, char *cmd, char *arg) { inner }
 EO(pac) EO(pr) EO(ai) EO(err) EO(ish) EO(ic) EO(mpt)
 EO(shape) EO(seq) EO(ts) EO(td) EO(order) EO(hll) EO(hlw)
 EO(hlp) EO(hlr) EO(hl) EO(lim) EO(led) EO(vis)
+EO(rec)
 
 _EO(grp, xgrp = (!*arg ? !xgrp : eo_val(arg)) * 2; return NULL;)
 
@@ -1562,6 +1564,7 @@ static struct excmd {
 	{"m", ec_mark},
 	{"q!", ec_quit},
 	{"q", ec_quit},
+	EO(rec),
 	{"reg+", ec_regprint},
 	{"reg", ec_regprint},
 	{"re", ec_krsset},
diff --git a/term.c b/term.c
index 65254701..8804effc 100644
--- a/term.c
+++ b/term.c
@@ -170,6 +170,12 @@ int term_read(int winch)
 		ret:
 		ibuf_cnt = 1;
 		ibuf_pos = 0;
+		if (xrec && *ibuf) {
+			char buf[2];
+			buf[0] = *ibuf;
+			buf[1] = '\0';
+			ex_regput(xrec, buf, 1);
+		}
 	}
 	if (icmd_pos < sizeof(icmd))
 		icmd[icmd_pos++] = ibuf[ibuf_pos];
diff --git a/vi.h b/vi.h
index 98f80e03..e0448294 100644
--- a/vi.h
+++ b/vi.h
@@ -428,6 +428,7 @@ extern int xpr;
 extern int xlim;
 extern int xseq;
 extern int xerr;
+extern int xrec;
 /* global variables */
 extern int xquit;
 extern int xrow, xoff, xtop;
