#!/bin/sh -e
for s in *.sh
do
	head -2 "$s" | grep -q "Generated by patch2vi" || continue
	printf "%s\n" "SCRIPT: $s"
	sed '1,/^exit 0$/d' "$s" | patch -p1 --merge=diff3
	[ "$1" = "1" ] && ./cbuild.sh build
	git diff > /tmp/tmp.patch
	git checkout . &>/dev/null
	# Replace embedded patch: keep everything up to "exit 0", append new diff
	sed '/^exit 0$/q' "$s" > /tmp/tmp.sh
	cat /tmp/tmp.patch >> /tmp/tmp.sh
	cp /tmp/tmp.sh "$s"
	chmod +x "$s"
	git add "$s"
	printf "\n"
done
rm -f tmp *.orig *.rej
