#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0001-0010 0013-0014 0016-0037 0104 0110 0112-0113 0120-0121 0126 0131-0132 0177-0377

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

SEP="$(printf '\001')"
# Command that handles readability line breaks
LB="0?"
# Disable errors
[ "$DBG" = "1" ] && DBG="0\?" || DBG=
# Ignore errors
[ "$QF" = "1" ] && QF= || QF="\\${SEP}vis 2\\${SEP}q!1"
# Enters vi at failing code line in this script
# Designed for state inspection mid execution
[ "$INTR" = "1" ] && INTR="\\${SEP}|sc|\\${SEP}vis 2:0reg:e $0:83reg %@/:%f> %@p:&Q:b0:|sc! \\\\\\${SEP}|:vis 3\\${SEP}q1" || INTR=

# Patch: ex.c lbuf.c regex.c vi.c vi.h
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}98reg${SEP}b0${SEP}%ya b${SEP}%;f> int xesc = '\\\\\\\\\\\\\\\\';		/\\\\* ex command arg escape character \\\\*/
int xexec_dep;			/\\\\* ex_exec recursion depth \\\\*/
sbuf \\\\*xacreg;			/\\\\* autocomplete db filter regex \\\\*/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:38\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 0${SEP}%;f+ \\\\{
	sbuf \\\\*reg = xregs\\\\['/'\\\\];
	if \\\\(kwd && \\\\*kwd && \\\\(\\\\(!reg \\\\|\\\\| !xkwdrs \\\\|\\\\| strcmp\\\\(kwd, reg->s\\\\)\\\\)${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:179\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 1${SEP}%;f+ 
static void \\\\*ec_fuzz\\\\(char \\\\*loc, char \\\\*cmd, char \\\\*arg\\\\)
\\\\{${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:389\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 2${SEP}%;f+ 	while \\\\(1\\\\) \\\\{
		sbuf_null\\\\(fuzz\\\\)
		c = 0;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:418\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 3${SEP};0${SEP}0reg${SEP}.,\$f+ ^		if \\\\(rs\\\\) \\\\{\$${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:420\\${SEP}pr${INTR}${QF}}${SEP}98reg${SEP}${LB}
${SEP}+1m 4${SEP}%;f+ 			dwid1 = max == INT_MAX \\\\? dwid2 : MIN\\\\(dwid1, dwid2\\\\);
			for \\\\(pos = beg; c < max && pos < end; pos\\\\+\\\\+\\\\) \\\\{
				path = xb->ln\\\\[pos\\\\];${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:427\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 5${SEP}%;f+ 				break;
			\\\\}
		\\\\}
		rset_free\\\\(rs\\\\);${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:465\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 6${SEP}%;f+ 	free\\\\(sb->s\\\\);
	path = lbuf_get\\\\(xb, lnum\\\\);
	if \\\\(\\\\*cmd == 'f' && path\\\\) \\\\{${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:492\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 7${SEP}%;f+ 		path\\\\[lbuf_s\\\\(path\\\\)->len\\\\] = '\\\\\\\\n';
	} else if \\\\(\\\\*cmd != 'f'\\\\)
		temp_switch\\\\(1, 1\\\\);${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:501\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 8${SEP}%;f+ 	if \\\\(!xkwdrs\\\\)
		return xserr;
	if \\\\(\\\\(xdefreg \\\\|\\\\| o1 >= 0\\\\) && dir > 0\\\\) \\\\{${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:516\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 9${SEP}%;f+ 			sbuf \\\\*sb = xregs\\\\[xdefreg\\\\];
			if \\\\(!sb\\\\)
				return \"uninitialized register\";${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:525\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 10${SEP}%;f+ 		sbuf sb;
		void \\\\*ret = NULL;
		lbuf_region\\\\(xb, &sb, beg, o1, r2, o2\\\\);${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:535\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 11${SEP}%;f+ 	int beg, end, grp;
	char \\\\*pat, \\\\*rep = NULL, \\\\*_rep;
	char \\\\*s = arg;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1013\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 12${SEP}%;f+ 		return xrerr;
	pat = re_read\\\\(&s, 0\\\\);
	if \\\\(pat && \\\\(\\\\*pat \\\\|\\\\| !rs\\\\)\\\\)${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1020\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 13${SEP}%;f+ 		rep = re_read\\\\(&s, 0\\\\);
	}
	free\\\\(pat\\\\);${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1030\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 14${SEP}%;f+ 	for \\\\(i = beg; i < end; i\\\\+\\\\+\\\\) \\\\{
		char \\\\*ln = lbuf_get\\\\(xb, i\\\\);
		sbuf \\\\*r = NULL;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1034\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 15${SEP}%;f+ 					}
					_rep\\\\+\\\\+;
					grp = abs\\\\(\\\\(\\\\*_rep - '0'\\\\) \\\\* 2\\\\);${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1049\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 16${SEP}%;f+ 		lbuf_emark\\\\(xb, lo, last, 0\\\\);
	}
	if \\\\(rs != xkwdrs\\\\)${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1080\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 17${SEP}%;f+ \\\\{
	int i, beg, end, not, matched = 0;
	char \\\\*pat, \\\\*s = arg;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1149\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 18${SEP}%;f+ 	not = !!strchr\\\\(cmd, '!'\\\\);
	pat = re_read\\\\(&s, 0\\\\);
	if \\\\(pat && \\\\*pat\\\\)${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1157\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 19${SEP};0${SEP}0reg${SEP}.,\$f+ ^	else\$${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1159\\${SEP}pr${INTR}${QF}}${SEP}98reg${SEP}${LB}
${SEP}+1m 20${SEP}%;f+ 	for \\\\(i = beg; i < lbuf_len\\\\(xb\\\\);\\\\) \\\\{
		char \\\\*ln = lbuf_get\\\\(xb, i\\\\);
		lbuf_s\\\\(ln\\\\)->grec &= ~xgdep;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1169\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 21${SEP}%;f+ 		while \\\\(i < lbuf_len\\\\(xb\\\\) && !\\\\(lbuf_i\\\\(xb, i\\\\)->grec & xgdep\\\\)\\\\)
			i\\\\+\\\\+;
	}${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1179\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 22${SEP}%;f+ 
static void \\\\*ec_setincl\\\\(char \\\\*loc, char \\\\*cmd, char \\\\*arg\\\\)
\\\\{${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1320\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 23${SEP}%;f+ 	if \\\\(!\\\\*arg\\\\)
		fsincl = NULL;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1323\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2m 24${SEP}${LB}
${SEP}'0s/rset \\\\*x/rstr *x/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:38\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'1,#+2c 			|| ((xkwdrs->flg & REG_ICASE) != xic))) {
		rstr_free(xkwdrs);
		xkwdrs = rstr_make(kwd, xic ? REG_ICASE : 0);
${SEP}${LB}
${SEP}'2s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:389\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'3s/et_s/tr_/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:418\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'4s/regex->//${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:420\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'5s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:427\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'6s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:465\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'7s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:492\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'8s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:501\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'9s/nsubc/rs ? xkwdrs->rs->nsubc : 2/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:516\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'10s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:525\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'11s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:535\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'12s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1013\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'13s/et_s/tr_/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1020\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'14s/nsubc/rs ? rs->rs->nsubc : 2/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1030\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'15s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1034\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'16s/rs->nsubc/(rs->rs ? rs->rs->nsubc : 2)/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1049\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'17s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1080\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'18s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1149\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'19s/et_s/tr_/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1157\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'20s/et_s/tr_/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1159\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'21s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1169\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'22s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1179\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'23s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1320\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'24s/et_s/tr_/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL ex.c:1323\\${SEP}pr${INTR}${QF}}${SEP}b1${SEP}%ya b${SEP}%;f> 	return n != 0;
}

${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL lbuf.c:493\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 0${SEP}%;f+ 		int nskip, int \\\\*r, int \\\\*o\\\\)
\\\\{
	int r0 = \\\\*r, o0 = \\\\*o;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL lbuf.c:497\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 1${SEP}%;f+ 		step = 0;
		flg = REG_NEWLINE;
		s = lb->ln\\\\[i\\\\];${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL lbuf.c:510\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 2${SEP}${LB}
${SEP}'0s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL lbuf.c:493\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'1s/nsubc/rs ? re->rs->nsubc : 2/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL lbuf.c:497\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'2s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL lbuf.c:510\\${SEP}pr${INTR}${QF}}${SEP}b2${SEP}%ya b${SEP}%;f> 	\\\\*src = \\\\*s \\\\? s \\\\+ 1 : s;
	sbufn_ret\\\\(sb, sb->s\\\\)
}${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL regex.c:766\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2m 0${SEP}${LB}
${SEP}'0a 
/* return zero if a simple pattern is given */
static int rstr_simple(rstr *rs, char *re, int icase)
{
	char *beg;
	char *end;
	if (!strcmp(re, \"^\$\"))
		return 1;
	rs->lbeg = re[0] == '^';
	if (rs->lbeg)
		re++;
	rs->wbeg = re[0] == '\\\\\\\\' && re[1] == '<';
	if (rs->wbeg)
		re += 2;
	beg = re;
	while (re[0] && !strchr(\"\\\\\\\\.*+?[]{}()\$\", (unsigned char) re[0]))
		re++;
	end = re;
	rs->wend = re[0] == '\\\\\\\\' && re[1] == '>';
	if (rs->wend)
		re += 2;
	rs->lend = re[0] == '\$';
	if (rs->lend)
		re++;
	if (!re[0]) {
		int len = end - beg;
		rs->len = len;
		rs->str = emalloc(len + 1);
		rs->str[len] = '\\\\0';
		if (icase) {
			while (--len >= 0)
				rs->str[len] = tolower((unsigned char)beg[len]);
		} else
			memcpy(rs->str, beg, len);
		return 0;
	}
	return 1;
}

rstr *rstr_make(char *re, int flg)
{
	rstr *rs = emalloc(sizeof(*rs));
	memset(rs, 0, sizeof(*rs));
	rs->flg = flg;
	if (rstr_simple(rs, re, flg & REG_ICASE))
		rs->rs = rset_make(1, &re, flg);
	if (!rs->rs && !rs->str) {
		free(rs);
		return NULL;
	}
	return rs;
}

#define rstr_cmp(gen, wbeg, wend, cmpcase) \\\\
wbeg wend \\\\
m = rs->str; t = r; \\\\
for (; *m && *t; t++, m++) { \\\\
	if (cmpcase) \\\\
		goto break##gen; \\\\
} \\\\
if (!*m) { \\\\
	if (grps) { \\\\
		grps[0] = r - s; \\\\
		grps[1] = r - s + len; \\\\
	} \\\\
	return 0; \\\\
} \\\\
break##gen:; \\\\

#define rstr_match1(gen, wbeg, wend, cmpcase, stopcond) \\\\
{ for (r = beg; stopcond; r++) { \\\\
	rstr_cmp(2##gen, wbeg, wend, cmpcase) \\\\
} } \\\\

#define _wbeg if (r > s && (isword(r - 1) || !isword(r))) continue;
#define _wend if (r[len] && (!isword(r + len - 1) || isword(r + len))) continue;

#define template(gen, cmpcase, stopcond) \\\\
if (!rs->wbeg && !rs->wend) \\\\
	rstr_match1(1##gen, /*nop*/, /*nop*/, cmpcase, stopcond) \\\\
else if (rs->wbeg && !rs->wend) \\\\
	rstr_match1(2##gen, _wbeg, /*nop*/, cmpcase, stopcond) \\\\
else if (!rs->wbeg && rs->wend) \\\\
	rstr_match1(3##gen, /*nop*/, _wend, cmpcase, stopcond) \\\\
else \\\\
	rstr_match1(4##gen, _wbeg, _wend, cmpcase, stopcond) \\\\

/* return zero if an occurrence is found */
int rstr_find(rstr *rs, char *s, int *grps, int flg)
{
	int len;
	char *beg, *end, *r, *t, *m;
	if (rs->rs)
		return rset_find(rs->rs, s, grps, flg);
	flg = rs->flg | flg;
	if ((rs->lbeg && (flg & REG_NOTBOL)) || (rs->lend && (flg & REG_NOTEOL)))
		return -1;
	if (!*s)
		return -1;
	len = rs->len;
	beg = s;
	if (rs->lbeg || rs->lend || !len) {
		end = s + strlen(s) - len - (flg & REG_NEWLINE ? 1 : 0);
		if (end < beg)
			return -1;
		if (rs->lend)
			beg = end;
		if (rs->lbeg)
			end = s;
		if (flg & REG_ICASE) {
			template(4, tolower((unsigned char) *t) != *m, r <= end)
		} else {
			template(3, *t != *m, r <= end)
		}
	} else {
		if (flg & REG_ICASE) {
			template(2, tolower((unsigned char) *t) != *m, r[len - 1])
		} else {
			template(1, *t != *m, r[len - 1])
		}
	}
	return -1;
}

int rstr_match(rstr *rs, char *s, int flg)
{
	if (rs->rs)
		return re_pikevm(rs->rs->regex, s, NULL, 0, flg);
	int ret = rstr_find(rs, s, NULL, flg);
	return ret < 0 ? 0 : 1;
}

void rstr_free(rstr *rs)
{
	if (!rs)
		return;
	rset_free(rs->rs);
	free(rs->str);
	free(rs);
}
${SEP}b3${SEP}%ya b${SEP}%;f> 	ex_regput\\\\(tolower\\\\(c\\\\), s, isupper\\\\(c\\\\)\\\\);
}

${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:380\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 0${SEP}%;f+ 				memcpy\\\\(cpath, ptrs\\\\[i\\\\], pathlen \\\\+ len\\\\);
				plen\\\\[i\\\\+\\\\+\\\\] = pathlen \\\\+ len;
			} else if \\\\(ret >= 0 && S_ISREG\\\\(statbuf\\\\.st_mode\\\\)\\\\)${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:419\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 1${SEP}${LB}
${SEP}'0s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:380\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'1s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:419\\${SEP}pr${INTR}${QF}}${SEP}b4${SEP}%ya b${SEP}%;f> 	int nsubc;		/\\\\* total sub count \\\\*/
	int n;			/\\\\* number of regular expressions in this set \\\\*/
} rset;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.h:112\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2m 0${SEP};0${SEP}0reg${SEP}.,\$f+ void rset_free${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.h:118\\${SEP}pr${INTR}${QF}}${SEP}98reg${SEP}${LB}
${SEP}m 1${SEP};0${SEP}0reg${SEP}.,\$f+ int lbuf_search${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.h:181\\${SEP}pr${INTR}${QF}}${SEP}98reg${SEP}${LB}
${SEP}m 2${SEP};0${SEP}0reg${SEP}.,\$f+ ^		int nskip, int \\\\*r, int \\\\*o\\\\);\$${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.h:182\\${SEP}pr${INTR}${QF}}${SEP}98reg${SEP}${LB}
${SEP}m 3${SEP};0${SEP}0reg${SEP}.,\$f+ extern rset \\\\*xkwdrs;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.h:445\\${SEP}pr${INTR}${QF}}${SEP}98reg${SEP}${LB}
${SEP}m 4${SEP};0${SEP}0reg${SEP}.,\$f+ int ex_krs${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.h:484\\${SEP}pr${INTR}${QF}}${SEP}98reg${SEP}${LB}
${SEP}m 5${SEP}%;f+ extern int vi_hidch;
extern int vi_lncol;
/\\\\* filesystem \\\\*/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.h:544\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3m 6${SEP}${LB}
${SEP}'0a typedef struct {
	rset *rs;		/* only for regex patterns */
	char *str;		/* for simple, non-regex patterns  */
	int len;		/* str length */
	int flg;		/* flags */
	int lbeg, lend;		/* match line beg/end */
	int wbeg, wend;		/* match word beg/end */
} rstr;
${SEP}${LB}
${SEP}'1a rstr *rstr_make(char *re, int flg);
int rstr_find(rstr *rs, char *s, int *grps, int flg);
int rstr_match(rstr *rs, char *s, int flg);
void rstr_free(rstr *rs);
${SEP}${LB}
${SEP}'2s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.h:181\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'3a 
${SEP}${LB}
${SEP}'4s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.h:445\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'5s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.h:484\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}'6s/et/tr/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.h:544\\${SEP}pr${INTR}${QF}}${SEP}vis 2${SEP}b0${SEP}w${SEP}b1${SEP}w${SEP}b2${SEP}w${SEP}b3${SEP}w${SEP}b4${SEP}w${SEP}q" $VI -e 'ex.c' 'lbuf.c' 'regex.c' 'vi.c' 'vi.h'

exit 0
=== PATCH2VI DELTA ===
=== DELTA ex.c ===
=== GROUP 7 ===
-		rset_free(rs);
+		rstr_free(rs);
=== END ===
=== LEVEL 2 ===
=== pre_ctx ===
				break;
			}
		}
=== END ===
=== post_ctx ===
		sbuf_cut(sb, 0)
		if (pflg) {
			term_clean();
=== END ===
=== pattern ===
				break;
			\}
		\}
		rset_free\(rs\);
=== END ===
=== END ===
=== DELTA vi.h ===
=== GROUP 2 ===
+rstr *rstr_make(char *re, int flg);
+int rstr_find(rstr *rs, char *s, int *grps, int flg);
+int rstr_match(rstr *rs, char *s, int flg);
+void rstr_free(rstr *rs);
=== END ===
=== LEVEL 2 ===
=== pre_ctx ===
rset *rset_make(int n, char **pat, int flg);
static rset *rset_smake(char *pat, int flg)
	{ char *ss[1] = {pat}; return rset_make(1, ss, flg); }
int rset_find(rset *re, char *s, int *grps, int flg);
int rset_match(rset *rs, char *s, int flg);
void rset_free(rset *re);
=== END ===
=== post_ctx ===
char *re_read(char **src, int delim);

/* lbuf.c: line buffer */
=== END ===
=== pattern ===
void rset_free
=== END ===
=== edit_cmd_rel ===
a rstr *rstr_make(char *re, int flg);
int rstr_find(rstr *rs, char *s, int *grps, int flg);
int rstr_match(rstr *rs, char *s, int flg);
void rstr_free(rstr *rs);
=== END ===
=== GROUP 3 ===
-int lbuf_search(struct lbuf *lb, rset *re, int dir, int beg, int end, int pskip,
+int lbuf_search(struct lbuf *lb, rstr *re, int dir, int beg, int end, int pskip,
=== END ===
=== LEVEL 2 ===
=== pre_ctx ===
int lbuf_eol(struct lbuf *lb, int r, int state);
int lbuf_next(struct lbuf *lb, int dir, int *r, int *o);
int lbuf_findchar(struct lbuf *lb, char *cs, int cmd, int n, int *r, int *o);
=== END ===
=== post_ctx ===
		int nskip, int *r, int *o);
=== END ===
=== pattern ===
int lbuf_search
=== END ===
=== edit_cmd_rel ===
+0
s/et/tr/
=== END ===
=== GROUP 5 ===
-extern rset *xkwdrs;
+extern rstr *xkwdrs;
=== END ===
=== LEVEL 2 ===
=== pre_ctx ===
extern int xesc;
extern int xexec_dep;
extern sbuf *xacreg;
=== END ===
=== post_ctx ===
extern sbuf *xregs[256];
extern int xdefreg;
extern struct buf *bufs;
=== END ===
=== pattern ===
extern rset \*xkwdrs;
=== END ===
=== edit_cmd_rel ===
+0
s/et/tr/
=== END ===
=== GROUP 6 ===
-int ex_krs(rset **krs, int *dir);
+int ex_krs(rstr **krs, int *dir);
=== END ===
=== LEVEL 2 ===
=== pre_ctx ===
#define ex_print(line, ft) { RS(2, ex_cprint(line, ft, -1, 0, 0, 1)); }
void ex_init(char **files, int n);
void ex_bufpostfix(struct buf *p, int clear);
=== END ===
=== post_ctx ===
void ex_krsset(char *kwd, int dir);
void ex_regesc(sbuf *sb, char *beg, char *end, int ex);
int ex_edit(const char *path, int len);
=== END ===
=== pattern ===
int ex_krs
=== END ===
=== edit_cmd_rel ===
+0
s/et/tr/
=== END ===
=== END ===
=== PATCH2VI PATCH ===
diff --git a/ex.c b/ex.c
index bc6a6269..8a0e338a 100644
--- a/ex.c
+++ b/ex.c
@@ -35,7 +35,7 @@ int xsep = ':';			/* ex command separator */
 int xesc = '\\';		/* ex command arg escape character */
 int xexec_dep;			/* ex_exec recursion depth */
 sbuf *xacreg;			/* autocomplete db filter regex */
-rset *xkwdrs;			/* the last searched keyword rset */
+rstr *xkwdrs;			/* the last searched keyword rset */
 sbuf *xregs[256];		/* string registers */
 int xdefreg;			/* ex default register */
 struct buf *bufs;		/* main buffers */
@@ -176,9 +176,9 @@ void ex_krsset(char *kwd, int dir)
 {
 	sbuf *reg = xregs['/'];
 	if (kwd && *kwd && ((!reg || !xkwdrs || strcmp(kwd, reg->s))
-			|| ((xkwdrs->regex->flg & REG_ICASE) != xic))) {
-		rset_free(xkwdrs);
-		xkwdrs = rset_smake(kwd, xic ? REG_ICASE : 0);
+			|| ((xkwdrs->flg & REG_ICASE) != xic))) {
+		rstr_free(xkwdrs);
+		xkwdrs = rstr_make(kwd, xic ? REG_ICASE : 0);
 		xkwdcnt++;
 		ex_regput('/', kwd, 0);
 		xkwddir = dir;
@@ -386,7 +386,7 @@ static void *ec_edit(char *loc, char *cmd, char *arg)
 
 static void *ec_fuzz(char *loc, char *cmd, char *arg)
 {
-	rset *rs;
+	rstr *rs;
 	char *path, *p, buf[128], trunc[128], *sret = NULL;
 	int c, pos, subs[2], inst = -1, lnum = -1;
 	int beg, end, max = INT_MAX, dwid1, dwid2;
@@ -415,16 +415,16 @@ static void *ec_fuzz(char *loc, char *cmd, char *arg)
 	while (1) {
 		sbuf_null(fuzz)
 		c = 0;
-		rs = rset_smake(fuzz->s, xic ? flg | REG_ICASE : flg);
+		rs = rstr_make(fuzz->s, xic ? flg | REG_ICASE : flg);
 		if (rs) {
-			syn_reloadft(syn_addhl(fuzz->s, 1), rs->regex->flg);
+			syn_reloadft(syn_addhl(fuzz->s, 1), rs->flg);
 			term_record = !!term_sbuf;
 			end = MIN(end, lbuf_len(xb));
 			dwid2 = itoalen(end);
 			dwid1 = max == INT_MAX ? dwid2 : MIN(dwid1, dwid2);
 			for (pos = beg; c < max && pos < end; pos++) {
 				path = xb->ln[pos];
-				if (rset_match(rs, path, 0)) {
+				if (rstr_match(rs, path, 0)) {
 					sbuf_mem(sb, &pos, sizeof(pos))
 					p = itoa(c++, buf);
 					int z, wid = p - buf;
@@ -462,7 +462,7 @@ static void *ec_fuzz(char *loc, char *cmd, char *arg)
 				break;
 			}
 		}
-		rset_free(rs);
+		rstr_free(rs);
 		sbuf_cut(sb, 0)
 		if (pflg) {
 			term_clean();
@@ -489,7 +489,7 @@ static void *ec_fuzz(char *loc, char *cmd, char *arg)
 	free(sb->s);
 	path = lbuf_get(xb, lnum);
 	if (*cmd == 'f' && path) {
-		rset_find(rs, path, subs, 0);
+		rstr_find(rs, path, subs, 0);
 		xrow = lnum;
 		xoff = uc_off(path, subs[0]);
 	} else if (path) {
@@ -498,7 +498,7 @@ static void *ec_fuzz(char *loc, char *cmd, char *arg)
 		path[lbuf_s(path)->len] = '\n';
 	} else if (*cmd != 'f')
 		temp_switch(1, 1);
-	rset_free(rs);
+	rstr_free(rs);
 	return sret;
 }
 
@@ -513,7 +513,7 @@ static void *ec_find(char *loc, char *cmd, char *arg)
 	if (!xkwdrs)
 		return xserr;
 	if ((xdefreg || o1 >= 0) && dir > 0) {
-		int offs[xkwdrs->nsubc];
+		int offs[xkwdrs->rs ? xkwdrs->rs->nsubc : 2];
 		int r2 = end - 1;
 		int skip = cmd[1] == '+' ? 1 : 0;
 		int soff = o1 >= 0 ? MAX(0, lbuf_pos2off(xb, beg, o1, r2, o2,
@@ -522,7 +522,7 @@ static void *ec_find(char *loc, char *cmd, char *arg)
 			sbuf *sb = xregs[xdefreg];
 			if (!sb)
 				return "uninitialized register";
-			if (soff >= sb->s_n || rset_find(xkwdrs, sb->s + soff, offs, 0) < 0
+			if (soff >= sb->s_n || rstr_find(xkwdrs, sb->s + soff, offs, 0) < 0
 					|| offs[xgrp] < 0
 					|| (o1 >= 0 && lbuf_off2pos(xb, beg, o1, r2, o2,
 							soff + offs[xgrp], &xrow, &xoff)))
@@ -532,7 +532,7 @@ static void *ec_find(char *loc, char *cmd, char *arg)
 		sbuf sb;
 		void *ret = NULL;
 		lbuf_region(xb, &sb, beg, o1, r2, o2);
-		if (rset_find(xkwdrs, sb.s + soff, offs, 0) < 0 || offs[xgrp] < 0
+		if (rstr_find(xkwdrs, sb.s + soff, offs, 0) < 0 || offs[xgrp] < 0
 				|| lbuf_off2pos(xb, beg, o1, r2, o2,
 						soff + offs[xgrp], &xrow, &xoff))
 			ret = xuerr;
@@ -1010,14 +1010,14 @@ static void *ec_substitute(char *loc, char *cmd, char *arg)
 	int beg, end, grp;
 	char *pat, *rep = NULL, *_rep;
 	char *s = arg;
-	rset *rs = xkwdrs;
+	rstr *rs = xkwdrs;
 	int i, first = -1, last;
 	struct lopt *lo;
 	if (ex_vregion(loc, &beg, &end))
 		return xrerr;
 	pat = re_read(&s, 0);
 	if (pat && (*pat || !rs))
-		rs = rset_smake(pat, xic ? REG_ICASE : 0);
+		rs = rstr_make(pat, xic ? REG_ICASE : 0);
 	if (!rs) {
 		free(pat);
 		return xserr;
@@ -1027,11 +1027,11 @@ static void *ec_substitute(char *loc, char *cmd, char *arg)
 		rep = re_read(&s, 0);
 	}
 	free(pat);
-	int offs[rs->nsubc];
+	int offs[rs->rs ? rs->rs->nsubc : 2];
 	for (i = beg; i < end; i++) {
 		char *ln = lbuf_get(xb, i);
 		sbuf *r = NULL;
-		while (rset_find(rs, ln, offs, REG_NEWLINE) >= 0) {
+		while (rstr_find(rs, ln, offs, REG_NEWLINE) >= 0) {
 			if (offs[xgrp] < 0) {
 				ln += offs[1] > 0 ? offs[1] : 1;
 				continue;
@@ -1046,7 +1046,7 @@ static void *ec_substitute(char *loc, char *cmd, char *arg)
 					}
 					_rep++;
 					grp = abs((*_rep - '0') * 2);
-					if (grp + 1 >= rs->nsubc)
+					if (grp + 1 >= (rs->rs ? rs->rs->nsubc : 2))
 						sbuf_chr(r, (unsigned char)*_rep)
 					else if (offs[grp] >= 0)
 						sbuf_mem(r, ln + offs[grp], offs[grp + 1] - offs[grp])
@@ -1077,7 +1077,7 @@ static void *ec_substitute(char *loc, char *cmd, char *arg)
 		lbuf_emark(xb, lo, last, 0);
 	}
 	if (rs != xkwdrs)
-		rset_free(rs);
+		rstr_free(rs);
 	free(rep);
 	return first < 0 ? xuerr : NULL;
 }
@@ -1146,7 +1146,7 @@ static void *ec_glob(char *loc, char *cmd, char *arg)
 {
 	int i, beg, end, not, matched = 0;
 	char *pat, *s = arg;
-	rset *rs;
+	rstr *rs;
 	if (!loc[0] && !xgdep)
 		loc = "%";
 	if (ex_vregion(loc, &beg, &end))
@@ -1154,9 +1154,9 @@ static void *ec_glob(char *loc, char *cmd, char *arg)
 	not = !!strchr(cmd, '!');
 	pat = re_read(&s, 0);
 	if (pat && *pat)
-		rs = rset_smake(pat, xic ? REG_ICASE : 0);
+		rs = rstr_make(pat, xic ? REG_ICASE : 0);
 	else
-		rs = rset_smake(xregs['/'] ? xregs['/']->s : "", xic ? REG_ICASE : 0);
+		rs = rstr_make(xregs['/'] ? xregs['/']->s : "", xic ? REG_ICASE : 0);
 	free(pat);
 	if (!rs)
 		return xserr;
@@ -1166,7 +1166,7 @@ static void *ec_glob(char *loc, char *cmd, char *arg)
 	for (i = beg; i < lbuf_len(xb);) {
 		char *ln = lbuf_get(xb, i);
 		lbuf_s(ln)->grec &= ~xgdep;
-		if (rset_match(rs, ln, REG_NEWLINE) != not) {
+		if (rstr_match(rs, ln, REG_NEWLINE) != not) {
 			matched = 1;
 			xrow = i;
 			if (ex_exec(s))
@@ -1176,7 +1176,7 @@ static void *ec_glob(char *loc, char *cmd, char *arg)
 		while (i < lbuf_len(xb) && !(lbuf_i(xb, i)->grec & xgdep))
 			i++;
 	}
-	rset_free(rs);
+	rstr_free(rs);
 	xgdep /= 2;
 	return matched ? NULL : xuerr;
 }
@@ -1317,10 +1317,10 @@ static void *ec_chdir(char *loc, char *cmd, char *arg)
 
 static void *ec_setincl(char *loc, char *cmd, char *arg)
 {
-	rset_free(fsincl);
+	rstr_free(fsincl);
 	if (!*arg)
 		fsincl = NULL;
-	else if (!(fsincl = rset_smake(arg, xic ? REG_ICASE : 0)))
+	else if (!(fsincl = rstr_make(arg, xic ? REG_ICASE : 0)))
 		return xserr;
 	return NULL;
 }
diff --git a/lbuf.c b/lbuf.c
index e550fa9d..c30b36d4 100644
--- a/lbuf.c
+++ b/lbuf.c
@@ -490,11 +490,11 @@ int lbuf_findchar(struct lbuf *lb, char *cs, int cmd, int n, int *row, int *off)
 	return n != 0;
 }
 
-int lbuf_search(struct lbuf *lb, rset *re, int dir, int beg, int end, int pskip,
+int lbuf_search(struct lbuf *lb, rstr *re, int dir, int beg, int end, int pskip,
 		int nskip, int *r, int *o)
 {
 	int r0 = *r, o0 = *o;
-	int offs[re->nsubc], i = r0;
+	int offs[re->rs ? re->rs->nsubc : 2], i = r0;
 	char *s = lbuf_get(lb, i);
 	int off, g1, g2, _o, step, flg;
 	if (pskip >= 0 && s)
@@ -507,7 +507,7 @@ int lbuf_search(struct lbuf *lb, rset *re, int dir, int beg, int end, int pskip,
 		step = 0;
 		flg = REG_NEWLINE;
 		s = lb->ln[i];
-		while (rset_find(re, s + off, offs, flg) >= 0) {
+		while (rstr_find(re, s + off, offs, flg) >= 0) {
 			flg |= REG_NOTBOL;
 			g1 = offs[xgrp], g2 = offs[xgrp + 1];
 			if (g1 < 0) {
diff --git a/regex.c b/regex.c
index ff88bb41..fc39e70f 100644
--- a/regex.c
+++ b/regex.c
@@ -764,3 +764,143 @@ char *re_read(char **src, int delim)
 	*src = *s ? s + 1 : s;
 	sbufn_ret(sb, sb->s)
 }
+
+/* return zero if a simple pattern is given */
+static int rstr_simple(rstr *rs, char *re, int icase)
+{
+	char *beg;
+	char *end;
+	if (!strcmp(re, "^$"))
+		return 1;
+	rs->lbeg = re[0] == '^';
+	if (rs->lbeg)
+		re++;
+	rs->wbeg = re[0] == '\\' && re[1] == '<';
+	if (rs->wbeg)
+		re += 2;
+	beg = re;
+	while (re[0] && !strchr("\\.*+?[]{}()$", (unsigned char) re[0]))
+		re++;
+	end = re;
+	rs->wend = re[0] == '\\' && re[1] == '>';
+	if (rs->wend)
+		re += 2;
+	rs->lend = re[0] == '$';
+	if (rs->lend)
+		re++;
+	if (!re[0]) {
+		int len = end - beg;
+		rs->len = len;
+		rs->str = emalloc(len + 1);
+		rs->str[len] = '\0';
+		if (icase) {
+			while (--len >= 0)
+				rs->str[len] = tolower((unsigned char)beg[len]);
+		} else
+			memcpy(rs->str, beg, len);
+		return 0;
+	}
+	return 1;
+}
+
+rstr *rstr_make(char *re, int flg)
+{
+	rstr *rs = emalloc(sizeof(*rs));
+	memset(rs, 0, sizeof(*rs));
+	rs->flg = flg;
+	if (rstr_simple(rs, re, flg & REG_ICASE))
+		rs->rs = rset_make(1, &re, flg);
+	if (!rs->rs && !rs->str) {
+		free(rs);
+		return NULL;
+	}
+	return rs;
+}
+
+#define rstr_cmp(gen, wbeg, wend, cmpcase) \
+wbeg wend \
+m = rs->str; t = r; \
+for (; *m && *t; t++, m++) { \
+	if (cmpcase) \
+		goto break##gen; \
+} \
+if (!*m) { \
+	if (grps) { \
+		grps[0] = r - s; \
+		grps[1] = r - s + len; \
+	} \
+	return 0; \
+} \
+break##gen:; \
+
+#define rstr_match1(gen, wbeg, wend, cmpcase, stopcond) \
+{ for (r = beg; stopcond; r++) { \
+	rstr_cmp(2##gen, wbeg, wend, cmpcase) \
+} } \
+
+#define _wbeg if (r > s && (isword(r - 1) || !isword(r))) continue;
+#define _wend if (r[len] && (!isword(r + len - 1) || isword(r + len))) continue;
+
+#define template(gen, cmpcase, stopcond) \
+if (!rs->wbeg && !rs->wend) \
+	rstr_match1(1##gen, /*nop*/, /*nop*/, cmpcase, stopcond) \
+else if (rs->wbeg && !rs->wend) \
+	rstr_match1(2##gen, _wbeg, /*nop*/, cmpcase, stopcond) \
+else if (!rs->wbeg && rs->wend) \
+	rstr_match1(3##gen, /*nop*/, _wend, cmpcase, stopcond) \
+else \
+	rstr_match1(4##gen, _wbeg, _wend, cmpcase, stopcond) \
+
+/* return zero if an occurrence is found */
+int rstr_find(rstr *rs, char *s, int *grps, int flg)
+{
+	int len;
+	char *beg, *end, *r, *t, *m;
+	if (rs->rs)
+		return rset_find(rs->rs, s, grps, flg);
+	flg = rs->flg | flg;
+	if ((rs->lbeg && (flg & REG_NOTBOL)) || (rs->lend && (flg & REG_NOTEOL)))
+		return -1;
+	if (!*s)
+		return -1;
+	len = rs->len;
+	beg = s;
+	if (rs->lbeg || rs->lend || !len) {
+		end = s + strlen(s) - len - (flg & REG_NEWLINE ? 1 : 0);
+		if (end < beg)
+			return -1;
+		if (rs->lend)
+			beg = end;
+		if (rs->lbeg)
+			end = s;
+		if (flg & REG_ICASE) {
+			template(4, tolower((unsigned char) *t) != *m, r <= end)
+		} else {
+			template(3, *t != *m, r <= end)
+		}
+	} else {
+		if (flg & REG_ICASE) {
+			template(2, tolower((unsigned char) *t) != *m, r[len - 1])
+		} else {
+			template(1, *t != *m, r[len - 1])
+		}
+	}
+	return -1;
+}
+
+int rstr_match(rstr *rs, char *s, int flg)
+{
+	if (rs->rs)
+		return re_pikevm(rs->rs->regex, s, NULL, 0, flg);
+	int ret = rstr_find(rs, s, NULL, flg);
+	return ret < 0 ? 0 : 1;
+}
+
+void rstr_free(rstr *rs)
+{
+	if (!rs)
+		return;
+	rset_free(rs->rs);
+	free(rs->str);
+	free(rs);
+}
diff --git a/vi.c b/vi.c
index d133d031..9abb9e21 100644
--- a/vi.c
+++ b/vi.c
@@ -377,7 +377,7 @@ static void vi_regput(int c, const char *s, int lnmode)
 	ex_regput(tolower(c), s, isupper(c));
 }
 
-rset *fsincl;
+rstr *fsincl;
 static int fspos;
 static int fsdir;
 
@@ -416,7 +416,7 @@ void dir_calc(char *path)
 				memcpy(cpath, ptrs[i], pathlen + len);
 				plen[i++] = pathlen + len;
 			} else if (ret >= 0 && S_ISREG(statbuf.st_mode))
-				if (!fsincl || rset_match(fsincl, cpath, 0)) {
+				if (!fsincl || rstr_match(fsincl, cpath, 0)) {
 					sbuf_mem(sb, cpath, (int)(pathlen + len))
 					sbuf_chr(sb, '\n')
 				}
diff --git a/vi.h b/vi.h
index 98f80e03..b79c47e9 100644
--- a/vi.h
+++ b/vi.h
@@ -110,12 +110,24 @@ typedef struct {
 	int nsubc;		/* total sub count */
 	int n;			/* number of regular expressions in this set */
 } rset;
+typedef struct {
+	rset *rs;		/* only for regex patterns */
+	char *str;		/* for simple, non-regex patterns  */
+	int len;		/* str length */
+	int flg;		/* flags */
+	int lbeg, lend;		/* match line beg/end */
+	int wbeg, wend;		/* match word beg/end */
+} rstr;
 rset *rset_make(int n, char **pat, int flg);
 static rset *rset_smake(char *pat, int flg)
 	{ char *ss[1] = {pat}; return rset_make(1, ss, flg); }
 int rset_find(rset *re, char *s, int *grps, int flg);
 int rset_match(rset *rs, char *s, int flg);
 void rset_free(rset *re);
+rstr *rstr_make(char *re, int flg);
+int rstr_find(rstr *rs, char *s, int *grps, int flg);
+int rstr_match(rstr *rs, char *s, int flg);
+void rstr_free(rstr *rs);
 char *re_read(char **src, int delim);
 
 /* lbuf.c: line buffer */
@@ -178,8 +190,9 @@ int lbuf_indents(struct lbuf *lb, int r);
 int lbuf_eol(struct lbuf *lb, int r, int state);
 int lbuf_next(struct lbuf *lb, int dir, int *r, int *o);
 int lbuf_findchar(struct lbuf *lb, char *cs, int cmd, int n, int *r, int *o);
-int lbuf_search(struct lbuf *lb, rset *re, int dir, int beg, int end, int pskip,
+int lbuf_search(struct lbuf *lb, rstr *re, int dir, int beg, int end, int pskip,
 		int nskip, int *r, int *o);
+
 #define lbuf_dedup(lb, str, n) \
 { for (int i = 0; i < lbuf_len(lb);) { \
 	char *s = lbuf_get(lb, i); \
@@ -442,7 +455,7 @@ extern int xsep;
 extern int xesc;
 extern int xexec_dep;
 extern sbuf *xacreg;
-extern rset *xkwdrs;
+extern rstr *xkwdrs;
 extern sbuf *xregs[256];
 extern int xdefreg;
 extern struct buf *bufs;
@@ -481,7 +494,7 @@ void ex_cprint(char *line, char *ft, int r, int c, int left, int flg);
 #define ex_print(line, ft) { RS(2, ex_cprint(line, ft, -1, 0, 0, 1)); }
 void ex_init(char **files, int n);
 void ex_bufpostfix(struct buf *p, int clear);
-int ex_krs(rset **krs, int *dir);
+int ex_krs(rstr **krs, int *dir);
 void ex_krsset(char *kwd, int dir);
 void ex_regesc(sbuf *sb, char *beg, char *end, int ex);
 int ex_edit(const char *path, int len);
@@ -541,5 +554,5 @@ void vi(int init);
 extern int vi_hidch;
 extern int vi_lncol;
 /* filesystem */
-extern rset *fsincl;
+extern rstr *fsincl;
 void dir_calc(char *path);
