#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0003-0010 0013-0014 0016-0037 0102-0104 0107-0110 0112 0115-0116 0120-0122 0124-0132 0136 0177-0377

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

SEP="$(printf '\001')"
ESC="$(printf '\002')"
# Command that handles readability line breaks
LB="0?"
# Phase 1 (search/mark): errors disabled by default,
# DBG1=1 enables error reporting, QF1=1 quits on failure
# OK1: with DBG1=1 also report fallback anchor successes
[ "$DBG1" = "1" ] && OK1= || OK1="0${ESC}${ESC}${ESC}?"
[ "$DBG1" = "1" ] && DBG1= || DBG1="0${ESC}?"
[ "$QF1" = "1" ] && QF1="${ESC}${SEP}vis 2${ESC}${SEP}q!1" || QF1=
# Phase 2 (edits): DBG2=1 disables errors, QF2=1 ignores them
[ "$DBG2" = "1" ] && DBG2="0${ESC}?" || DBG2=
[ "$QF2" = "1" ] && QF2= || QF2="${ESC}${SEP}vis 2${ESC}${SEP}q!1"
# Enters vi at failing code line in this script
# Designed for state inspection mid execution
[ "$INTR" = "1" ] && INTR="${ESC}${SEP}|sc|${ESC}${SEP}vis 2:0reg:e $0:83reg %@/:%f> %@p:&Q:b0:|sc! ${ESC}${ESC}${ESC}${SEP}|:vis 3${ESC}${SEP}q1" || INTR=

# Patch: led.c ren.c uc.c vi.c
EXINIT="|sc! ${ESC}${SEP}|:vis 3${SEP}98reg${SEP}b0${SEP}%ya b${SEP}?%;f> 
int dstrlen\\(const char \\*s, char delim\\)
\\{
	register const char \\*i;
	for \\(i=s; \\*i && \\*i != delim; \\+\\+i\\);
	return i-s;${ESC}${SEP}0${ESC}?${ESC}?${ESC}${SEP}0${ESC}?${ESC}?+2m 0${ESC}${ESC}${ESC}${SEP}1q${ESC}${SEP}%;f> 
int dstrlen\\(const char \\*s, char delim\\)
\\{${ESC}${SEP}1${ESC}?${ESC}?${ESC}${SEP}1${ESC}?${ESC}?+2m 0${ESC}${ESC}${ESC}${SEP}${OK1}p OK led.c:6:a1${SEP}${LB}
${SEP}0;1??!${DBG1:-ya!p${ESC}${SEP}prp${ESC}${SEP}p FAIL led.c:6${ESC}${SEP}pr${INTR}${QF1}}${SEP}${LB}
${SEP}?%;f+ 	register const char \\*i;
	for \\(i=s; \\*i && \\*i != delim; \\+\\+i\\);
	return i-s;
}

static int search\\(const char \\*pattern, int l\\)${ESC}${SEP}0${ESC}?${ESC}?${ESC}${SEP}0${ESC}?${ESC}?+2m 1${ESC}${ESC}${ESC}${SEP}1q${ESC}${SEP}%;f+ 	register const char \\*i;
	for \\(i=s; \\*i && \\*i != delim; \\+\\+i\\);
	return i-s;${ESC}${SEP}1${ESC}?${ESC}?${ESC}${SEP}1${ESC}?${ESC}?+2m 1${ESC}${ESC}${ESC}${SEP}${OK1}p OK led.c:9:a1${SEP}${LB}
${SEP}0;1??!${DBG1:-ya!p${ESC}${SEP}prp${ESC}${SEP}p FAIL led.c:9${ESC}${SEP}pr${INTR}${QF1}}${SEP}${LB}
${SEP}${LB}
${SEP}'0a #ifdef __SSE2__
	const char *i = s;
	/* scalar prefix until 16-byte aligned */
	while (((uintptr_t)i & 15) && *i && *i != delim)
		i++;
	if (!*i || *i == delim)
		return i - s;
	__m128i vd = _mm_set1_epi8(delim);
	__m128i vz = _mm_setzero_si128();
	for (;;) {
		__m128i c = _mm_load_si128((const __m128i *)i);
		int mask = _mm_movemask_epi8(
			_mm_or_si128(_mm_cmpeq_epi8(c, vd), _mm_cmpeq_epi8(c, vz)));
		if (mask)
			return i + __builtin_ctz(mask) - s;
		i += 16;
	}
#else
${SEP}??!${DBG2:-ya!p${ESC}${SEP}prp${ESC}${SEP}p FAIL led.c:6:m0${ESC}${SEP}pr${INTR}${QF2}}${SEP}${LB}
${SEP}'1a #endif
${SEP}??!${DBG2:-ya!p${ESC}${SEP}prp${ESC}${SEP}p FAIL led.c:9:m1${ESC}${SEP}pr${INTR}${QF2}}${SEP}b1${SEP}%ya b${SEP}?%;f> 		rstate->holelen = uc_len\\(ss\\);
		memcpy\\(rstate->nullhole, ss, rstate->holelen\\);
		memset\\(ss, 0, rstate->holelen\\);
	} else
		for \\(n = 0; \\(l = uc_len\\(ss\\)\\); n\\+\\+\\)
			ss \\+= l;${ESC}${SEP}0${ESC}?${ESC}?${ESC}${SEP}0${ESC}?${ESC}?+3m 0${ESC}${ESC}${ESC}${SEP}1q${ESC}${SEP}%;f> 		rstate->holelen = uc_len\\(ss\\);
		memcpy\\(rstate->nullhole, ss, rstate->holelen\\);
		memset\\(ss, 0, rstate->holelen\\);${ESC}${SEP}1${ESC}?${ESC}?${ESC}${SEP}1${ESC}?${ESC}?+3m 0${ESC}${ESC}${ESC}${SEP}${OK1}p OK ren.c:111:a1${ESC}${ESC}${ESC}${SEP}1q${ESC}${SEP}%;f> 	} else
		for \\(n = 0; \\(l = uc_len\\(ss\\)\\); n\\+\\+\\)${ESC}${SEP}2${ESC}?${ESC}?${ESC}${SEP}2${ESC}?${ESC}?m 0${ESC}${ESC}${ESC}${SEP}${OK1}p OK ren.c:111:a2${SEP}${LB}
${SEP}0;1;2??!${DBG1:-ya!p${ESC}${SEP}prp${ESC}${SEP}p FAIL ren.c:111${ESC}${SEP}pr${INTR}${QF1}}${SEP}${LB}
${SEP}?%;f+ 			ss \\+= l;
	unsigned int b = n \\+ 1, c = 2, i;
	int cpos = 0, wid, \\*col;
	int \\*pos = emalloc\\(\\(b \\* 2 \\* sizeof\\(pos\\[0\\]\\)\\) \\+ b \\* sizeof\\(char\\*\\)\\);${ESC}${SEP}0${ESC}?${ESC}?${ESC}${SEP}0${ESC}?${ESC}?m 1${ESC}${ESC}${ESC}${SEP}1q${ESC}${SEP};0${ESC}${SEP}0reg${ESC}${SEP}.,\$f+ ^			ss \\+= l;\$${ESC}${SEP}1${ESC}?${ESC}?${ESC}${SEP}1${ESC}?${ESC}?m 1${ESC}${ESC}${ESC}${SEP}${OK1}p OK ren.c:113:a1${ESC}${ESC}${ESC}${SEP}98reg${ESC}${SEP}98reg${SEP}${LB}
${SEP}0;1??!${DBG1:-ya!p${ESC}${SEP}prp${ESC}${SEP}p FAIL ren.c:113${ESC}${SEP}pr${INTR}${QF1}}${SEP}${LB}
${SEP}${LB}
${SEP}'0,#+1c 	} else {
		n = 0;
#ifdef __SSE2__
		if (utf8_length[0xc0] != 1) {
			__m128i v_mask = _mm_set1_epi8((char)0xc0);
			__m128i v_cont = _mm_set1_epi8((char)0x80);
			__m128i v_zero = _mm_setzero_si128();
			/* align to 16 bytes for safe page-boundary loads */
			while ((uintptr_t)ss & 15) {
				l = uc_len(ss);
				if (!l)
					goto count_done;
				n++;
				ss += l;
			}
			for (;;) {
				__m128i chunk = _mm_load_si128((const __m128i*)ss);
				int null_mask = _mm_movemask_epi8(_mm_cmpeq_epi8(chunk, v_zero));
				__m128i masked = _mm_and_si128(chunk, v_mask);
				int cont_mask = _mm_movemask_epi8(_mm_cmpeq_epi8(masked, v_cont));
				if (null_mask) {
					int end = __builtin_ctz(null_mask);
					int valid = (1 << end) - 1;
					n += __builtin_popcount(~cont_mask & valid);
					ss += end;
					goto count_done;
				}
				n += 16 - __builtin_popcount(cont_mask);
				ss += 16;
			}
		} else
#endif
		for (; (l = uc_len(ss)); n++)
${SEP}??!${DBG2:-ya!p${ESC}${SEP}prp${ESC}${SEP}p FAIL ren.c:111:m0${ESC}${SEP}pr${INTR}${QF2}}${SEP}${LB}
${SEP}'1a count_done:;
	}
${SEP}??!${DBG2:-ya!p${ESC}${SEP}prp${ESC}${SEP}p FAIL ren.c:113:m1${ESC}${SEP}pr${INTR}${QF2}}${SEP}b2${SEP}%ya b${SEP}?%;f> int uc_slen\\(char \\*s\\)
\\{
	int n = 0, l;
	for \\(; \\(l = uc_len\\(s\\)\\); n\\+\\+\\)
		s \\+= l;
	return n;${ESC}${SEP}0${ESC}?${ESC}?${ESC}${SEP}0${ESC}?${ESC}?+2m 0${ESC}${ESC}${ESC}${SEP}1q${ESC}${SEP}%;f> int uc_slen\\(char \\*s\\)
\\{
	int n = 0, l;${ESC}${SEP}1${ESC}?${ESC}?${ESC}${SEP}1${ESC}?${ESC}?+2m 0${ESC}${ESC}${ESC}${SEP}${OK1}p OK uc.c:24:a1${SEP}${LB}
${SEP}0;1??!${DBG1:-ya!p${ESC}${SEP}prp${ESC}${SEP}p FAIL uc.c:24${ESC}${SEP}pr${INTR}${QF1}}${SEP}${LB}
${SEP}${LB}
${SEP}'0a #ifdef __SSE2__
	if (utf8_length[0xc0] != 1) {
		__m128i v_mask = _mm_set1_epi8((char)0xc0);
		__m128i v_cont = _mm_set1_epi8((char)0x80);
		__m128i v_zero = _mm_setzero_si128();
		while ((uintptr_t)s & 15) {
			l = uc_len(s);
			if (!l)
				return n;
			n++;
			s += l;
		}
		for (;;) {
			__m128i chunk = _mm_load_si128((const __m128i*)s);
			int null_mask = _mm_movemask_epi8(_mm_cmpeq_epi8(chunk, v_zero));
			__m128i masked = _mm_and_si128(chunk, v_mask);
			int cont_mask = _mm_movemask_epi8(_mm_cmpeq_epi8(masked, v_cont));
			if (null_mask) {
				int end = __builtin_ctz(null_mask);
				int valid = (1 << end) - 1;
				return n + __builtin_popcount(~cont_mask & valid);
			}
			n += 16 - __builtin_popcount(cont_mask);
			s += 16;
		}
		return n;
	}
#endif
${SEP}??!${DBG2:-ya!p${ESC}${SEP}prp${ESC}${SEP}p FAIL uc.c:24:m0${ESC}${SEP}pr${INTR}${QF2}}${SEP}b3${SEP}%ya b${SEP}?%;f> #include <ctype\\.h>
#include <fcntl\\.h>
#include <stdio\\.h>${ESC}${SEP}0${ESC}?${ESC}?${ESC}${SEP}0${ESC}?${ESC}?m 0${ESC}${ESC}${ESC}${SEP}1q${ESC}${SEP};0${ESC}${SEP}0reg${ESC}${SEP}.,\$f> ^#include <ctype\\.h>\$${ESC}${SEP}1${ESC}?${ESC}?${ESC}${SEP}1${ESC}?${ESC}?m 0${ESC}${ESC}${ESC}${SEP}${OK1}p OK vi.c:0:a1${ESC}${ESC}${ESC}${SEP}98reg${ESC}${SEP}98reg${SEP}${LB}
${SEP}0;1??!${DBG1:-ya!p${ESC}${SEP}prp${ESC}${SEP}p FAIL vi.c:0${ESC}${SEP}pr${INTR}${QF1}}${SEP}${LB}
${SEP}${LB}
${SEP}'0i #ifdef __SSE2__
#include <stdint.h>
#include <emmintrin.h>
#endif
${SEP}??!${DBG2:-ya!p${ESC}${SEP}prp${ESC}${SEP}p FAIL vi.c:0:m0${ESC}${SEP}pr${INTR}${QF2}}${SEP}vis 2${SEP}b0${SEP}w${SEP}b1${SEP}w${SEP}b2${SEP}w${SEP}b3${SEP}w${SEP}q" $VI -e 'led.c' 'ren.c' 'uc.c' 'vi.c'

exit 0
=== PATCH2VI DELTA ===
=== PATCH2VI PATCH ===
diff --git a/led.c b/led.c
index 7178cae0..9938c52f 100644
--- a/led.c
+++ b/led.c
@@ -4,9 +4,28 @@ sbuf *led_attsb;
 
 int dstrlen(const char *s, char delim)
 {
+#ifdef __SSE2__
+	const char *i = s;
+	/* scalar prefix until 16-byte aligned */
+	while (((uintptr_t)i & 15) && *i && *i != delim)
+		i++;
+	if (!*i || *i == delim)
+		return i - s;
+	__m128i vd = _mm_set1_epi8(delim);
+	__m128i vz = _mm_setzero_si128();
+	for (;;) {
+		__m128i c = _mm_load_si128((const __m128i *)i);
+		int mask = _mm_movemask_epi8(
+			_mm_or_si128(_mm_cmpeq_epi8(c, vd), _mm_cmpeq_epi8(c, vz)));
+		if (mask)
+			return i + __builtin_ctz(mask) - s;
+		i += 16;
+	}
+#else
 	register const char *i;
 	for (i=s; *i && *i != delim; ++i);
 	return i-s;
+#endif
 }
 
 static int search(const char *pattern, int l)
diff --git a/ren.c b/ren.c
index 9b4776c8..b9e46ae5 100644
--- a/ren.c
+++ b/ren.c
@@ -108,9 +108,42 @@ ren_state *ren_position(char *s)
 		rstate->holelen = uc_len(ss);
 		memcpy(rstate->nullhole, ss, rstate->holelen);
 		memset(ss, 0, rstate->holelen);
-	} else
-		for (n = 0; (l = uc_len(ss)); n++)
+	} else {
+		n = 0;
+#ifdef __SSE2__
+		if (utf8_length[0xc0] != 1) {
+			__m128i v_mask = _mm_set1_epi8((char)0xc0);
+			__m128i v_cont = _mm_set1_epi8((char)0x80);
+			__m128i v_zero = _mm_setzero_si128();
+			/* align to 16 bytes for safe page-boundary loads */
+			while ((uintptr_t)ss & 15) {
+				l = uc_len(ss);
+				if (!l)
+					goto count_done;
+				n++;
+				ss += l;
+			}
+			for (;;) {
+				__m128i chunk = _mm_load_si128((const __m128i*)ss);
+				int null_mask = _mm_movemask_epi8(_mm_cmpeq_epi8(chunk, v_zero));
+				__m128i masked = _mm_and_si128(chunk, v_mask);
+				int cont_mask = _mm_movemask_epi8(_mm_cmpeq_epi8(masked, v_cont));
+				if (null_mask) {
+					int end = __builtin_ctz(null_mask);
+					int valid = (1 << end) - 1;
+					n += __builtin_popcount(~cont_mask & valid);
+					ss += end;
+					goto count_done;
+				}
+				n += 16 - __builtin_popcount(cont_mask);
+				ss += 16;
+			}
+		} else
+#endif
+		for (; (l = uc_len(ss)); n++)
 			ss += l;
+count_done:;
+	}
 	unsigned int b = n + 1, c = 2, i;
 	int cpos = 0, wid, *col;
 	int *pos = emalloc((b * 2 * sizeof(pos[0])) + b * sizeof(char*));
diff --git a/uc.c b/uc.c
index 875905a8..6d0c30b6 100644
--- a/uc.c
+++ b/uc.c
@@ -22,6 +22,34 @@ unsigned char utf8_length[256] = {
 int uc_slen(char *s)
 {
 	int n = 0, l;
+#ifdef __SSE2__
+	if (utf8_length[0xc0] != 1) {
+		__m128i v_mask = _mm_set1_epi8((char)0xc0);
+		__m128i v_cont = _mm_set1_epi8((char)0x80);
+		__m128i v_zero = _mm_setzero_si128();
+		while ((uintptr_t)s & 15) {
+			l = uc_len(s);
+			if (!l)
+				return n;
+			n++;
+			s += l;
+		}
+		for (;;) {
+			__m128i chunk = _mm_load_si128((const __m128i*)s);
+			int null_mask = _mm_movemask_epi8(_mm_cmpeq_epi8(chunk, v_zero));
+			__m128i masked = _mm_and_si128(chunk, v_mask);
+			int cont_mask = _mm_movemask_epi8(_mm_cmpeq_epi8(masked, v_cont));
+			if (null_mask) {
+				int end = __builtin_ctz(null_mask);
+				int valid = (1 << end) - 1;
+				return n + __builtin_popcount(~cont_mask & valid);
+			}
+			n += 16 - __builtin_popcount(cont_mask);
+			s += 16;
+		}
+		return n;
+	}
+#endif
 	for (; (l = uc_len(s)); n++)
 		s += l;
 	return n;
diff --git a/vi.c b/vi.c
index d133d031..436ea3ca 100644
--- a/vi.c
+++ b/vi.c
@@ -1,3 +1,7 @@
+#ifdef __SSE2__
+#include <stdint.h>
+#include <emmintrin.h>
+#endif
 #include <ctype.h>
 #include <fcntl.h>
 #include <stdio.h>
