#!/bin/sh
# Generated by patch2vi from unified diff
# Separator: '@'
set -e

# Path to nextvi (adjust as needed)
VI=${VI:-vi}

# Verify that VI is nextvi
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi" >&2
    exit 1
fi

# Patch: ex.c
EXINIT="rcm:|sc! @|vis 6@1606a 	signal(SIGINT, SIG_DFL); /* got past init? ok remove ^c */
.
@1605a 	if (stdin_fd) {
		if (i)
			ec_edit(NULL, \"\", \"\");
		i = lbuf_rd(xb, STDIN_FILENO, 0, lbuf_len(xb));
		term_done();
		term_init();
		lbuf_saved(xb, 1);
		if (i)
			ex_print(\"stdin read failed\", msg_ft)
		else
			ec_edit(\"\", NULL, \"\"); /* shebang patch compat */
		close(0);
		if (dup2(stdin_fd, 0) == -1) {
			fprintf(stderr, \"error: %s\\n\", \"dup2\");
			close(stdin_fd);
			exit(1);
		}
	}
.
@1603;10c !n && stdin_fd ? NULL : 
.
@1600a 	int i = n;
.
@1598;19c  + !!stdin_fd
.
@372a 	if (!loc)
		return fd < 0 || rd ? xuerr : NULL;
	ret:
.
@354c 	int fd = 0, len, rd = 0, cd = 0;
	if (!cmd)
		goto ret;
.
@vis 4@wq" $VI -e 'ex.c'

# Patch: term.c
EXINIT="rcm:|sc! @|vis 6@351;11;23c stdin_fd
.
@308;20;21c stdin_fd
.
@164,165c 				read(stdin_fd, ibuf, 1) <= 0) {
			xquit = !isatty(stdin_fd) ? -1 : xquit;
.
@160a 		ufd.fd = stdin_fd;
.
@42;11;12c stdin_fd
.
@33a 	isig = 1;
.
@21,23c 	if (!isig && stdin_fd)
		newtermios.c_lflag &= ~(ICANON);
	else
		newtermios.c_lflag &= ~(ICANON | ISIG | ECHO);
	tcsetattr(stdin_fd, TCSAFLUSH, &newtermios);
	if (!ioctl(stdin_fd, TIOCGWINSZ, &win)) {
.
@19;11;12c stdin_fd
.
@8a int stdin_fd;
static int isig;
.
@vis 4@wq" $VI -e 'term.c'

# Patch: vi.c
EXINIT="rcm:|sc! @|vis 6@1804c 		} else if (!argv[i][1])
			stdin_fd = MAX(0, open(ctermid(NULL), O_RDONLY));
.
@1789a 	sigaction(SIGINT, &sa, NULL);
.
@vis 4@wq" $VI -e 'vi.c'

# Patch: vi.h
EXINIT="rcm:|sc! @|vis 6@540a extern int stdin_fd;
.
@vis 4@wq" $VI -e 'vi.h'
