#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0003-0010 0013-0014 0016-0037 0112 0120-0121 0126 0132 0176-0377

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

# Env switches:
# Phase 1 (search/mark) reports nothing by default
#   DBG1=1 reports failures and which fallback anchor
#   resolved a group, QF1=1 also quits on failure
# Phase 2 (edits) reports and quits by default
#   DBG2=1 silences it, QF2=1 keeps going after an error
# INTR=1 enters vi at the failing code line in this
#   script, for state inspection mid execution

# Body too large for EXINIT/argv: stage it in a file
( : > /tmp/p2vi.$$ ) 2>/dev/null && P2VIF=/tmp/p2vi.$$ || P2VIF=./p2vi.$$
trap 'rm -f "$P2VIF"' EXIT

# Patch: conf.c ex.c led.c vi.h
printf '%s%s%s\n' '|sc! |:vis 3ic 0217reg prFp FAIL %@219pr? %@212214reg ? %@217? %@211216reg ? %@220221reg vis 2q!1211reg ? %@221'\
"${DBG1:+213reg ? %@217? %@210215reg ? %@220}\
${DBG2:+ya!214ya!216}\
${QF1:+210reg vis 2q!1}\
${QF2:+ya!221}\
${INTR:+212reg |sc|vis 2:fr 0:e $0:83reg %@47:%f> 219reg %@219:&Q:b0:|sc! |:vis 3q1}"\
'fr 98b0%ya 98?0?
%f> \(\?:'\''\[0-9]\+\)\|\(\[\.%\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\[0-9]\+\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\)\[ \\t]\*\\
\(\?:\(\[,;]#\?\)\[ \\t]\*\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\
\(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\
\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\
\|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\
\(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",
		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},1??0?
1??+3m 11q0?
%f> \(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\
\|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\
\(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",
		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},2??0?
2??m 1220reg p OK conf.c:297:a22sc %? %@2152sc!1q0?
;0fr.,$f> ^\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\$3??0?
3??m 1220reg p OK conf.c:297:a32sc %? %@2152sc!fr 981qfr 980?
%f> \(\?:'\''\[0-9]\+\)\|\(\[\.%\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\[0-9]\+\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\)\[ \\t]\*\\
\(\?:\(\[,;]#\?\)\[ \\t]\*\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\
\(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\4??0?
4??+3m 1220reg p OK conf.c:297:a42sc %? %@2152sc!1q0?
%f> \|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\
\(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",
		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},5??0?
5??-1m 1220reg p OK conf.c:297:a52sc %? %@2152sc!1q0?
%f> .....0.9].....\....\|.0-9..t.\*...\).\?........%... \\.]\*\[0....\[......\*...\[ ...\*..\|......\\..\\].....\..\)\*...\?..\\.]......\\t..\\
....\[,;...\)....].\(......\(\?....\\.....\\.\\\\..\).....\[.\\..\*.......:.\(..\[\^.\\........\\\.......>.\?.....\\........\.\?.\*...\|.
.....0...\+\).\(.\..........t].....\(.......\+...........\[...].\)..\\....\*..:....]...\|...\[...\\.\\.\|.....\?\)..\\..... ........
\(.....p..a........r\|.....\|......t...\|s.....se...s...\|..de..h...w..]..l.f.\|..m......i...
..@..d.j...\\....,1..\\......}.\?.].........\|p.uh.\?....e\[....!\?\|.\[-\+..tdp....n..i..c..\|.
.\?:..\?.... \\.]...\)\?..!.....\?...\?.r..............\)..............y..!..\?.c...........
......1....Y...., ....RE..R...R....H.....1....,......H., RE, .R1, .Y......\)..6??0?
6??+3m 1220reg p OK conf.c:297:a62sc %? %@2152sc!1q0?
grp 1%f> \(\?:'\''\[0-9]\+\)\|\(\[\.%\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\[0-9]\+\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\)\[ \\t]\*\\.*?
\(\?:\(\[,;]#\?\)\[ \\t]\*\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\.*?
\(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\.*?
(\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\)7??0?
grp 07??m 1220reg p OK conf.c:297:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	\{ac_ft, "\[\^ \\t-/:-@\[-\^\{-~]\+\(\?:\(\\n\$\)\|\\n\)\|\\n\|\(\[\^\\n]\+\(\\n\)\)",
		A\(NA, SYN_BGMK\(RE1\), SYN_BGMK\(AY1\), SYN_BGMK\(AY\)\)},
	\{ac_ft, "\[\^ \\t-/:-@\[-\^\{-~]\+\$\|\(\.\+\$\)", A\(NA, SYN_BGMK\(AY1\)\)},.*(	\{vs_ft, "\.\+", A\(AY1 \| SYN_BD\), 1},)
	\{vs_ft, "\(\^\[\?/]\)\|\(\\\\\\\\\[<>]\|\\\\\(\\\\\?\[:=!<>#]\|\\\\\[\\\\\^\?\(\(\?:\\\\\\\\\.\?\|\[\^\\\\]]\)\*\)]\|\\\\\[\|\[\.\^\$\\\\\(\)\*\+\|\?]\|\\\\\{\(\[0-9]\*\(,\)\?\[0-9]\*\)\?}\?\)\|\\\\\\\\\(\.\)",
		A\(SYN_BD, BL1, WH1, GR1, RE1, WH1, YE\)},8??0?
grp 08??-7m 1220reg p OK conf.c:297:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	\{n_ft, "1\(\[ \\t]\*\[1-9]\[ \\t]\*\)9", A\(RE1, MA1 \| SYN_BD\)},
	\{n_ft, "9\[ \\t]\*\(\[1-9]\[ \\t]\*\)1", A\(RE1, MA1 \| SYN_BD\)},
	\{n_ft, "\[1-9]", A\(RE1\)},.*(	\{vs_ft, "\(\\\\\\\\\)\(\.\)\(\?:\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\[\^\\\\\\\\\\\\]]\)\)\?\|\[\^\\\\\\\\\[\^]\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\.\)\|\\)
\[\^\\\\\\\\\[\^]\\\\\^\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\[\^\\\\\\\\]\)\|\\\\\^\(-\)\[\^\\\\\\\\]",
		A\(GR1 \| SYN_BD \| SYN_ATT, 1, GR1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1\), 2},9??0?
grp 09??-10m 1220reg p OK conf.c:297:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg conf.c:2972sc %? %@2132sc!0?
'\''1s/\|o/|tc|o/??!219reg conf.c:297:m12sc %? %@2142sc!b1%ya 98?0?
%f> int xish;			/\* interactive shell \*/
int xgrp;			/\* regex search group \*/
int xpac;			/\* print autocomplete options \*/
int xmpt;			/\* whether to prompt after printing > 1 lines in vi \*/
int xpr;			/\* ex_cprint register \*/
int xlim = -1;			/\* rendering cutoff for non cursor lines \*/1??0?
1??+2m 11q0?
%f> int xish;			/\* interactive shell \*/
int xgrp;			/\* regex search group \*/
int xpac;			/\* print autocomplete options \*/4??0?
4??+2m 1220reg p OK ex.c:17:a42sc %? %@2152sc!1q0?
grp 1%f> int xish;			/\* interactive shell \*/.*?
int xgrp;			/\* regex search group \*/.*?
(int xpac;			/\* print autocomplete options \*/)7??0?
grp 07??m 1220reg p OK ex.c:17:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> int xshape = 1;			/\* perform letter shaping \*/
int xorder = 1;			/\* change the order of characters \*/
int xts = 8;			/\* number of spaces for tab \*/.*(int xseq = 1;			/\* undo/redo sequence \*/)
int xerr = 1;			/\* error handling -
				bit 1: print errors, bit 2: early return, bit 3: ignore errors \*/8??0?
grp 08??-4m 1220reg p OK ex.c:17:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> int xhlr;			/\* highlight text in reverse direction \*/
int xled = 1;			/\* use the line editor \*/
int xtd = \+1;			/\* current text direction \*/.*(int xquit;			/\* exit if positive, force quit or unwind if negative \*/)
int xrow, xoff, xtop;		/\* current row, column, and top row \*/
int xbufcur;			/\* number of active buffers \*/9??0?
grp 09??-10m 1220reg p OK ex.c:17:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:172sc %? %@2132sc!0?
?0?
%f+ 
EO\(pac\) EO\(pr\) EO\(ai\) EO\(err\) EO\(fr\) EO\(ish\) EO\(ic\) EO\(mpt\)
EO\(rr\) EO\(shape\) EO\(seq\) EO\(td\) EO\(order\) EO\(hll\) EO\(hlw\)
EO\(hlp\) EO\(hlr\) EO\(hl\) EO\(lim\) EO\(led\) EO\(vis\)

_EO\(ts, xts = \*arg \? MAX\(0, eo_val\(arg\)\) : !xts; return NULL;\)
_EO\(grp, xgrp = \(\*arg \? MAX\(0, eo_val\(arg\)\) : !xgrp\) \* 2; return NULL;\)1??0?
1??+3m 21q0?
%f+ EO\(hlp\) EO\(hlr\) EO\(hl\) EO\(lim\) EO\(led\) EO\(vis\)

_EO\(ts, xts = \*arg \? MAX\(0, eo_val\(arg\)\) : !xts; return NULL;\)
_EO\(grp, xgrp = \(\*arg \? MAX\(0, eo_val\(arg\)\) : !xgrp\) \* 2; return NULL;\)2??0?
2??m 2220reg p OK ex.c:1644:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^EO\(hlp\) EO\(hlr\) EO\(hl\) EO\(lim\) EO\(led\) EO\(vis\)$3??0?
3??m 2220reg p OK ex.c:1644:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 
EO\(pac\) EO\(pr\) EO\(ai\) EO\(err\) EO\(fr\) EO\(ish\) EO\(ic\) EO\(mpt\)
EO\(rr\) EO\(shape\) EO\(seq\) EO\(td\) EO\(order\) EO\(hll\) EO\(hlw\)4??0?
4??+3m 2220reg p OK ex.c:1644:a42sc %? %@2152sc!1q0?
%f+ 
_EO\(ts, xts = \*arg \? MAX\(0, eo_val\(arg\)\) : !xts; return NULL;\)
_EO\(grp, xgrp = \(\*arg \? MAX\(0, eo_val\(arg\)\) : !xgrp\) \* 2; return NULL;\)5??0?
5??-1m 2220reg p OK ex.c:1644:a52sc %? %@2152sc!1q0?
%f+ 
..\(.......\(... ...a........r..E..f......ish........ .O\(..t.
.O.r.\) E...ha..\) ..\(s.....O.... .....de.\)...........\(h...
EO...p. ..........\(h.. .O......E.\(.e......vi.\)

..O\(..........\*....................a.g.......ts. ........U....
.....r....g.p.. ..... . M..\(.,.eo............ .xgr...........u.. ...L;.6??0?
6??+3m 2220reg p OK ex.c:1644:a62sc %? %@2152sc!1q0?
grp 1%f+ .*?
EO\(pac\) EO\(pr\) EO\(ai\) EO\(err\) EO\(fr\) EO\(ish\) EO\(ic\) EO\(mpt\).*?
EO\(rr\) EO\(shape\) EO\(seq\) EO\(td\) EO\(order\) EO\(hll\) EO\(hlw\).*?
(EO\(hlp\) EO\(hlr\) EO\(hl\) EO\(lim\) EO\(led\) EO\(vis\))7??0?
grp 07??m 2220reg p OK ex.c:1644:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	return uc_isdigit\(\*arg\) \|\| \(\*arg == '\''-'\'' && uc_isdigit\(arg\[1]\)\) \?
		atoi\(arg\) : \(unsigned char\)\*arg;
}.*(_EO\(left,)
	if \(\*loc\)
		xleft = \(xcols / 2\) \* atoi\(loc\);8??0?
grp 08??-5m 2220reg p OK ex.c:1644:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	}
	return xkwdrs \? NULL : xserr;
}.*(	else if \(\*arg\))
		xleft = atoi\(arg\);
	else if \(lbuf_get\(xb, xrow\)\)9??0?
grp 09??-8m 2220reg p OK ex.c:1644:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg ex.c:16442sc %? %@2132sc!0?
?0?
%f+ 	\{"j", ec_join},
	EO\(ts\),
	EO\(td\),
	EO\(order\),
	EO\(hll\),
	EO\(hlw\),1??0?
1??+2m 31q0?
%f+ 	\{"j", ec_join},
	EO\(ts\),
	EO\(td\),4??0?
4??+2m 3220reg p OK ex.c:1744:a42sc %? %@2152sc!1q0?
grp 1%f+ 	\{"j", ec_join},.*?
	EO\(ts\),.*?
(	EO\(td\),)7??0?
grp 07??m 3220reg p OK ex.c:1744:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	\{"cm", ec_cmap},
	\{"cd", ec_chdir},
	\{"c", ec_insert},.*(	EO\(hlp\),)
	EO\(hlr\),
	EO\(hl\),8??0?
grp 08??-4m 3220reg p OK ex.c:1744:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	\{"ya\+", ec_yank},
	\{"ya", ec_yank},
	\{"cm!", ec_cmap},.*(	EO\(left\),)
	EO\(lim\),
	EO\(led\),9??0?
grp 09??-7m 3220reg p OK ex.c:1744:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:17442sc %? %@2132sc!0?
'\''1i int xtc = 1;			/* tab path completion in the ex prompt */
??!219reg ex.c:17:m12sc %? %@2142sc!0?
'\''2s/s\)/s) EO(tc)/??!219reg ex.c:1644:m22sc %? %@2142sc!0?
'\''3i 	EO(tc),
??!219reg ex.c:1744:m32sc %? %@2142sc!b2%ya 98?0?
%f> static sbuf \*suggestsb;
static sbuf \*acsb;
sbuf \*led_attsb;

int dstrlen\(const char \*s, char delim\)1??0?
1??+1m 11q0?
%f> static sbuf \*suggestsb;
static sbuf \*acsb;4??0?
4??+1m 1220reg p OK led.c:2:a42sc %? %@2152sc!1q0?
grp 1%f> static sbuf \*suggestsb;.*?
(static sbuf \*acsb;)7??0?
grp 07??m 1220reg p OK led.c:2:a72sc %? %@2152sc!0?
1;4;7??!219reg led.c:22sc %? %@2132sc!0?
?0?
%f+ 	return r - s;
}

static void led_printparts\(sbuf \*sb, int pre, int ps,
	char \*post, int postn, int \*poff\)
\{1??0?
1??+2m 21q0?
%f+ 	return r - s;
}

4??0?
4??+2m 2220reg p OK led.c:279:a42sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	kind = r > s \? uc_kind\(r\) : 0;
	while \(r > s && uc_kind\(uc_beg\(s, r - 1\)\) == kind\)
		r = uc_beg\(s, r - 1\);.*(		sbufn_null\(sb\))
		return;
	}8??0?
grp 08??-5m 2220reg p OK led.c:279:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	int kind;
	while \(r > s && uc_isspace\(\*r\)\)
		r = uc_beg\(s, r - 1\);.*(	int dir, off, pos, psn = sb->s_n;)
	sbuf_str\(sb, post\)
	sbufn_null\(sb\)9??0?
grp 09??-8m 2220reg p OK led.c:279:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg led.c:2792sc %? %@2132sc!0?
?0?
%f+ 				exbuf_load\(ex_buf\)
			}
			continue; }
		default:
			if \(c == '\''\\n'\'' \|\| TK_INT\(c\)\)
				return c;1??0?
1??+2m 31q0?
%f+ 				exbuf_load\(ex_buf\)
			}
			continue; }4??0?
4??+2m 3220reg p OK led.c:643:a42sc %? %@2152sc!1q0?
grp 1%f+ 				exbuf_load\(ex_buf\).*?
			}.*?
(			continue; })7??0?
grp 07??m 3220reg p OK led.c:643:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 				exbuf_load\(ex_buf\)
			} else if \(bidx != ex_buf - bufs && bidx < xbufcur\) \{
				ex_buf = bufs \+ bidx;.*(			if \(\(cs = led_read\(kmap, c\)\)\))
				sbuf_str\(sb, cs\)
		}8??0?
grp 08??-4m 3220reg p OK led.c:643:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				if \(ex_buf == tmpex_buf\)
					continue;
				restore\(ex_buf\).*(		is->sug = NULL;)
		is->_sug = NULL;
		if \(ai_max >= 0 && xpac\)9??0?
grp 09??-7m 3220reg p OK led.c:643:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg led.c:6432sc %? %@2132sc!0?
?0?
%f+ 		sbuf_free\(suggestsb\)
		sbuf_free\(acsb\)
	}
}1??0?
1??+2m 41q0?
%f+ 		sbuf_free\(suggestsb\)
		sbuf_free\(acsb\)
	}4??0?
4??+2m 4220reg p OK led.c:734:a42sc %? %@2152sc!1q0?
grp 1%f+ 		sbuf_free\(suggestsb\).*?
		sbuf_free\(acsb\).*?
(	})7??0?
grp 07??m 4220reg p OK led.c:734:a72sc %? %@2152sc!0?
1;4;7??!219reg led.c:7342sc %? %@2132sc!0?
'\''1i static sbuf *compsb;
??!219reg led.c:2:m12sc %? %@2142sc!0?
'\''2i /* complete the path at the end of sb, lst gets the matches; returns their count */
static int led_pathcomp(sbuf *sb, int pre, sbuf *lst)
{
	DIR *dp;
	struct dirent *dirp;
	struct stat st;
	char *base;
	int i, n = 0, wo, bo, blen, mlen = 0;
	sbuf_smake(path, 128)
	for (wo = sb->s_n; wo > pre; wo--)
		if (sb->s[wo-1] == '\'' '\'' || sb->s[wo-1] == '\''\t'\'')
			break;
	for (bo = wo, i = sb->s_n; i > wo; i--)
		if (sb->s[i-1] == '\''/'\'') {
			bo = i;
			break;
		}
	sbuf_mem(path, sb->s + wo, bo - wo)
	sbufn_null(path)
	base = sb->s + bo;
	blen = sb->s_n - bo;
	if (!(dp = opendir(path->s_n ? path->s : "."))) {
		free(path->s);
		return 0;
	}
	while ((dirp = readdir(dp))) {
		if (dirp->d_name[0] == '\''.'\'' && (!dirp->d_name[1] ||
				(dirp->d_name[1] == '\''.'\'' && !dirp->d_name[2])))
			continue;
		if (strncmp(dirp->d_name, base, blen))
			continue;
		if (!n++) {
			sbufn_str(lst, dirp->d_name)
			mlen = lst->s_n;
		} else {
			for (i = 0; i < mlen && lst->s[i] == dirp->d_name[i]; i++);
			mlen = i;
			sbuf_chr(lst, '\'' '\'')
			sbufn_str(lst, dirp->d_name)
		}
	}
	closedir(dp);
	if (n) {
		sbuf_mem(sb, lst->s + blen, mlen - blen)
		if (n == 1) {
			sbufn_str(path, lst->s)
			if (!stat(path->s, &st) && S_ISDIR(st.st_mode))
				sbuf_chr(sb, '\''/'\'')
		}
		sbufn_null(sb)
	}
	free(path->s);
	return n;
}

??!219reg led.c:279:m22sc %? %@2142sc!0?
'\''3i 		case '\''\t'\'':
			if (xtc && ai_max < 0 && sb->s[ps] == '\'':'\'') {
				if (!compsb)
					sbuf_make(compsb, 128)
				sbuf_cut(compsb, 0)
				i = led_pathcomp(sb, pre, compsb);
				if (i > 1 && sb->s_n == len)
					led_info(compsb->s)
				if (i)
					break;
			}
??!219reg led.c:643:m32sc %? %@2142sc!0?
'\''4i 	if (compsb) {
		sbuf_free(compsb)
		compsb = NULL;
	}
??!219reg led.c:734:m42sc %? %@2142sc!b3%ya 98?0?
%f> extern int xish;
extern int xgrp;
extern int xpac;
extern int xmpt;
extern int xpr;
extern int xlim;1??0?
1??+2m 11q0?
%f> extern int xish;
extern int xgrp;
extern int xpac;4??0?
4??+2m 1220reg p OK vi.h:428:a42sc %? %@2152sc!1q0?
grp 1%f> extern int xish;.*?
extern int xgrp;.*?
(extern int xpac;)7??0?
grp 07??m 1220reg p OK vi.h:428:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> extern int xshape;
extern int xorder;
extern int xts;.*(extern int xseq;)
extern int xerr;
extern int xfr;8??0?
grp 08??-4m 1220reg p OK vi.h:428:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> extern int xhlr;
extern int xled;
extern int xtd;.*(extern int xrr;)
/\* global variables \*/
extern int xquit;9??0?
grp 09??-7m 1220reg p OK vi.h:428:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.h:4282sc %? %@2132sc!0?
'\''1i extern int xtc;
??!219reg vi.h:428:m12sc %? %@2142sc!vis 2b0wb1wb2wb3w2q' > "$P2VIF"
EXINIT='%ya 97:? %@97' $VI -e 'conf.c' 'ex.c' 'led.c' 'vi.h' "$P2VIF"

exit 0
=== PATCH2VI DELTA ===
=== PATCH2VI PATCH ===
diff --git a/conf.c b/conf.c
index 70157040..c0453e42 100644
--- a/conf.c
+++ b/conf.c
@@ -294,7 +294,7 @@ return|select|switch|type|var))\\>", A(GR1, BL1 | SYN_BD, YE1)},
 (?:'[0-9]+)|([.%$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*[0-9]+[ \t]*)*(?:[ \t]*\\|(?:[^|\\\\]|\\\\.?)*\\|?[ \t]*)*)[ \t]*\
 (?:([,;]#?)[ \t]*((?:\\|(?:[^|\\\\]|\\\\.?)*\\|?[ \t]*)*(?:(?:<(?:[^<\\\\]|\\\\.?)*<?|>(?:[^>\\\\]|\\\\.?)*>?)|\
 (?:'[0-9]+)|([.$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*([0-9]+)[ \t]*)*(?:[ \t]*\\|(?:[^|\\\\]|\\\\.?)*\\|?)*[ \t]*)*)\
-((pac|pr|ai|ish|err|fr|ic|grp|mpt|rr|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
+((pac|pr|ai|ish|err|fr|ic|grp|mpt|rr|shape|seq|ts|td|tc|order|hl[lwpr]?|left|lim|led|vis)\
 |[@&!dmj]|=\\?{0,1}|\\?{1,2}[?!]?|b[psx]?|p[uh]?|ac|e[f!]?!?|f[-+><tdp]?|inc|i|sc!?|\
 (?:g!?|s)[ \t]?(.)?|q!?|reg?\\+?|rd?|w(?:q!|[q!])?|u[czbd]|x!?|ya[!+]?|cm!?|cd?)?",
 		A(BL1 | SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1)},
diff --git a/ex.c b/ex.c
index 3d5a1721..e8791a14 100644
--- a/ex.c
+++ b/ex.c
@@ -15,6 +15,7 @@ int xts = 8;			/* number of spaces for tab */
 int xish;			/* interactive shell */
 int xgrp;			/* regex search group */
 int xpac;			/* print autocomplete options */
+int xtc = 1;			/* tab path completion in the ex prompt */
 int xmpt;			/* whether to prompt after printing > 1 lines in vi */
 int xpr;			/* ex_cprint register */
 int xlim = -1;			/* rendering cutoff for non cursor lines */
@@ -1641,7 +1642,7 @@ static void *eo_##opt(char *loc, char *cmd, char *arg) { inner }
 
 EO(pac) EO(pr) EO(ai) EO(err) EO(fr) EO(ish) EO(ic) EO(mpt)
 EO(rr) EO(shape) EO(seq) EO(td) EO(order) EO(hll) EO(hlw)
-EO(hlp) EO(hlr) EO(hl) EO(lim) EO(led) EO(vis)
+EO(hlp) EO(hlr) EO(hl) EO(lim) EO(led) EO(vis) EO(tc)
 
 _EO(ts, xts = *arg ? MAX(0, eo_val(arg)) : !xts; return NULL;)
 _EO(grp, xgrp = (*arg ? MAX(0, eo_val(arg)) : !xgrp) * 2; return NULL;)
@@ -1742,6 +1743,7 @@ static struct excmd {
 	{"j", ec_join},
 	EO(ts),
 	EO(td),
+	EO(tc),
 	EO(order),
 	EO(hll),
 	EO(hlw),
diff --git a/led.c b/led.c
index 9eb8e85b..dd1efca5 100644
--- a/led.c
+++ b/led.c
@@ -1,5 +1,6 @@
 static sbuf *suggestsb;
 static sbuf *acsb;
+static sbuf *compsb;
 sbuf *led_attsb;
 
 int dstrlen(const char *s, char delim)
@@ -277,6 +278,61 @@ static int led_lastword(char *s)
 	return r - s;
 }
 
+/* complete the path at the end of sb, lst gets the matches; returns their count */
+static int led_pathcomp(sbuf *sb, int pre, sbuf *lst)
+{
+	DIR *dp;
+	struct dirent *dirp;
+	struct stat st;
+	char *base;
+	int i, n = 0, wo, bo, blen, mlen = 0;
+	sbuf_smake(path, 128)
+	for (wo = sb->s_n; wo > pre; wo--)
+		if (sb->s[wo-1] == ' ' || sb->s[wo-1] == '\t')
+			break;
+	for (bo = wo, i = sb->s_n; i > wo; i--)
+		if (sb->s[i-1] == '/') {
+			bo = i;
+			break;
+		}
+	sbuf_mem(path, sb->s + wo, bo - wo)
+	sbufn_null(path)
+	base = sb->s + bo;
+	blen = sb->s_n - bo;
+	if (!(dp = opendir(path->s_n ? path->s : "."))) {
+		free(path->s);
+		return 0;
+	}
+	while ((dirp = readdir(dp))) {
+		if (dirp->d_name[0] == '.' && (!dirp->d_name[1] ||
+				(dirp->d_name[1] == '.' && !dirp->d_name[2])))
+			continue;
+		if (strncmp(dirp->d_name, base, blen))
+			continue;
+		if (!n++) {
+			sbufn_str(lst, dirp->d_name)
+			mlen = lst->s_n;
+		} else {
+			for (i = 0; i < mlen && lst->s[i] == dirp->d_name[i]; i++);
+			mlen = i;
+			sbuf_chr(lst, ' ')
+			sbufn_str(lst, dirp->d_name)
+		}
+	}
+	closedir(dp);
+	if (n) {
+		sbuf_mem(sb, lst->s + blen, mlen - blen)
+		if (n == 1) {
+			sbufn_str(path, lst->s)
+			if (!stat(path->s, &st) && S_ISDIR(st.st_mode))
+				sbuf_chr(sb, '/')
+		}
+		sbufn_null(sb)
+	}
+	free(path->s);
+	return n;
+}
+
 static void led_printparts(sbuf *sb, int pre, int ps,
 	char *post, int postn, int *poff)
 {
@@ -641,6 +697,17 @@ static int led_line(sbuf *sb, int ps, int pre, char **post, int postn, char **po
 				exbuf_load(ex_buf)
 			}
 			continue; }
+		case '\t':
+			if (xtc && ai_max < 0 && sb->s[ps] == ':') {
+				if (!compsb)
+					sbuf_make(compsb, 128)
+				sbuf_cut(compsb, 0)
+				i = led_pathcomp(sb, pre, compsb);
+				if (i > 1 && sb->s_n == len)
+					led_info(compsb->s)
+				if (i)
+					break;
+			}
 		default:
 			if (c == '\n' || TK_INT(c))
 				return c;
@@ -732,4 +799,8 @@ void led_done(void)
 		sbuf_free(suggestsb)
 		sbuf_free(acsb)
 	}
+	if (compsb) {
+		sbuf_free(compsb)
+		compsb = NULL;
+	}
 }
diff --git a/vi.h b/vi.h
index 5a7e773a..f5b33af3 100644
--- a/vi.h
+++ b/vi.h
@@ -426,6 +426,7 @@ extern int xts;
 extern int xish;
 extern int xgrp;
 extern int xpac;
+extern int xtc;
 extern int xmpt;
 extern int xpr;
 extern int xlim;
