#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0003-0010 0013-0014 0016-0037 0112 0121 0126 0131 0176-0377

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

# Env switches:
# Phase 1 (search/mark) reports nothing by default
#   DBG1=1 reports failures and which fallback anchor
#   resolved a group, QF1=1 also quits on failure
# Phase 2 (edits) reports and quits by default
#   DBG2=1 silences it, QF2=1 keeps going after an error
# INTR=1 enters vi at the failing code line in this
#   script, for state inspection mid execution

# Body too large for EXINIT/argv: stage it in a file
( : > /tmp/p2vi.$$ ) 2>/dev/null && P2VIF=/tmp/p2vi.$$ || P2VIF=./p2vi.$$
trap 'rm -f "$P2VIF"' EXIT

# Patch: Makefile cbuild.sh term.c vi.c vi.h
printf '%s%s%s\n' '|sc! |:vis 3ic 0217reg prFp FAIL %@219pr? %@212214reg ? %@217? %@211216reg ? %@220221reg vis 2q!1211reg ? %@221'\
"${DBG1:+213reg ? %@217? %@210215reg ? %@220}\
${DBG2:+ya!214ya!216}\
${QF1:+210reg vis 2q!1}\
${QF2:+ya!221}\
${INTR:+212reg |sc|vis 2:fr 0:e $0:83reg %@47:%f> 219reg %@219:&Q:b0:|sc! |:vis 3q1}"\
'fr 98b0%ya 98?0?
%f>        -Wno-missing-field-initializers \\
       -Wno-unused-parameter \\
       -Wfatal-errors \\
       \$\{CFLAGS}

CFLAGS \+= -D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE1??0?
1??+2m 11q0?
%f>        -Wno-missing-field-initializers \\
       -Wno-unused-parameter \\
       -Wfatal-errors \\4??0?
4??+2m 1220reg p OK Makefile:9:a42sc %? %@2152sc!1q0?
grp 1%f>        -Wno-missing-field-initializers \\.*?
       -Wno-unused-parameter \\.*?
(       -Wfatal-errors \\)7??0?
grp 07??m 1220reg p OK Makefile:9:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> CFLAGS := \\
       -pedantic -Wall -Wextra \\
       -Wno-implicit-fallthrough \\.*(install: vi)
	mkdir -p "\$\{DESTDIR}\$\{bindir}/"
	cp -f vi "\$\{DESTDIR}\$\{bindir}/vi"8??0?
grp 08??-11m 1220reg p OK Makefile:9:a82sc %? %@2152sc!'\''00?
1;4;7;8??!219reg Makefile:92sc %? %@2132sc!0?
'\''1i        -pthread \
??!219reg Makefile:9:m12sc %? %@2142sc!b1%ya 98?0?
%f> CFLAGS="\\
-pedantic -Wall -Wextra \\
-Wno-implicit-fallthrough \\
-Wno-missing-field-initializers \\
-Wno-unused-parameter \\
-Wno-unused-result \\1??0?
1??+2m 11q0?
%f> CFLAGS="\\
-pedantic -Wall -Wextra \\
-Wno-implicit-fallthrough \\4??0?
4??+2m 1220reg p OK cbuild.sh:45:a42sc %? %@2152sc!1q0?
grp 1%f> CFLAGS="\\.*?
-pedantic -Wall -Wextra \\.*?
(-Wno-implicit-fallthrough \\)7??0?
grp 07??m 1220reg p OK cbuild.sh:45:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> : "\$\{PREFIX:=/usr/local}"
: "\$\{OS:=\$\(uname\)}"
: "\$\{CFLAGS:=-O2}".*(case "\$OS" in)
\*_NT\*\) CFLAGS="\$CFLAGS -D_POSIX_C_SOURCE=200809L" ;;
\*Darwin\*\) CFLAGS="\$CFLAGS -D_POSIX_C_SOURCE=200809L -D_DARWIN_C_SOURCE" ;;8??0?
grp 08??-7m 1220reg p OK cbuild.sh:45:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f>     # shellcheck disable=SC2068 # We want to split elements, but avoid whitespace problems \(`\$\*`\), and also avoid `eval \$\*`
    \$@
}.*(\*Linux\*\) CFLAGS="\$CFLAGS -D_POSIX_C_SOURCE=200809L" ;;)
\*\) CFLAGS="\$CFLAGS -D_DEFAULT_SOURCE" ;;
esac9??0?
grp 09??-10m 1220reg p OK cbuild.sh:45:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg cbuild.sh:452sc %? %@2132sc!0?
'\''1i -pthread \
??!219reg cbuild.sh:45:m12sc %? %@2142sc!b2%ya 98?0?
%f> 		ibuf_cnt = 1;
		ibuf_pos = 0;
	}
	if \(icmd_pos < sizeof\(icmd\)\)
		icmd\[icmd_pos\+\+] = ibuf\[ibuf_pos];
	return ibuf\[ibuf_pos\+\+];1??0?
1??+2m 11q0?
%f> 		ibuf_cnt = 1;
		ibuf_pos = 0;
	}4??0?
4??+2m 1220reg p OK term.c:177:a42sc %? %@2152sc!1q0?
grp 1%f> 		ibuf_cnt = 1;.*?
		ibuf_pos = 0;.*?
(	})7??0?
grp 07??m 1220reg p OK term.c:177:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 			ex_regput\(xrr, buf, 1\);
		}
		ret:.*(/\* return a static string that changes text attributes to att \*/)
char \*term_att\(int att\)
\{8??0?
grp 08??-6m 1220reg p OK term.c:177:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 		} else if \(xrr > 0\) \{
			static char buf\[2];
			buf\[0] = \*ibuf;.*(	if \(att & SYN_MK\))
		return "\\x1b\[m";
	static char buf\[128] = "\\x1b\[";9??0?
grp 09??-9m 1220reg p OK term.c:177:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg term.c:1772sc %? %@2132sc!0?
'\''1i 	vi_rendwait();		/* the queued frame overlaps the read above */
??!219reg term.c:177:m12sc %? %@2142sc!b3%ya 98?0?
%f> #include <sys/stat\.h>
#include <sys/ioctl\.h>
#include <sys/wait\.h>
#include "vi\.h"
#include "conf\.c"
#include "ex\.c"1??0?
1??+2m 11q0?
%f> #include <sys/stat\.h>
#include <sys/ioctl\.h>
#include <sys/wait\.h>4??0?
4??+2m 1220reg p OK vi.c:15:a42sc %? %@2152sc!1q0?
grp 1%f> #include <sys/stat\.h>.*?
#include <sys/ioctl\.h>.*?
(#include <sys/wait\.h>)7??0?
grp 07??m 1220reg p OK vi.c:15:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> #include <poll\.h>
#include <termios\.h>
#include <limits\.h>.*(#include "lbuf\.c")
#include "led\.c"
#include "regex\.c"8??0?
grp 08??-4m 1220reg p OK vi.c:15:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> #include <dirent\.h>
#include <signal\.h>
#include <unistd\.h>.*(#include "ren\.c")
#include "term\.c"
#include "uc\.c"9??0?
grp 09??-7m 1220reg p OK vi.c:15:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.c:152sc %? %@2132sc!0?
?0?
%f+ else if \(xrow >= xtop \+ xrows\) \\
	xtop = xrow - xrows \+ 1; \\

void vi\(int init\)
\{
	char \*ln, \*cs;1??0?
1??+2m 21q0?
%f+ else if \(xrow >= xtop \+ xrows\) \\
	xtop = xrow - xrows \+ 1; \\

4??0?
4??+2m 2220reg p OK vi.c:1166:a42sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	xrow = lbuf_len\(xb\) \? lbuf_len\(xb\) - 1 : 0; \\
if \(xrow < xtop\) \\
	xtop = xrow; \\.*(	int mv, n, k, c;)
	xgrec\+\+;
	if \(init\) \{8??0?
grp 08??-4m 2220reg p OK vi.c:1166:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	\*cs = cmd;
	term_push\(str, cs - str \+ 1\);
}.*(		term_pos\(xrow - xtop, led_pos\(lbuf_get\(xb, xrow\), vi_col\)\);)
	}
	while \(!xquit\) \{9??0?
grp 09??-10m 2220reg p OK vi.c:1166:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg vi.c:11662sc %? %@2132sc!0?
?0?
%f+ 				}
			}
		}
		term_record = 1;
		if \(vi_mod & 1 \|\| xleft != oleft
				\|\| \(vi_lnnum && orow != xrow && !\(vi_lnnum == 2\)\)
				\|\| \(\*vi_word && orow != xrow\)\)
			vi_drawagain\(xtop\);
		else if \(\*vi_word && \(ooff != xoff \|\| vi_mod & 2\)
				&& xrow\+1 < xtop \+ xrows\)
			vi_drawrow\(xrow\+1\);
		else if \(xtop != otop\)
			vi_drawupdate\(otop - xtop\);
		if \(xhll\) \{
			syn_blockhl = -1;
			if \(xrow != orow && orow >= xtop && orow < xtop \+ xrows\)
				if \(!\(vi_mod & 1\)\)
					vi_drawrow\(orow\);
			syn_blockhl = -1;
			syn_reloadft\(syn_addhl\("\^\.\+", 2\), 0\);
			vi_drawrow\(xrow\);
			syn_reloadft\(syn_addhl\(NULL, 2\), 0\);
		} else if \(vi_mod & 2 && !\(vi_mod & 1\)\) \{
			syn_blockhl = -1;
			vi_drawrow\(xrow\);
		}
		if \(vi_status && xmpt < 1\) \{
			xrows -= term_resized != vi_status;
			vi_status = term_resized;
			vc_status\(vi_tsm\);
			if \(xmpt > 0\)
				xmpt = 0;
		}
		term_pos\(xrow - xtop, n \+ vi_lncol\);
		term_commit\(\);
		xb->useq \+= xseq;
	}1??0?
1??+3m 31q0?
%f+ 		term_record = 1;
		if \(vi_mod & 1 \|\| xleft != oleft
				\|\| \(vi_lnnum && orow != xrow && !\(vi_lnnum == 2\)\)
				\|\| \(\*vi_word && orow != xrow\)\)
			vi_drawagain\(xtop\);
		else if \(\*vi_word && \(ooff != xoff \|\| vi_mod & 2\)
				&& xrow\+1 < xtop \+ xrows\)
			vi_drawrow\(xrow\+1\);
		else if \(xtop != otop\)
			vi_drawupdate\(otop - xtop\);
		if \(xhll\) \{
			syn_blockhl = -1;
			if \(xrow != orow && orow >= xtop && orow < xtop \+ xrows\)
				if \(!\(vi_mod & 1\)\)
					vi_drawrow\(orow\);
			syn_blockhl = -1;
			syn_reloadft\(syn_addhl\("\^\.\+", 2\), 0\);
			vi_drawrow\(xrow\);
			syn_reloadft\(syn_addhl\(NULL, 2\), 0\);
		} else if \(vi_mod & 2 && !\(vi_mod & 1\)\) \{
			syn_blockhl = -1;
			vi_drawrow\(xrow\);
		}
		if \(vi_status && xmpt < 1\) \{
			xrows -= term_resized != vi_status;
			vi_status = term_resized;
			vc_status\(vi_tsm\);
			if \(xmpt > 0\)
				xmpt = 0;
		}
		term_pos\(xrow - xtop, n \+ vi_lncol\);
		term_commit\(\);
		xb->useq \+= xseq;
	}2??0?
2??m 3220reg p OK vi.c:1801:a22sc %? %@2152sc!1q0?
%f+ 		term_record = 1;
		if \(vi_mod & 1 \|\| xleft != oleft
				\|\| \(vi_lnnum && orow != xrow && !\(vi_lnnum == 2\)\)
				\|\| \(\*vi_word && orow != xrow\)\)
			vi_drawagain\(xtop\);
		else if \(\*vi_word && \(ooff != xoff \|\| vi_mod & 2\)
				&& xrow\+1 < xtop \+ xrows\)
			vi_drawrow\(xrow\+1\);
		else if \(xtop != otop\)
			vi_drawupdate\(otop - xtop\);
		if \(xhll\) \{
			syn_blockhl = -1;
			if \(xrow != orow && orow >= xtop && orow < xtop \+ xrows\)
				if \(!\(vi_mod & 1\)\)
					vi_drawrow\(orow\);
			syn_blockhl = -1;
			syn_reloadft\(syn_addhl\("\^\.\+", 2\), 0\);
			vi_drawrow\(xrow\);
			syn_reloadft\(syn_addhl\(NULL, 2\), 0\);
		} else if \(vi_mod & 2 && !\(vi_mod & 1\)\) \{
			syn_blockhl = -1;
			vi_drawrow\(xrow\);
		}
		if \(vi_status && xmpt < 1\) \{
			xrows -= term_resized != vi_status;
			vi_status = term_resized;
			vc_status\(vi_tsm\);
			if \(xmpt > 0\)
				xmpt = 0;
		}
		term_pos\(xrow - xtop, n \+ vi_lncol\);
		term_commit\(\);3??0?
3??m 3220reg p OK vi.c:1801:a32sc %? %@2152sc!1q0?
%f+ 				}
			}
		}4??0?
4??+3m 3220reg p OK vi.c:1801:a42sc %? %@2152sc!1q0?
%f+ 		xb->useq \+= xseq;
	}5??0?
5??-32m 3220reg p OK vi.c:1801:a52sc %? %@2152sc!1q0?
%f+ 	....
	...
.	.
..t..m.....r......
		....v..... ..1 \|...l....!......t
	..........ln.......o.......x....&..!\(.i...n.m..=...\)
.	...\|..\*.._wo.d..&...o. !=.xrow..
....i_....a...n\(......
	......i.....i...........o.. !..x... .\|..._... &.2.
	..	.. ..ow\+. ..............\)
..	.i..r.....\(......\).
...........x.op.......p.
....i...a.u.da...o..p ..x.o..;
	.if .x...\)..
		.............. .1.
.	..............ro..&..o.o..>.....p.....r......... ...r.w..
...	.........m.d .....
....	v._...w..w..r.w..
...syn..lo..h. =..1.
...sy.......d.t.s...add....\^\..".........
............w.x.o..;
.........l.adf.\(.y._a.d..\(N...,...,....
... e.se... \(v...o............._m...&......
			s.n_..o.....=...;
.		v....a.......ow.;
	..
.	i...v.....t.. .. x.p..<.....
	..xr.....=..e........e.... ........s;
..	v....a....= .erm....i..d.
		..c_..a..s.vi.tsm\).
...i. \(...... ..
.	.....t = ..
	..
..t..m.p.s\(.r......t..... ...i.l......
..te...c.......;
..xb...s.........q.
	.6??0?
6??+3m 3220reg p OK vi.c:1801:a62sc %? %@2152sc!1q0?
grp 1%f+ 				}.*?
			}.*?
		}.*?
(		term_record = 1;)7??0?
grp 07??m 3220reg p OK vi.c:1801:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 					la\.off = off1;
					sbuf_mem\(led_attsb, &la, sizeof\(la\)\)
					vi_mod \|= row1 == row && orow == xrow \? 2 : 1;.*(			term_chr\('\''\\n'\''\);)
		else
			term_kill\(\);8??0?
grp 08??-37m 3220reg p OK vi.c:1801:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 					la\.att = hls\[k]\.att\[0];
					sbuf_mem\(led_attsb, &la, sizeof\(la\)\)
					la\.s = lbuf_get\(xb, row1\);.*(static void sighandler\(int signo\))
\{
	term_winch\+\+;9??0?
grp 09??-43m 3220reg p OK vi.c:1801:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:18012sc %? %@2132sc!0?
?0?
%f+ 		xb->useq \+= xseq;
	}
	if \(--xgrec == 0\) \{
		term_pos\(xrows - !vi_status, 0\);
		if \(xmpt > 0 && !xpln\)1??0?
1??+1m 41q0?
%f+ 		xb->useq \+= xseq;
	}4??0?
4??+1m 4220reg p OK vi.c:1834:a42sc %? %@2152sc!1q0?
grp 1%f+ 		xb->useq \+= xseq;.*?
(	})7??0?
grp 07??m 4220reg p OK vi.c:1834:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 					la\.off = off1;
					sbuf_mem\(led_attsb, &la, sizeof\(la\)\)
					vi_mod \|= row1 == row && orow == xrow \? 2 : 1;.*(			term_chr\('\''\\n'\''\);)
		else
			term_kill\(\);8??0?
grp 08??-4m 4220reg p OK vi.c:1834:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 					la\.att = hls\[k]\.att\[0];
					sbuf_mem\(led_attsb, &la, sizeof\(la\)\)
					la\.s = lbuf_get\(xb, row1\);.*(static void sighandler\(int signo\))
\{
	term_winch\+\+;9??0?
grp 09??-10m 4220reg p OK vi.c:1834:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.c:18342sc %? %@2132sc!0?
'\''1i #include <pthread.h>
??!219reg vi.c:15:m12sc %? %@2142sc!0?
'\''2i /* the frame the redraw thread paints while the input loop reads keys */
static struct vi_rend {
	pthread_mutex_t mtx;
	pthread_cond_t req;		/* a frame is queued */
	pthread_cond_t done;		/* the queued frame is painted */
	pthread_t tid;
	int on;				/* 1 threaded, -1 pthread_create() failed */
	int busy;			/* a frame is queued or being painted */
	int skip;			/* mod bits of the frames dropped so far */
	int mod;			/* vi_mod when the frame was queued */
	int otop, oleft, orow, ooff;	/* the state the frame draws over */
	int pos;			/* the cursor column of the frame */
} vi_rend = {PTHREAD_MUTEX_INITIALIZER, PTHREAD_COND_INITIALIZER,
		PTHREAD_COND_INITIALIZER};

/* paint one frame; the editor state it reads is frozen until vi_rendwait() */
static void vi_rendframe(struct vi_rend *r)
{
	term_record = 1;
	if (r->mod & 1 || xleft != r->oleft
			|| (vi_lnnum && r->orow != xrow && !(vi_lnnum == 2))
			|| (*vi_word && r->orow != xrow))
		vi_drawagain(xtop);
	else if (*vi_word && (r->ooff != xoff || r->mod & 2)
			&& xrow+1 < xtop + xrows)
		vi_drawrow(xrow+1);
	else if (xtop != r->otop)
		vi_drawupdate(r->otop - xtop);
	if (xhll) {
		syn_blockhl = -1;
		if (xrow != r->orow && r->orow >= xtop && r->orow < xtop + xrows)
			if (!(r->mod & 1))
				vi_drawrow(r->orow);
		syn_blockhl = -1;
		syn_reloadft(syn_addhl("^.+", 2), 0);
		vi_drawrow(xrow);
		syn_reloadft(syn_addhl(NULL, 2), 0);
	} else if (r->mod & 2 && !(r->mod & 1)) {
		syn_blockhl = -1;
		vi_drawrow(xrow);
	}
	if (vi_status && xmpt < 1) {
		xrows -= term_resized != vi_status;
		vi_status = term_resized;
		vc_status(vi_tsm);
		if (xmpt > 0)
			xmpt = 0;
	}
	term_pos(xrow - xtop, r->pos + vi_lncol);
	term_commit();
}

static void *vi_rendloop(void *arg)
{
	struct vi_rend *r = arg;
	sigset_t set;
	sigemptyset(&set);		/* SIGWINCH belongs to the input loop */
	sigaddset(&set, SIGWINCH);
	pthread_sigmask(SIG_BLOCK, &set, NULL);
	pthread_mutex_lock(&r->mtx);
	for (;;) {
		while (!r->busy)
			pthread_cond_wait(&r->req, &r->mtx);
		pthread_mutex_unlock(&r->mtx);
		vi_rendframe(r);
		pthread_mutex_lock(&r->mtx);
		r->busy = 0;
		pthread_cond_signal(&r->done);
	}
	return NULL;
}

/* wait for the queued frame; the editor state is shared until this returns */
void vi_rendwait(void)
{
	struct vi_rend *r = &vi_rend;
	if (r->on != 1)
		return;
	pthread_mutex_lock(&r->mtx);
	while (r->busy)
		pthread_cond_wait(&r->done, &r->mtx);
	pthread_mutex_unlock(&r->mtx);
}

/* whether input is waiting; a frame drawn now is stale before it lands */
static int vi_rendpend(void)
{
	struct pollfd ufd = {STDIN_FILENO, POLLIN};
	return ibuf_pos < ibuf_cnt || poll(&ufd, 1, 0) > 0;
}

/* queue a frame and hand the input loop its thread back */
static void vi_rendpost(int mod, int otop, int oleft, int orow, int ooff, int pos)
{
	struct vi_rend *r = &vi_rend;
	mod |= r->skip;
	if (!xquit && vi_rendpend()) {
		r->skip = mod | 1;
		return;
	}
	r->skip = 0;
	if (!r->on)
		r->on = pthread_create(&r->tid, NULL, vi_rendloop, r) ? -1 : 1;
	pthread_mutex_lock(&r->mtx);
	r->mod = mod;
	r->otop = otop;
	r->oleft = oleft;
	r->orow = orow;
	r->ooff = ooff;
	r->pos = pos;
	r->busy = r->on > 0;
	pthread_cond_signal(&r->req);
	pthread_mutex_unlock(&r->mtx);
	if (r->on < 0)
		vi_rendframe(r);
}

??!219reg vi.c:1166:m22sc %? %@2142sc!0?
'\''3,#+31c 		vi_rendpost(vi_mod, otop, oleft, orow, ooff, n);
??!219reg vi.c:1801:m32sc %? %@2142sc!0?
'\''4i 	vi_rendwait();
??!219reg vi.c:1834:m42sc %? %@2142sc!b4%ya 98?0?
%f> 
/\* vi\.c: main \*/
void vi\(int init\);
extern int vi_hidch;
extern int vi_lncol;
/\* filesystem \*/1??0?
1??+2m 11q0?
%f> 
/\* vi\.c: main \*/
void vi\(int init\);4??0?
4??+2m 1220reg p OK vi.h:547:a42sc %? %@2152sc!1q0?
grp 1%f> .*?
/\* vi\.c: main \*/.*?
(void vi\(int init\);)7??0?
grp 07??m 1220reg p OK vi.h:547:a72sc %? %@2152sc!0?
1;4;7??!219reg vi.h:5472sc %? %@2132sc!0?
'\''1i void vi_rendwait(void);
??!219reg vi.h:547:m12sc %? %@2142sc!vis 2b0wb1wb2wb3wb4w2q' > "$P2VIF"
EXINIT='%ya 97:? %@97' $VI -e 'Makefile' 'cbuild.sh' 'term.c' 'vi.c' 'vi.h' "$P2VIF"

if [ $# -gt 0 ]; then
    export P2VI_PATCH="$P2VI_PATCH ${0##*/}"
    next=$1
    shift
    case $next in /*|./*|../*) "$next" "$@" ;; *) "./$next" "$@" ;; esac
fi

exit 0
=== PATCH2VI PATCH ===
diff --git a/Makefile b/Makefile
index ce76c2f2..4cf746e9 100644
--- a/Makefile
+++ b/Makefile
@@ -7,6 +7,7 @@ CFLAGS := \
        -Wno-missing-field-initializers \
        -Wno-unused-parameter \
        -Wfatal-errors \
+       -pthread \
        ${CFLAGS}
 
 CFLAGS += -D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE
diff --git a/cbuild.sh b/cbuild.sh
index 62d18e99..73510208 100755
--- a/cbuild.sh
+++ b/cbuild.sh
@@ -43,6 +43,7 @@ run() {
 CFLAGS="\
 -pedantic -Wall -Wextra \
 -Wno-implicit-fallthrough \
+-pthread \
 -Wno-missing-field-initializers \
 -Wno-unused-parameter \
 -Wno-unused-result \
diff --git a/term.c b/term.c
index c8861702..05951cb2 100644
--- a/term.c
+++ b/term.c
@@ -175,6 +175,7 @@ int term_read(int winch)
 		ibuf_cnt = 1;
 		ibuf_pos = 0;
 	}
+	vi_rendwait();		/* the queued frame overlaps the read above */
 	if (icmd_pos < sizeof(icmd))
 		icmd[icmd_pos++] = ibuf[ibuf_pos];
 	return ibuf[ibuf_pos++];
diff --git a/vi.c b/vi.c
index c4d07045..d98a38b1 100644
--- a/vi.c
+++ b/vi.c
@@ -13,6 +13,7 @@
 #include <sys/stat.h>
 #include <sys/ioctl.h>
 #include <sys/wait.h>
+#include <pthread.h>
 #include "vi.h"
 #include "conf.c"
 #include "ex.c"
@@ -1164,6 +1165,123 @@ if (xrow < xtop) \
 else if (xrow >= xtop + xrows) \
 	xtop = xrow - xrows + 1; \
 
+/* the frame the redraw thread paints while the input loop reads keys */
+static struct vi_rend {
+	pthread_mutex_t mtx;
+	pthread_cond_t req;		/* a frame is queued */
+	pthread_cond_t done;		/* the queued frame is painted */
+	pthread_t tid;
+	int on;				/* 1 threaded, -1 pthread_create() failed */
+	int busy;			/* a frame is queued or being painted */
+	int skip;			/* mod bits of the frames dropped so far */
+	int mod;			/* vi_mod when the frame was queued */
+	int otop, oleft, orow, ooff;	/* the state the frame draws over */
+	int pos;			/* the cursor column of the frame */
+} vi_rend = {PTHREAD_MUTEX_INITIALIZER, PTHREAD_COND_INITIALIZER,
+		PTHREAD_COND_INITIALIZER};
+
+/* paint one frame; the editor state it reads is frozen until vi_rendwait() */
+static void vi_rendframe(struct vi_rend *r)
+{
+	term_record = 1;
+	if (r->mod & 1 || xleft != r->oleft
+			|| (vi_lnnum && r->orow != xrow && !(vi_lnnum == 2))
+			|| (*vi_word && r->orow != xrow))
+		vi_drawagain(xtop);
+	else if (*vi_word && (r->ooff != xoff || r->mod & 2)
+			&& xrow+1 < xtop + xrows)
+		vi_drawrow(xrow+1);
+	else if (xtop != r->otop)
+		vi_drawupdate(r->otop - xtop);
+	if (xhll) {
+		syn_blockhl = -1;
+		if (xrow != r->orow && r->orow >= xtop && r->orow < xtop + xrows)
+			if (!(r->mod & 1))
+				vi_drawrow(r->orow);
+		syn_blockhl = -1;
+		syn_reloadft(syn_addhl("^.+", 2), 0);
+		vi_drawrow(xrow);
+		syn_reloadft(syn_addhl(NULL, 2), 0);
+	} else if (r->mod & 2 && !(r->mod & 1)) {
+		syn_blockhl = -1;
+		vi_drawrow(xrow);
+	}
+	if (vi_status && xmpt < 1) {
+		xrows -= term_resized != vi_status;
+		vi_status = term_resized;
+		vc_status(vi_tsm);
+		if (xmpt > 0)
+			xmpt = 0;
+	}
+	term_pos(xrow - xtop, r->pos + vi_lncol);
+	term_commit();
+}
+
+static void *vi_rendloop(void *arg)
+{
+	struct vi_rend *r = arg;
+	sigset_t set;
+	sigemptyset(&set);		/* SIGWINCH belongs to the input loop */
+	sigaddset(&set, SIGWINCH);
+	pthread_sigmask(SIG_BLOCK, &set, NULL);
+	pthread_mutex_lock(&r->mtx);
+	for (;;) {
+		while (!r->busy)
+			pthread_cond_wait(&r->req, &r->mtx);
+		pthread_mutex_unlock(&r->mtx);
+		vi_rendframe(r);
+		pthread_mutex_lock(&r->mtx);
+		r->busy = 0;
+		pthread_cond_signal(&r->done);
+	}
+	return NULL;
+}
+
+/* wait for the queued frame; the editor state is shared until this returns */
+void vi_rendwait(void)
+{
+	struct vi_rend *r = &vi_rend;
+	if (r->on != 1)
+		return;
+	pthread_mutex_lock(&r->mtx);
+	while (r->busy)
+		pthread_cond_wait(&r->done, &r->mtx);
+	pthread_mutex_unlock(&r->mtx);
+}
+
+/* whether input is waiting; a frame drawn now is stale before it lands */
+static int vi_rendpend(void)
+{
+	struct pollfd ufd = {STDIN_FILENO, POLLIN};
+	return ibuf_pos < ibuf_cnt || poll(&ufd, 1, 0) > 0;
+}
+
+/* queue a frame and hand the input loop its thread back */
+static void vi_rendpost(int mod, int otop, int oleft, int orow, int ooff, int pos)
+{
+	struct vi_rend *r = &vi_rend;
+	mod |= r->skip;
+	if (!xquit && vi_rendpend()) {
+		r->skip = mod | 1;
+		return;
+	}
+	r->skip = 0;
+	if (!r->on)
+		r->on = pthread_create(&r->tid, NULL, vi_rendloop, r) ? -1 : 1;
+	pthread_mutex_lock(&r->mtx);
+	r->mod = mod;
+	r->otop = otop;
+	r->oleft = oleft;
+	r->orow = orow;
+	r->ooff = ooff;
+	r->pos = pos;
+	r->busy = r->on > 0;
+	pthread_cond_signal(&r->req);
+	pthread_mutex_unlock(&r->mtx);
+	if (r->on < 0)
+		vi_rendframe(r);
+}
+
 void vi(int init)
 {
 	char *ln, *cs;
@@ -1798,40 +1916,10 @@ void vi(int init)
 				}
 			}
 		}
-		term_record = 1;
-		if (vi_mod & 1 || xleft != oleft
-				|| (vi_lnnum && orow != xrow && !(vi_lnnum == 2))
-				|| (*vi_word && orow != xrow))
-			vi_drawagain(xtop);
-		else if (*vi_word && (ooff != xoff || vi_mod & 2)
-				&& xrow+1 < xtop + xrows)
-			vi_drawrow(xrow+1);
-		else if (xtop != otop)
-			vi_drawupdate(otop - xtop);
-		if (xhll) {
-			syn_blockhl = -1;
-			if (xrow != orow && orow >= xtop && orow < xtop + xrows)
-				if (!(vi_mod & 1))
-					vi_drawrow(orow);
-			syn_blockhl = -1;
-			syn_reloadft(syn_addhl("^.+", 2), 0);
-			vi_drawrow(xrow);
-			syn_reloadft(syn_addhl(NULL, 2), 0);
-		} else if (vi_mod & 2 && !(vi_mod & 1)) {
-			syn_blockhl = -1;
-			vi_drawrow(xrow);
-		}
-		if (vi_status && xmpt < 1) {
-			xrows -= term_resized != vi_status;
-			vi_status = term_resized;
-			vc_status(vi_tsm);
-			if (xmpt > 0)
-				xmpt = 0;
-		}
-		term_pos(xrow - xtop, n + vi_lncol);
-		term_commit();
+		vi_rendpost(vi_mod, otop, oleft, orow, ooff, n);
 		xb->useq += xseq;
 	}
+	vi_rendwait();
 	if (--xgrec == 0) {
 		term_pos(xrows - !vi_status, 0);
 		if (xmpt > 0 && !xpln)
diff --git a/vi.h b/vi.h
index e5018fa9..07ec1337 100644
--- a/vi.h
+++ b/vi.h
@@ -545,6 +545,7 @@ char *conf_digraph(int c1, int c2);
 
 /* vi.c: main */
 void vi(int init);
+void vi_rendwait(void);
 extern int vi_hidch;
 extern int vi_lncol;
 /* filesystem */
