#!/bin/sh
# Generated by patch2vi from unified diff
# Available separators: 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0x0b 0x0c 0x0e 0x0f 0x10 0x11 0x12 0x13 0x14 0x15 0x16 0x17 0x18 0x19 0x1a 0x1b 0x1c 0x1d 0x1e 0x1f 0x44 0x47 0x48 0x4a 0x50 0x51 0x5a 0x7f 0x80 0x81 0x82 0x83 0x84 0x85 0x86 0x87 0x88 0x89 0x8a 0x8b 0x8c 0x8d 0x8e 0x8f 0x90 0x91 0x92 0x93 0x94 0x95 0x96 0x97 0x98 0x99 0x9a 0x9b 0x9c 0x9d 0x9e 0x9f 0xa0 0xa1 0xa2 0xa3 0xa4 0xa5 0xa6 0xa7 0xa8 0xa9 0xaa 0xab 0xac 0xad 0xae 0xaf 0xb0 0xb1 0xb2 0xb3 0xb4 0xb5 0xb6 0xb7 0xb8 0xb9 0xba 0xbb 0xbc 0xbd 0xbe 0xbf 0xc0 0xc1 0xc2 0xc3 0xc4 0xc5 0xc6 0xc7 0xc8 0xc9 0xca 0xcb 0xcc 0xcd 0xce 0xcf 0xd0 0xd1 0xd2 0xd3 0xd4 0xd5 0xd6 0xd7 0xd8 0xd9 0xda 0xdb 0xdc 0xdd 0xde 0xdf 0xe0 0xe1 0xe2 0xe3 0xe4 0xe5 0xe6 0xe7 0xe8 0xe9 0xea 0xeb 0xec 0xed 0xee 0xef 0xf0 0xf1 0xf2 0xf3 0xf4 0xf5 0xf6 0xf7 0xf8 0xf9 0xfa 0xfb 0xfc 0xfd 0xfe 0xff
set -e

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

# Path to nextvi (adjust as needed)
VI=${VI:-vi}

# Uncomment to enter interactive vi on patch failure
#DBG="|sc|vis 2:e $0:@Q:q!1"
# Uncomment to skip errors (. = silent nop)
#DBG="."
# Set QF=. to continue despite errors (errors are still printed)
#QF=.

# Verify that VI is nextvi
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi" >&2
    exit 1
fi

# Patch: vi.c
SEP="$(printf '\x01')"
QF=${QF-"$(printf 'vis 2\\\x01q! 1')"}
EXINIT="rcm:|sc! \\\\${SEP}|vis 3${SEP}%f> static int vi_nlword;			/\\\\* new line mode for eEwWbB \\\\*/${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 46\\${SEP}${QF}}${SEP};=
${SEP}.a static int vi_visual;			/* visual mode: 0=off, 'v'=char, 'V'=line */
static int vi_vrow;			/* selection anchor row */
static int vi_voff;			/* selection anchor column */
.
${SEP}.,\$;f> 	ret = func; \\\\\\\\
\\\\} \\\\} \\\\\\\\

${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 127\\${SEP}${QF}}${SEP};=
${SEP}+2a static void vi_visual_attrib(char *s, int row)
{
	if (!vi_visual || !s)
		return;
	int ar = vi_vrow, ao = vi_voff;
	int cr = xrow,   co = xoff;
	if (ar > cr || (ar == cr && ao > co)) {
		swap(&ar, &cr);
		swap(&ao, &co);
	}
	if (row < ar || row > cr)
		return;
	if (!led_attsb)
		sbuf_make(led_attsb, sizeof(led_att) * 16)
	led_att la;
	la.att = SYN_RV;
	la.s   = s;
	ren_state *r = ren_position(s);
	int o_beg, o_end;
	if (vi_visual == 'V') {
		o_beg = 0;
		o_end = r->n - 1;
	} else if (ar == cr) {		/* single row, char visual */
		o_beg = ao; o_end = co;
	} else if (row == ar) {		/* first row: anchor to EOL */
		o_beg = ao; o_end = lbuf_eol(xb, row, 1);
	} else if (row == cr) {		/* last row: 0 to cursor */
		o_beg = 0;  o_end = co;
	} else {			/* middle row: full line */
		o_beg = 0;  o_end = lbuf_eol(xb, row, 1);
	}
	o_beg = MAX(0, MIN(o_beg, r->n - 1));
	o_end = MAX(0, MIN(o_end, r->n - 1));
	for (int o = o_beg; o <= o_end; o++) {
		la.off = o;
		sbuf_mem(led_attsb, &la, (int)sizeof(la))
	}
}

.
${SEP}.,\$;f> 		vi_lncol = dir_context\\\\(s\\\\) < 0 \\\\? 0 : l1;
		memset\\\\(c, ' ', l1 - \\\\(c - tmp\\\\)\\\\);
		c\\\\[l1 - \\\\(c - tmp\\\\)\\\\] = '\\\\\\\\0';${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 194\\${SEP}${QF}}${SEP};=
${SEP}+2a 		vi_visual_attrib(s, row);
.
${SEP}.,\$;f> 		restore\\\\(ftidx\\\\)
		return;
	\\\\}${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 213\\${SEP}${QF}}${SEP};=
${SEP}+2a 	vi_visual_attrib(s, row);
.
${SEP}.,\$;f> 	free\\\\(sb->s\\\\);
\\\\}

${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 965\\${SEP}${QF}}${SEP};=
${SEP}+2a static int vc_visual_op(int cmd)
{
	int r1 = vi_vrow, o1 = vi_voff;
	int r2 = xrow,   o2 = xoff;
	if (r1 > r2 || (r1 == r2 && o1 > o2)) {
		swap(&r1, &r2);
		swap(&o1, &o2);
	}
	int lnmode = (vi_visual == 'V');
	vi_visual = 0;		/* clear before any operation (vi_change re-enters vi()) */
	vi_mod |= 1;
	if (!lnmode) {
		if (o2 < lbuf_eol(xb, r2, 2))
			o2++;		/* include char under cursor, like vc_motion */
		ren_state *r = (ren_state*)lbuf_get(xb, r1);
		r = r ? ren_position((char*)r) : NULL;
		o1 = r ? MAX(0, MIN(o1, r->n)) : 0;
	} else {
		o1 = 0;
		o2 = lbuf_eol(xb, r2, r1 >= r2);
	}
	int mv_before = lbuf_len(xb);
	int key = 0;
	if (cmd == 'y')
		vi_yank(r1, o1, r2, o2, lnmode);
	else if (cmd == 'd')
		vi_delete(r1, o1, r2, o2, lnmode);
	else if (cmd == 'c')
		key = vi_change(r1, o1, r2, o2, lnmode);
	else if (cmd == '~' || cmd == 'u' || cmd == 'U')
		vi_case(r1, o1, r2, o2, lnmode, cmd);
	else if (cmd == '!')
		vi_pipe(r1, r2);
	else if (cmd == '>' || cmd == '<')
		vi_shift(r1, r2, cmd == '>' ? +1 : -1, 1);
	vi_mod |= r1 != r2 || mv_before != lbuf_len(xb) ? 1 : 2;
	return key;
}

.
${SEP}.,\$;f> 				lbuf_mark\\\\(xb, '\`', xrow, ooff\\\\);
			xrow = nrow;
			xoff = noff;${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1239\\${SEP}${QF}}${SEP};=
${SEP}+2a 			if (vi_visual)
				vi_mod |= 1;
.
${SEP}.,\$;f> 				vi_mod \\\\|= 1;
				break;
			case 'u':${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1315\\${SEP}${QF}}${SEP};=
${SEP}+2a 				if (vi_visual) {
					vc_visual_op('u');
					break;
				}
.
${SEP}.,\$;f> 				vi_mod \\\\|= 1;
				break;
			case 'v':${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1364\\${SEP}${QF}}${SEP};=
${SEP}+3,#+79c 				if (vi_visual == 'v') {
					vi_visual = 0;
				} else {
					vi_visual = 'v';
					vi_vrow = xrow;
					vi_voff = xoff;
.
${SEP}.,\$f> 				\\\\}${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1444\\${SEP}${QF}}${SEP};=
${SEP}.a 				vi_mod |= 1;
.
${SEP}.,\$f> 				break;${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1445\\${SEP}${QF}}${SEP};=
${SEP}.a 			case 'U':
				if (vi_visual) {
					vc_visual_op('U');
					break;
				}
				continue;
.
${SEP}.,\$f> 			case 'V':${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1447\\${SEP}${QF}}${SEP};=
${SEP}+1c 				if (vi_visual == 'V') {
					vi_visual = 0;
				} else {
					vi_visual = 'V';
					vi_vrow = xrow;
					vi_voff = xoff;
				}
.
${SEP}.,\$;f> 					goto quit;
				break;
			case 'c':${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1473\\${SEP}${QF}}${SEP};=
${SEP}+2a 				if (vi_visual) {
					k = vc_visual_op('c');
					goto ins;
				}
				/* fall through */
.
${SEP}.,\$f> 			case 'd':${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1474\\${SEP}${QF}}${SEP};=
${SEP}.a 				if (vi_visual) {
					vc_visual_op('d');
					break;
				}
.
${SEP}.,\$;f> 			case '>':
			case '<':
			case TK_CTL\\\\('w'\\\\):${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1498\\${SEP}${QF}}${SEP};=
${SEP}+2a 				if (vi_visual && c != TK_CTL('w')) {
					vc_visual_op(c);
					break;
				}
.
${SEP}.,\$;f> 				\\\\} else if \\\\(k == '~' \\\\|\\\\| k == 'u' \\\\|\\\\| k == 'U'\\\\) \\\\{
					vc_motion\\\\(k\\\\);
					goto rep;${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1617\\${SEP}${QF}}${SEP};=
${SEP}+2a 				} else if (k == '.') {
					vi_mod |= 2;
					while (vi_arg) {
						term_push(\"j\", 1);
						term_push(rep_cmd, rep_len);
						if (strchr(\"iIoOaAsScC\", rep_cmd[0])) {
							term_push(\"0\", 1);
							if (noff)
								vi_argcmd(noff, 'l');
						}
						vi_arg--;
					}
				} else if (k == 'W') {
					vi_nlword = !vi_nlword;
				} else if (k == 'o') {
					ex_command(\"%s/\\\\x0d//g:%s/[ \\\\t]+\$//g\")
					vi_mod |= 1;
				} else if (k == 'I' || k == 'i') {
					vi_mod |= 2;
					char restr[100] = \"%s/^\\\\t/\";
					vi_arg = MIN(vi_arg ? vi_arg : xts, 80);
					if (k == 'I') {
						cmd = restr+6;
						while (vi_arg--)
							*cmd++ = ' ';
						strcpy(cmd, \"/g\");
					} else {
						strcpy(restr, \"%s/^ {\");
						strcpy(itoa(vi_arg, restr+6), \"}/\\\\t/g\");
					}
					ln = vi_enprompt(\":\", restr, &k, &n);
					goto do_excmd;
				} else if (k == 'b' || k == 'v') {
					term_push(k == 'v' ? \":\\\\x01\" : \":\\\\x02\", 2); /* ^a : ^b */
				} else if (k == ';') {
					ln = vi_enprompt(\":\", \"!\", &k, &n);
					goto do_excmd;
				} else if (k == '/') {
					cs = vi_curword(xb, xrow, xoff, vi_arg, 0);
					ln = vi_prompt(\"xkwd:\", vs_ft, cs, &k, &xkmap, &n);
					if (k)
						ex_krsset(ln + n, +1);
					vi_drawmsg_mpt(k && !xkwdrs ? \"syntax error\" : ln)
					free(ln);
					free(cs);
				} else if (k == 't') {
					vi_drawmsg(\"arg2:(0|#)\");
					cs = vi_curword(xb, xrow, xoff, vi_prefix(), 1);
					char buf[cs ? strlen(cs)+30 : 30];
					strcpy(buf, \".,.+\");
					char *buf1 = itoa(vi_arg, buf+4);
					strcat(buf1, \"s/\");
					if (cs) {
						strcat(buf1, cs);
						strcat(buf1, \"/\");
						free(cs);
					}
					ln = vi_enprompt(\":\", buf, &k, &n);
					goto do_excmd;
				} else if (k == 'r') {
					cs = vi_curword(xb, xrow, xoff, vi_arg, 1);
					char buf[cs ? strlen(cs)+30 : 30];
					strcpy(buf, \"%s/\");
					if (cs) {
						strcat(buf, cs);
						strcat(buf, \"/\");
						free(cs);
					}
					ln = vi_enprompt(\":\", buf, &k, &n);
					goto do_excmd;
				} else if (k == 'V') {
					vi_hidch = !vi_hidch;
					vi_mod |= 1;
				} else {
					term_dec()
.
${SEP}.,\$;f> 				term_push\\\\(\"yy\", 2\\\\);
				goto motion;
			case '~':${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1632\\${SEP}${QF}}${SEP};=
${SEP}+2a 				if (vi_visual) {
					vc_visual_op('~');
					break;
				}
.
${SEP}.,\$;f> 				vc_status\\\\(0\\\\);
				vi_mod \\\\|= 1;
				break;${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1695\\${SEP}${QF}}${SEP};=
${SEP}+2a 			case TK_ESC:
				if (vi_visual) {
					vi_visual = 0;
					vi_mod |= 1;
					break;
				}
				continue;
.
${SEP}.,\$;f> 			if \\\\(xmpt > 0\\\\)
				xmpt = 0;
		\\\\}${SEP}??!${DBG:--5,+5p\\${SEP}p FAIL line 1789\\${SEP}${QF}}${SEP};=
${SEP}+2a 		if (vi_visual)
			vi_drawmsg(vi_visual == 'v' ?
				\"-- VISUAL --\" : \"-- VISUAL LINE --\");
.
${SEP}vis 2${SEP}wq" $VI -e 'vi.c'

exit 0
=== PATCH2VI DELTA ===
=== DELTA vi.c ===
--- /tmp/patch2vi_2V71eo_vi.c.diff.orig	2026-02-17 21:50:22.218604414 -0100
+++ /tmp/patch2vi_2V71eo_vi.c.diff	2026-02-17 21:50:48.380431113 -0100
@@ -6,9 +6,7 @@
 #abs
 === SEARCH COMMAND ===
 %;f>
-=== SEARCH PATTERN (offset: 3) ===
-static int vi_status;			/\* rows reserved for permanent status bar \*/
-static int vi_tsm;			/\* type of the status message \*/
+=== SEARCH PATTERN (offset: 1) ===
 static int vi_nlword;			/\* new line mode for eEwWbB \*/
 --- extra (delete to include) ---
 
=== PATCH2VI PATCH ===
diff --git a/vi.c b/vi.c
index bc0eb301..113cfe28 100644
--- a/vi.c
+++ b/vi.c
@@ -44,6 +44,9 @@ static int vi_cndir = 1;		/* ^n direction */
 static int vi_status;			/* rows reserved for permanent status bar */
 static int vi_tsm;			/* type of the status message */
 static int vi_nlword;			/* new line mode for eEwWbB */
+static int vi_visual;			/* visual mode: 0=off, 'v'=char, 'V'=line */
+static int vi_vrow;			/* selection anchor row */
+static int vi_voff;			/* selection anchor column */
 
 void *emalloc(size_t size)
 {
@@ -125,6 +128,45 @@ for (i = 0, ret = 0;; i++) { \
 	ret = func; \
 } } \
 
+static void vi_visual_attrib(char *s, int row)
+{
+	if (!vi_visual || !s)
+		return;
+	int ar = vi_vrow, ao = vi_voff;
+	int cr = xrow,   co = xoff;
+	if (ar > cr || (ar == cr && ao > co)) {
+		swap(&ar, &cr);
+		swap(&ao, &co);
+	}
+	if (row < ar || row > cr)
+		return;
+	if (!led_attsb)
+		sbuf_make(led_attsb, sizeof(led_att) * 16)
+	led_att la;
+	la.att = SYN_RV;
+	la.s   = s;
+	ren_state *r = ren_position(s);
+	int o_beg, o_end;
+	if (vi_visual == 'V') {
+		o_beg = 0;
+		o_end = r->n - 1;
+	} else if (ar == cr) {		/* single row, char visual */
+		o_beg = ao; o_end = co;
+	} else if (row == ar) {		/* first row: anchor to EOL */
+		o_beg = ao; o_end = lbuf_eol(xb, row, 1);
+	} else if (row == cr) {		/* last row: 0 to cursor */
+		o_beg = 0;  o_end = co;
+	} else {			/* middle row: full line */
+		o_beg = 0;  o_end = lbuf_eol(xb, row, 1);
+	}
+	o_beg = MAX(0, MIN(o_beg, r->n - 1));
+	o_end = MAX(0, MIN(o_end, r->n - 1));
+	for (int o = o_beg; o <= o_end; o++) {
+		la.off = o;
+		sbuf_mem(led_attsb, &la, (int)sizeof(la))
+	}
+}
+
 static void vi_drawrow(int row)
 {
 	int l1, i, i1, lnnum = vi_lnnum;
@@ -192,6 +234,7 @@ static void vi_drawrow(int row)
 		vi_lncol = dir_context(s) < 0 ? 0 : l1;
 		memset(c, ' ', l1 - (c - tmp));
 		c[l1 - (c - tmp)] = '\0';
+		vi_visual_attrib(s, row);
 		led_crender(s, row - xtop, l1, xleft, xleft + xcols - l1)
 		preserve(int, syn_blockhl, syn_blockhl = -1;)
 		preserve(int, ftidx,)
@@ -211,6 +254,7 @@ static void vi_drawrow(int row)
 		restore(ftidx)
 		return;
 	}
+	vi_visual_attrib(s, row);
 	led_crender(s, row - xtop, 0, xleft, xleft + xcols)
 	rstate = rstates;
 }
@@ -963,6 +1007,45 @@ static void vi_shift(int r1, int r2, int dir, int count)
 	free(sb->s);
 }
 
+static int vc_visual_op(int cmd)
+{
+	int r1 = vi_vrow, o1 = vi_voff;
+	int r2 = xrow,   o2 = xoff;
+	if (r1 > r2 || (r1 == r2 && o1 > o2)) {
+		swap(&r1, &r2);
+		swap(&o1, &o2);
+	}
+	int lnmode = (vi_visual == 'V');
+	vi_visual = 0;		/* clear before any operation (vi_change re-enters vi()) */
+	vi_mod |= 1;
+	if (!lnmode) {
+		if (o2 < lbuf_eol(xb, r2, 2))
+			o2++;		/* include char under cursor, like vc_motion */
+		ren_state *r = (ren_state*)lbuf_get(xb, r1);
+		r = r ? ren_position((char*)r) : NULL;
+		o1 = r ? MAX(0, MIN(o1, r->n)) : 0;
+	} else {
+		o1 = 0;
+		o2 = lbuf_eol(xb, r2, r1 >= r2);
+	}
+	int mv_before = lbuf_len(xb);
+	int key = 0;
+	if (cmd == 'y')
+		vi_yank(r1, o1, r2, o2, lnmode);
+	else if (cmd == 'd')
+		vi_delete(r1, o1, r2, o2, lnmode);
+	else if (cmd == 'c')
+		key = vi_change(r1, o1, r2, o2, lnmode);
+	else if (cmd == '~' || cmd == 'u' || cmd == 'U')
+		vi_case(r1, o1, r2, o2, lnmode, cmd);
+	else if (cmd == '!')
+		vi_pipe(r1, r2);
+	else if (cmd == '>' || cmd == '<')
+		vi_shift(r1, r2, cmd == '>' ? +1 : -1, 1);
+	vi_mod |= r1 != r2 || mv_before != lbuf_len(xb) ? 1 : 2;
+	return key;
+}
+
 static int vc_motion(int cmd)
 {
 	int r1 = xrow, r2 = xrow;	/* region rows */
@@ -1237,6 +1320,8 @@ void vi(int init)
 				lbuf_mark(xb, '`', xrow, ooff);
 			xrow = nrow;
 			xoff = noff;
+			if (vi_visual)
+				vi_mod |= 1;
 		} else if (mv == 0) {
 			char *cmd;
 			term_dec()
@@ -1313,6 +1398,10 @@ void vi(int init)
 				vi_mod |= 1;
 				break;
 			case 'u':
+				if (vi_visual) {
+					vc_visual_op('u');
+					break;
+				}
 				undo:
 				if (vi_arg >= 0 && !lbuf_undo(xb, &xrow, &xoff)) {
 					vi_mod |= 1;
@@ -1361,90 +1450,29 @@ void vi(int init)
 				vi_mod |= 1;
 				break;
 			case 'v':
-				vi_mod |= 2;
-				k = term_read(0);
-				switch (k) {
-				case '.':
-					while (vi_arg) {
-						term_push("j", 1);
-						term_push(rep_cmd, rep_len);
-						if (strchr("iIoOaAsScC", rep_cmd[0])) {
-							term_push("0", 1);
-							if (noff)
-								vi_argcmd(noff, 'l');
-						}
-						vi_arg--;
-					}
-					break;
-				case 'w':
-					vi_nlword = !vi_nlword;
-					break;
-				case 'o':
-					ex_command("%s/\x0d//g:%s/[ \t]+$//g")
-					vi_mod |= 1;
-					break;
-				case 'I':;
-				case 'i':;
-					char restr[100] = "%s/^\t/";
-					vi_arg = MIN(vi_arg ? vi_arg : xts, 80);
-					if (k == 'I') {
-						cmd = restr+6;
-						while (vi_arg--)
-							*cmd++ = ' ';
-						strcpy(cmd, "/g");
-					} else {
-						strcpy(restr, "%s/^ {");
-						strcpy(itoa(vi_arg, restr+6), "}/\t/g");
-					}
-					ln = vi_enprompt(":", restr, &k, &n);
-					goto do_excmd;
-				case 'b':
-				case 'v':
-					term_push(k == 'v' ? ":\x01" : ":\x02", 2); /* ^a : ^b */
-					break;
-				case ';':
-					ln = vi_enprompt(":", "!", &k, &n);
-					goto do_excmd;
-				case '/':
-					cs = vi_curword(xb, xrow, xoff, vi_arg, 0);
-					ln = vi_prompt("xkwd:", vs_ft, cs, &k, &xkmap, &n);
-					if (k)
-						ex_krsset(ln + n, +1);
-					vi_drawmsg_mpt(k && !xkwdrs ? "syntax error" : ln)
-					free(ln);
-					free(cs);
-					break;
-				case 't': {
-					vi_drawmsg("arg2:(0|#)");
-					cs = vi_curword(xb, xrow, xoff, vi_prefix(), 1);
-					char buf[cs ? strlen(cs)+30 : 30];
-					strcpy(buf, ".,.+");
-					char *buf1 = itoa(vi_arg, buf+4);
-					strcat(buf1, "s/");
-					if (cs) {
-						strcat(buf1, cs);
-						strcat(buf1, "/");
-						free(cs);
-					}
-					ln = vi_enprompt(":", buf, &k, &n);
-					goto do_excmd; }
-				case 'r': {
-					cs = vi_curword(xb, xrow, xoff, vi_arg, 1);
-					char buf[cs ? strlen(cs)+30 : 30];
-					strcpy(buf, "%s/");
-					if (cs) {
-						strcat(buf, cs);
-						strcat(buf, "/");
-						free(cs);
-					}
-					ln = vi_enprompt(":", buf, &k, &n);
-					goto do_excmd; }
-				default:
-					term_dec()
+				if (vi_visual == 'v') {
+					vi_visual = 0;
+				} else {
+					vi_visual = 'v';
+					vi_vrow = xrow;
+					vi_voff = xoff;
 				}
+				vi_mod |= 1;
 				break;
+			case 'U':
+				if (vi_visual) {
+					vc_visual_op('U');
+					break;
+				}
+				continue;
 			case 'V':
-				vi_hidch = !vi_hidch;
+				if (vi_visual == 'V') {
+					vi_visual = 0;
+				} else {
+					vi_visual = 'V';
+					vi_vrow = xrow;
+					vi_voff = xoff;
+				}
 				vi_mod |= 1;
 				break;
 			case TK_CTL('v'):
@@ -1471,7 +1499,16 @@ void vi(int init)
 					goto quit;
 				break;
 			case 'c':
+				if (vi_visual) {
+					k = vc_visual_op('c');
+					goto ins;
+				}
+				/* fall through */
 			case 'd':
+				if (vi_visual) {
+					vc_visual_op('d');
+					break;
+				}
 				k = term_read(0);
 				if (k == 'i') {
 					k = term_read(0);
@@ -1496,6 +1533,10 @@ void vi(int init)
 			case '>':
 			case '<':
 			case TK_CTL('w'):
+				if (vi_visual && c != TK_CTL('w')) {
+					vc_visual_op(c);
+					break;
+				}
 				k = vc_motion(c);
 				if (c == 'c')
 					goto ins;
@@ -1615,6 +1656,81 @@ void vi(int init)
 				} else if (k == '~' || k == 'u' || k == 'U') {
 					vc_motion(k);
 					goto rep;
+				} else if (k == '.') {
+					vi_mod |= 2;
+					while (vi_arg) {
+						term_push("j", 1);
+						term_push(rep_cmd, rep_len);
+						if (strchr("iIoOaAsScC", rep_cmd[0])) {
+							term_push("0", 1);
+							if (noff)
+								vi_argcmd(noff, 'l');
+						}
+						vi_arg--;
+					}
+				} else if (k == 'W') {
+					vi_nlword = !vi_nlword;
+				} else if (k == 'o') {
+					ex_command("%s/\x0d//g:%s/[ \t]+$//g")
+					vi_mod |= 1;
+				} else if (k == 'I' || k == 'i') {
+					vi_mod |= 2;
+					char restr[100] = "%s/^\t/";
+					vi_arg = MIN(vi_arg ? vi_arg : xts, 80);
+					if (k == 'I') {
+						cmd = restr+6;
+						while (vi_arg--)
+							*cmd++ = ' ';
+						strcpy(cmd, "/g");
+					} else {
+						strcpy(restr, "%s/^ {");
+						strcpy(itoa(vi_arg, restr+6), "}/\t/g");
+					}
+					ln = vi_enprompt(":", restr, &k, &n);
+					goto do_excmd;
+				} else if (k == 'b' || k == 'v') {
+					term_push(k == 'v' ? ":\x01" : ":\x02", 2); /* ^a : ^b */
+				} else if (k == ';') {
+					ln = vi_enprompt(":", "!", &k, &n);
+					goto do_excmd;
+				} else if (k == '/') {
+					cs = vi_curword(xb, xrow, xoff, vi_arg, 0);
+					ln = vi_prompt("xkwd:", vs_ft, cs, &k, &xkmap, &n);
+					if (k)
+						ex_krsset(ln + n, +1);
+					vi_drawmsg_mpt(k && !xkwdrs ? "syntax error" : ln)
+					free(ln);
+					free(cs);
+				} else if (k == 't') {
+					vi_drawmsg("arg2:(0|#)");
+					cs = vi_curword(xb, xrow, xoff, vi_prefix(), 1);
+					char buf[cs ? strlen(cs)+30 : 30];
+					strcpy(buf, ".,.+");
+					char *buf1 = itoa(vi_arg, buf+4);
+					strcat(buf1, "s/");
+					if (cs) {
+						strcat(buf1, cs);
+						strcat(buf1, "/");
+						free(cs);
+					}
+					ln = vi_enprompt(":", buf, &k, &n);
+					goto do_excmd;
+				} else if (k == 'r') {
+					cs = vi_curword(xb, xrow, xoff, vi_arg, 1);
+					char buf[cs ? strlen(cs)+30 : 30];
+					strcpy(buf, "%s/");
+					if (cs) {
+						strcat(buf, cs);
+						strcat(buf, "/");
+						free(cs);
+					}
+					ln = vi_enprompt(":", buf, &k, &n);
+					goto do_excmd;
+				} else if (k == 'V') {
+					vi_hidch = !vi_hidch;
+					vi_mod |= 1;
+				} else {
+					term_dec()
 				}
 				break;
 			case 'x':
@@ -1630,6 +1746,10 @@ void vi(int init)
 				term_push("yy", 2);
 				goto motion;
 			case '~':
+				if (vi_visual) {
+					vc_visual_op('~');
+					break;
+				}
 				term_push("g~ ", 3);
 				goto motion;
 			case 'C':
@@ -1693,6 +1813,13 @@ void vi(int init)
 				vc_status(0);
 				vi_mod |= 1;
 				break;
+			case TK_ESC:
+				if (vi_visual) {
+					vi_visual = 0;
+					vi_mod |= 1;
+					break;
+				}
+				continue;
 			default:
 				continue;
 			}
@@ -1787,6 +1914,9 @@ void vi(int init)
 			if (xmpt > 0)
 				xmpt = 0;
 		}
+		if (vi_visual)
+			vi_drawmsg(vi_visual == 'v' ?
+				"-- VISUAL --" : "-- VISUAL LINE --");
 		term_pos(xrow - xtop, n + vi_lncol);
 		term_commit();
 		xb->useq += xseq;
