#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0001-0010 0013-0014 0016-0037 0112 0120-0121 0132 0177-0377

# Pass any argument to use patch(1) instead of nextvi ex commands
if [ -n "$1" ]; then
    sed '1,/^=== PATCH2VI PATCH ===$/d' "$0" | patch -p1 --merge=diff3
    exit $?
fi

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

SEP="$(printf '\001')"
# Command that handles readability line breaks
LB="0?"
# Disable errors
[ "$DBG" = "1" ] && DBG="0\?" || DBG=
# Ignore errors
[ "$QF" = "1" ] && QF= || QF="\\${SEP}vis 2\\${SEP}q!1"
# Enters vi at failing code line in this script
# Designed for state inspection mid execution
[ "$INTR" = "1" ] && INTR="\\${SEP}|sc|\\${SEP}vis 2:e $0:83reg %@/:%f> %@p:&Q:b0:|sc! \\\\\\${SEP}|:vis 3\\${SEP}q1" || INTR=

# Patch: conf.c vi.c
EXINIT="|sc! \\\\${SEP}|:vis 3${SEP}b0${SEP}%;f> 		A\\\\(SYN_BD, BL1, WH1, YE\\\\)\\\\},

	\\\\{bar_ft, \"\\\\^\\\\(\\\\\\\\\"\\\\.\\\\*\\\\\\\\\"\\\\)\\\\.\\\\*\\\\(\\\\\\\\\\\\\\\\\\\\[\\\\[wrf\\\\]\\\\\\\\\\\\\\\\\\\\]\\\\)\\\\.\\\\*\\\\\$\", A\\\\(AY1 \\\\| SYN_BD, BL, RE\\\\)\\\\},${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL conf.c:307\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3${SEP}s/\\\\)\\\\\$/).*\$/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL conf.c:307\\${SEP}pr${INTR}${QF}}${SEP}b1${SEP}%f> static int vi_nlmode;			/\\\\* new line mode for vi regions \\\\*/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:46\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}.a static int vi_visual;			/* visual mode: 0=off, 'v'=char, 'V'=line */
static int vi_vrow;			/* selection anchor row */
static int vi_voff;			/* selection anchor column */
${SEP}.,\$;f> 	ret = func; \\\\\\\\
\\\\} \\\\} \\\\\\\\

${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:127\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a static void vi_visual_attrib(char *s, int row)
{
	if (!vi_visual || !s)
		return;
	int ar = vi_vrow, ao = vi_voff;
	int cr = xrow,   co = xoff;
	if (ar > cr || (ar == cr && ao > co)) {
		swap(&ar, &cr);
		swap(&ao, &co);
	}
	if (row < ar || row > cr)
		return;
	if (!led_attsb)
		sbuf_make(led_attsb, sizeof(led_att) * 16)
	led_att la;
	la.att = SYN_RV;
	la.s = s;
	ren_state *r = ren_position(s);
	int rn1 = r->n - 1;
	int o_beg, o_end;
	if (vi_visual == 'V') {
		o_beg = 0;
		o_end = rn1;
	} else if (vi_visual == 'b') {
		o_beg = MIN(vi_voff, xoff);
		o_end = MAX(vi_voff, xoff);
	} else if (ar == cr) {
		o_beg = ao; o_end = co;
	} else if (row == ar) {
		o_beg = ao; o_end = lbuf_eol(xb, row, 1);
	} else if (row == cr) {
		o_beg = 0;
		o_end = co;
	} else {
		o_beg = 0;
		o_end = lbuf_eol(xb, row, 1);
	}
	o_beg = MAX(0, MIN(o_beg, rn1));
	o_end = MAX(0, MIN(o_end, rn1));
	for (int o = o_beg; o <= o_end; o++) {
		la.off = o;
		sbuf_mem(led_attsb, &la, (int)sizeof(la))
	}
}

${SEP}.,\$;f> 		vi_lncol = dir_context\\\\(s\\\\) < 0 \\\\? 0 : l1;
		memset\\\\(c, ' ', l1 - \\\\(c - tmp\\\\)\\\\);
		c\\\\[l1 - \\\\(c - tmp\\\\)\\\\] = '\\\\\\\\0';${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:193\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 		vi_visual_attrib(s, row);
${SEP}.,\$;f> 		restore\\\\(ftidx\\\\)
		return;
	\\\\}${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:212\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 	vi_visual_attrib(s, row);
${SEP}.,\$;f> 	char cbuf\\\\[8\\\\] = \"\", vi_msg\\\\[512\\\\], \\\\*c;
	col = vi_off2col\\\\(xb, xrow, xoff\\\\);
	col = ren_cursor\\\\(lbuf_get\\\\(xb, xrow\\\\), col\\\\) \\\\+ 1;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:493\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 	char *vs = vi_visual == 'V' ? \"-- VISUAL LINE -- \" :
		   vi_visual == 'b' ? \"-- VISUAL BLOCK -- \" :
		   vi_visual ? \"-- VISUAL -- \" : \"\";
${SEP}.,\$;f> 		c = rstate->chrs\\\\[xoff\\\\];
		uc_code\\\\(cp, c, l\\\\)
		memcpy\\\\(cbuf, c, l\\\\);${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:498\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3${SEP}s/d\"/d %s\"/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:498\\${SEP}pr${INTR}${QF}}${SEP}.,\$f> 			cbuf, cp, cp, cp, l, rstate->wid\\\\[xoff\\\\], c - lbuf_get\\\\(xb, xrow\\\\),${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:500\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+1${SEP}s/l\\\\)/l, vs)/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:500\\${SEP}pr${INTR}${QF}}${SEP}.,\$;f> 	\\\\} else \\\\{
		snprintf\\\\(vi_msg, sizeof\\\\(vi_msg\\\\),${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:503\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2${SEP}s/d\"/d %s\"/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:503\\${SEP}pr${INTR}${QF}}${SEP}.,\$;f> 			xb_path\\\\[0\\\\] \\\\? xb_path : \"unnamed\",
			xb->modified \\\\? \"\\\\* \" : \" \", lbuf_len\\\\(xb\\\\),
			xrow \\\\* 100 / MAX\\\\(1, lbuf_len\\\\(xb\\\\)-1\\\\), xrow\\\\+1, col,${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:507\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3${SEP}s/s\\\\)/s, vs)/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:507\\${SEP}pr${INTR}${QF}}${SEP}.,\$;f> 	free\\\\(sb->s\\\\);
\\\\}

${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:943\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a static int vc_insert(int cmd);

static int vc_block_insert(int vcmd, int r1, int r2, int ci)
{
	int eol = lbuf_eol(xb, r1, 1);
	xrow = r1;
	xoff = MIN(ci, eol);
	char *old_ln = lbuf_get(xb, r1);
	int old_nbytes = old_ln ? lbuf_s(old_ln)->len : 0;
	int off = MIN(ci, eol);
	if (off > 0) {
		char *cp = rstate->chrs[off];
		if (*cp == '\\\\n')
			off--;
	}
	if (vcmd == 'A' && off < rstate->n)
		off++;
	int ins_byte = rstate->chrs[off] - rstate->chrs[0];
	int key = vc_insert(vcmd == 'A' ? 'a' : 'i');
	char *new_ln = lbuf_get(xb, r1);
	int new_nbytes = new_ln ? lbuf_s(new_ln)->len : 0;
	int added = new_nbytes - old_nbytes;
	if (added <= 0)
		return key;
	char *ins_text = new_ln + ins_byte;
	int added_chars = 0;
	for (char *t = ins_text; t < ins_text + added; t += uc_len(t))
		added_chars++;
	for (int r = r1 + 1; r <= r2; r++) {
		char *ln = lbuf_get(xb, r);
		if (!ln)
			continue;
		int n = uc_slen(ln) - 1;	/* index of '\\\\n' = number of content chars */
		int pos;
		if (vcmd == 'I') {
			if (ci > n)		/* line too short: skip */
				continue;
			pos = ci;
		} else {			/* 'A': insert after right edge */
			pos = MIN(ci + 1, n);
		}
		char *p = uc_chr(ln, pos);
		char *nl_p = ln + lbuf_s(ln)->len;	/* pointer to '\\\\n' byte */
		int pre_bytes = p - ln;
		int post_bytes = nl_p - p + 1;		/* bytes from p through '\\\\n' */
		char *new_ln2 = emalloc(pre_bytes + added + post_bytes + 1);
		memcpy(new_ln2, ln, pre_bytes);
		memcpy(new_ln2 + pre_bytes, ins_text, added);
		memcpy(new_ln2 + pre_bytes + added, p, post_bytes);
		new_ln2[pre_bytes + added + post_bytes] = '\\\\0';
		lbuf_edit(xb, new_ln2, r, r + 1, pos, pos + added_chars);
		free(new_ln2);
	}
	vi_mod |= r1 != r2 ? 1 : 2;
	return key;
}

#define VCB_BOUNDS \\\\
	char *ln = lbuf_get(xb, r); \\\\
	if (!ln) continue; \\\\
	n = uc_slen(ln) - 1; \\\\
	left = MIN(c_left, n); \\\\
	right = MIN(c_right, n - 1); \\\\
	bp = uc_chr(ln, left); \\\\
	ep = right >= left ? uc_chr(bp, right - left + 1) : bp; \\\\
	nlp = ln + lbuf_s(ln)->len; \\\\
	if (ep > nlp) ep = nlp

static int vc_block_op(int cmd, int r1, int r2, int c_left, int c_right)
{
	int r, n, left, right;
	char *bp, *ep, *nlp;
	if (cmd == 'y' || cmd == 'd' || cmd == 'c') {
		sbuf_smake(yb, 256)
		for (r = r1; r <= r2; r++) {
			VCB_BOUNDS;
			if (ep > bp)
				sbuf_mem(yb, bp, (int)(ep - bp))
			if ((cmd == 'd' || cmd == 'c') && left <= right && n) {
				int beg_bytes = (int)(bp - ln);
				int rest_bytes = (int)(nlp - ep + 1);
				char *new_ln = emalloc(beg_bytes + rest_bytes + 1);
				memcpy(new_ln, ln, beg_bytes);
				memcpy(new_ln + beg_bytes, ep, rest_bytes);
				new_ln[beg_bytes + rest_bytes] = '\\\\0';
				lbuf_edit(xb, new_ln, r, r + 1, 0, 0);
				free(new_ln);
			}
			sbuf_chr(yb, '\\\\n')
		}
		sbuf_null(yb)
		vi_regput(vi_ybuf, yb->s, 0);
		free(yb->s);
		if (cmd == 'd' || cmd == 'c') {
			xrow = r1;
			xoff = c_left;
		}
		if (cmd == 'c')
			return vc_block_insert('I', r1, r2, c_left);
	} else if (cmd == '~' || cmd == 'u' || cmd == 'U') {
		for (r = r1; r <= r2; r++) {
			VCB_BOUNDS;
			if (left > right || !n)
				continue;
			int total = lbuf_s(ln)->len + 2;
			char *new_ln = emalloc(total);
			memcpy(new_ln, ln, total - 1);
			new_ln[total - 1] = '\\\\0';
			char *p = new_ln + (bp - ln);
			char *pe = new_ln + (ep - ln);
			while (p < pe) {
				int ch = (unsigned char)*p;
				if (ch <= 0x7f) {
					if (cmd == 'u')
						*p = (char)tolower(ch);
					else if (cmd == 'U')
						*p = (char)toupper(ch);
					else
						*p = (char)(islower(ch) ? toupper(ch) : tolower(ch));
				}
				p += uc_len(p);
			}
			lbuf_edit(xb, new_ln, r, r + 1, 0, 0);
			free(new_ln);
		}
	} else if (cmd == '>' || cmd == '<')
		vi_shift(r1, r2, cmd == '>' ? +1 : -1, 1);
	return 0;
}

static int vc_visual_op(int cmd)
{
	int r1 = vi_vrow, o1 = vi_voff;
	int r2 = xrow, o2 = xoff;
	if (r1 > r2 || (r1 == r2 && o1 > o2)) {
		swap(&r1, &r2);
		swap(&o1, &o2);
	}
	int visual = vi_visual;
	int lnmode = visual == 'V';
	vi_visual = 0;
	if (visual == 'b')
		return vc_block_op(cmd, r1, r2, MIN(o1, o2), MAX(o1, o2));
	if (!lnmode) {
		if (o2 < lbuf_eol(xb, r2, 2))
			o2++;		/* include char under cursor, like vc_motion */
		ren_state *r = (ren_state*)lbuf_get(xb, r1);
		r = r ? ren_position((char*)r) : NULL;
		o1 = r ? MAX(0, MIN(o1, r->n)) : 0;
	} else {
		o1 = 0;
		o2 = lbuf_eol(xb, r2, r1 >= r2);
	}
	int key = 0;
	int prevlen = lbuf_len(xb);
	if (cmd == 'y')
		vi_yank(r1, o1, r2, o2, lnmode);
	else if (cmd == 'd')
		vi_delete(r1, o1, r2, o2, lnmode);
	else if (cmd == 'c')
		key = vi_change(r1, o1, r2, o2, lnmode);
	else if (cmd == '~' || cmd == 'u' || cmd == 'U')
		vi_case(r1, o1, r2, o2, lnmode, cmd);
	else if (cmd == '!')
		vi_pipe(r1, r2);
	else if (cmd == '>' || cmd == '<')
		vi_shift(r1, r2, cmd == '>' ? +1 : -1, 1);
	vi_mod |= r1 != r2 || prevlen != lbuf_len(xb) ? 1 : 2;
	return key;
}

${SEP}.,\$;f> 				vi_mod \\\\|= 1;
				break;
			case 'u':${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:1289\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 				if (vi_visual) {
					vc_visual_op('u');
					break;
				}
${SEP}.,\$;f> 				vi_lncol = 0;
				vi_mod \\\\|= 1;
				break;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:1339\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 			case 'U':
				if (vi_visual)
					vc_visual_op('U');
				break;
${SEP}.,\$;f> 					xmpt = 1;
				break;
			case 'c':${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:1462\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 				if (vi_visual) {
					k = vc_visual_op('c');
					goto insert_done;
				}
${SEP}.,\$f> 			case 'd':${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:1463\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}.a 				if (vi_visual) {
					vc_visual_op('d');
					break;
				}
${SEP}.,\$;f> 			case '>':
			case '<':
			case TK_CTL\\\\('w'\\\\):${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:1511\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 				if (vi_visual && c != TK_CTL('w')) {
					vc_visual_op(c);
					break;
				}
${SEP}.,\$;f> 			case 'A':
			case 'o':
			case 'O':${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:1521\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 				if (vi_visual == 'b' && (c == 'I' || c == 'A')) {
					int r1b = MIN(vi_vrow, xrow), r2b = MAX(vi_vrow, xrow);
					int c_left = MIN(vi_voff, xoff), c_right = MAX(vi_voff, xoff);
					vi_visual = 0;
					k = vc_block_insert(c, r1b, r2b, c == 'I' ? c_left : c_right);
					goto insert_done;
				}
${SEP}.,\$;f> 					ex_command\\\\(cmd\\\\)
					restore\\\\(xled\\\\)
					vi_mod \\\\|= 1;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:1640\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+3${SEP}s/\\\\)/) {/${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:1640\\${SEP}pr${INTR}${QF}}${SEP}.,\$f> 					vc_motion\\\\(k\\\\);${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:1641\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}.a 				} else if (k == 'v' || k == 'V' || k == 'b') {
					vi_visual = vi_visual == k ? 0 : k;
					vi_vrow = xrow;
					vi_voff = xoff;
					vi_mod |= 1;
				}
${SEP}.,\$;f> 				term_push\\\\(\"yy\", 2\\\\);
				goto motion;
			case '~':${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:1655\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 				if (vi_visual) {
					vc_visual_op('~');
					break;
				}
${SEP}.,\$;f> 				vc_status\\\\(0\\\\);
				vi_mod \\\\|= 1;
				break;${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:1716\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 			case TK_ESC:
				if (vi_visual) {
					vi_visual = 0;
					vi_mod |= 1;
					break;
				}
				continue;
${SEP}.,\$;f> 				\\\\}
			\\\\}
		\\\\}${SEP}??!${DBG:-ya!p\\${SEP}prp\\${SEP}p FAIL vi.c:1776\\${SEP}pr${INTR}${QF}}${SEP}${LB}
${SEP}+2a 		if (vi_visual)
			vi_mod |= 1;
${SEP}vis 2${SEP}b0${SEP}w${SEP}b1${SEP}w${SEP}q" $VI -e 'conf.c' 'vi.c'

exit 0
=== PATCH2VI DELTA ===
=== DELTA vi.c ===
=== GROUP 1 ===
+static int vi_visual;			/* visual mode: 0=off, 'v'=char, 'V'=line */
+static int vi_vrow;			/* selection anchor row */
+static int vi_voff;			/* selection anchor column */
=== END ===
=== LEVEL 2 ===
=== pre_ctx ===
static int vi_status;			/* permanent status bar */
static int vi_tsm;			/* type of the status message */
static int vi_nlmode;			/* new line mode for vi regions */
=== END ===
=== post_ctx ===

void *emalloc(size_t size)
{
=== END ===
=== pattern ===
static int vi_nlmode;			/\* new line mode for vi regions \*/
=== END ===
=== edit_cmd_rel ===
a static int vi_visual;			/* visual mode: 0=off, 'v'=char, 'V'=line */
static int vi_vrow;			/* selection anchor row */
static int vi_voff;			/* selection anchor column */
=== END ===
=== END ===
=== PATCH2VI PATCH ===
diff --git a/conf.c b/conf.c
index 0d346df9..cdaf95a7 100644
--- a/conf.c
+++ b/conf.c
@@ -304,7 +304,7 @@ return|select|switch|type|var))\\>", A(GR1, BL1 | SYN_BD, YE1)},
 		A(SYN_BD, BL1, WH1, YE)},
 
 	{bar_ft, "^(\".*\").*(\\[[wrf]\\]).*$", A(AY1 | SYN_BD, BL, RE)},
-	{bar_ft, "^<(.+)> (?:[^ ]+ )*([0-9]+L) ([0-9]+W) (S[0-9]+) (O[0-9]+) (C[0-9]+)$",
+	{bar_ft, "^<(.+)> (?:[^ ]+ )*([0-9]+L) ([0-9]+W) (S[0-9]+) (O[0-9]+) (C[0-9]+).*$",
 		A(AY1 | SYN_BD, RE1, BL, YE, MA, CY1, YE1)},
 	{bar_ft, "^(\".*\").* ([0-9]{1,3}%) (L[0-9]+) (C[0-9]+) (B-?[0-9]+)?.*$",
 		A(AY1 | SYN_BD, BL, RE1, BL, YE1, GR)},
diff --git a/vi.c b/vi.c
index 74ffc2d3..08857c69 100644
--- a/vi.c
+++ b/vi.c
@@ -44,6 +44,9 @@ static int vi_cndir = 1;		/* ^n direction */
 static int vi_status;			/* permanent status bar */
 static int vi_tsm;			/* type of the status message */
 static int vi_nlmode;			/* new line mode for vi regions */
+static int vi_visual;			/* visual mode: 0=off, 'v'=char, 'V'=line */
+static int vi_vrow;			/* selection anchor row */
+static int vi_voff;			/* selection anchor column */
 
 void *emalloc(size_t size)
 {
@@ -125,6 +128,51 @@ for (i = 0, ret = 0;; i++) { \
 	ret = func; \
 } } \
 
+static void vi_visual_attrib(char *s, int row)
+{
+	if (!vi_visual || !s)
+		return;
+	int ar = vi_vrow, ao = vi_voff;
+	int cr = xrow,   co = xoff;
+	if (ar > cr || (ar == cr && ao > co)) {
+		swap(&ar, &cr);
+		swap(&ao, &co);
+	}
+	if (row < ar || row > cr)
+		return;
+	if (!led_attsb)
+		sbuf_make(led_attsb, sizeof(led_att) * 16)
+	led_att la;
+	la.att = SYN_RV;
+	la.s = s;
+	ren_state *r = ren_position(s);
+	int rn1 = r->n - 1;
+	int o_beg, o_end;
+	if (vi_visual == 'V') {
+		o_beg = 0;
+		o_end = rn1;
+	} else if (vi_visual == 'b') {
+		o_beg = MIN(vi_voff, xoff);
+		o_end = MAX(vi_voff, xoff);
+	} else if (ar == cr) {
+		o_beg = ao; o_end = co;
+	} else if (row == ar) {
+		o_beg = ao; o_end = lbuf_eol(xb, row, 1);
+	} else if (row == cr) {
+		o_beg = 0;
+		o_end = co;
+	} else {
+		o_beg = 0;
+		o_end = lbuf_eol(xb, row, 1);
+	}
+	o_beg = MAX(0, MIN(o_beg, rn1));
+	o_end = MAX(0, MIN(o_end, rn1));
+	for (int o = o_beg; o <= o_end; o++) {
+		la.off = o;
+		sbuf_mem(led_attsb, &la, (int)sizeof(la))
+	}
+}
+
 static void vi_drawrow(int row)
 {
 	int l1, i, i1, lnnum = vi_lnnum;
@@ -191,6 +239,7 @@ static void vi_drawrow(int row)
 		vi_lncol = dir_context(s) < 0 ? 0 : l1;
 		memset(c, ' ', l1 - (c - tmp));
 		c[l1 - (c - tmp)] = '\0';
+		vi_visual_attrib(s, row);
 		led_crender(s, row - xtop, l1, xleft, xleft + xcols - l1)
 		preserve(int, syn_blockhl, syn_blockhl = -1;)
 		preserve(int, ftidx,)
@@ -210,6 +259,7 @@ static void vi_drawrow(int row)
 		restore(ftidx)
 		return;
 	}
+	vi_visual_attrib(s, row);
 	led_crender(s, row - xtop, 0, xleft, xleft + xcols)
 	rstate = rstates;
 }
@@ -491,20 +541,23 @@ static void vc_status(int type)
 	char cbuf[8] = "", vi_msg[512], *c;
 	col = vi_off2col(xb, xrow, xoff);
 	col = ren_cursor(lbuf_get(xb, xrow), col) + 1;
+	char *vs = vi_visual == 'V' ? "-- VISUAL LINE -- " :
+		   vi_visual == 'b' ? "-- VISUAL BLOCK -- " :
+		   vi_visual ? "-- VISUAL -- " : "";
 	if (type && lbuf_get(xb, xrow)) {
 		c = rstate->chrs[xoff];
 		uc_code(cp, c, l)
 		memcpy(cbuf, c, l);
-		snprintf(vi_msg, sizeof(vi_msg), "<%s> 0x%x 0%o %u %dL %dW S%td O%d C%d",
+		snprintf(vi_msg, sizeof(vi_msg), "<%s> 0x%x 0%o %u %dL %dW S%td O%d C%d %s",
 			cbuf, cp, cp, cp, l, rstate->wid[xoff], c - lbuf_get(xb, xrow),
-			xoff, col);
+			xoff, col, vs);
 	} else {
 		snprintf(vi_msg, sizeof(vi_msg),
-			"\"%s\"%s%dL %d%% L%d C%d B%td",
+			"\"%s\"%s%dL %d%% L%d C%d B%td %s",
 			xb_path[0] ? xb_path : "unnamed",
 			xb->modified ? "* " : " ", lbuf_len(xb),
 			xrow * 100 / MAX(1, lbuf_len(xb)-1), xrow+1, col,
-			istempbuf(ex_buf) ? tempbufs - ex_buf - 1 : ex_buf - bufs);
+			istempbuf(ex_buf) ? tempbufs - ex_buf - 1 : ex_buf - bufs, vs);
 	}
 	vi_drawmsg_mpt(vi_msg)
 }
@@ -941,6 +994,177 @@ static void vi_shift(int r1, int r2, int dir, int count)
 	free(sb->s);
 }
 
+static int vc_insert(int cmd);
+
+static int vc_block_insert(int vcmd, int r1, int r2, int ci)
+{
+	int eol = lbuf_eol(xb, r1, 1);
+	xrow = r1;
+	xoff = MIN(ci, eol);
+	char *old_ln = lbuf_get(xb, r1);
+	int old_nbytes = old_ln ? lbuf_s(old_ln)->len : 0;
+	int off = MIN(ci, eol);
+	if (off > 0) {
+		char *cp = rstate->chrs[off];
+		if (*cp == '\n')
+			off--;
+	}
+	if (vcmd == 'A' && off < rstate->n)
+		off++;
+	int ins_byte = rstate->chrs[off] - rstate->chrs[0];
+	int key = vc_insert(vcmd == 'A' ? 'a' : 'i');
+	char *new_ln = lbuf_get(xb, r1);
+	int new_nbytes = new_ln ? lbuf_s(new_ln)->len : 0;
+	int added = new_nbytes - old_nbytes;
+	if (added <= 0)
+		return key;
+	char *ins_text = new_ln + ins_byte;
+	int added_chars = 0;
+	for (char *t = ins_text; t < ins_text + added; t += uc_len(t))
+		added_chars++;
+	for (int r = r1 + 1; r <= r2; r++) {
+		char *ln = lbuf_get(xb, r);
+		if (!ln)
+			continue;
+		int n = uc_slen(ln) - 1;	/* index of '\n' = number of content chars */
+		int pos;
+		if (vcmd == 'I') {
+			if (ci > n)		/* line too short: skip */
+				continue;
+			pos = ci;
+		} else {			/* 'A': insert after right edge */
+			pos = MIN(ci + 1, n);
+		}
+		char *p = uc_chr(ln, pos);
+		char *nl_p = ln + lbuf_s(ln)->len;	/* pointer to '\n' byte */
+		int pre_bytes = p - ln;
+		int post_bytes = nl_p - p + 1;		/* bytes from p through '\n' */
+		char *new_ln2 = emalloc(pre_bytes + added + post_bytes + 1);
+		memcpy(new_ln2, ln, pre_bytes);
+		memcpy(new_ln2 + pre_bytes, ins_text, added);
+		memcpy(new_ln2 + pre_bytes + added, p, post_bytes);
+		new_ln2[pre_bytes + added + post_bytes] = '\0';
+		lbuf_edit(xb, new_ln2, r, r + 1, pos, pos + added_chars);
+		free(new_ln2);
+	}
+	vi_mod |= r1 != r2 ? 1 : 2;
+	return key;
+}
+
+#define VCB_BOUNDS \
+	char *ln = lbuf_get(xb, r); \
+	if (!ln) continue; \
+	n = uc_slen(ln) - 1; \
+	left = MIN(c_left, n); \
+	right = MIN(c_right, n - 1); \
+	bp = uc_chr(ln, left); \
+	ep = right >= left ? uc_chr(bp, right - left + 1) : bp; \
+	nlp = ln + lbuf_s(ln)->len; \
+	if (ep > nlp) ep = nlp
+
+static int vc_block_op(int cmd, int r1, int r2, int c_left, int c_right)
+{
+	int r, n, left, right;
+	char *bp, *ep, *nlp;
+	if (cmd == 'y' || cmd == 'd' || cmd == 'c') {
+		sbuf_smake(yb, 256)
+		for (r = r1; r <= r2; r++) {
+			VCB_BOUNDS;
+			if (ep > bp)
+				sbuf_mem(yb, bp, (int)(ep - bp))
+			if ((cmd == 'd' || cmd == 'c') && left <= right && n) {
+				int beg_bytes = (int)(bp - ln);
+				int rest_bytes = (int)(nlp - ep + 1);
+				char *new_ln = emalloc(beg_bytes + rest_bytes + 1);
+				memcpy(new_ln, ln, beg_bytes);
+				memcpy(new_ln + beg_bytes, ep, rest_bytes);
+				new_ln[beg_bytes + rest_bytes] = '\0';
+				lbuf_edit(xb, new_ln, r, r + 1, 0, 0);
+				free(new_ln);
+			}
+			sbuf_chr(yb, '\n')
+		}
+		sbuf_null(yb)
+		vi_regput(vi_ybuf, yb->s, 0);
+		free(yb->s);
+		if (cmd == 'd' || cmd == 'c') {
+			xrow = r1;
+			xoff = c_left;
+		}
+		if (cmd == 'c')
+			return vc_block_insert('I', r1, r2, c_left);
+	} else if (cmd == '~' || cmd == 'u' || cmd == 'U') {
+		for (r = r1; r <= r2; r++) {
+			VCB_BOUNDS;
+			if (left > right || !n)
+				continue;
+			int total = lbuf_s(ln)->len + 2;
+			char *new_ln = emalloc(total);
+			memcpy(new_ln, ln, total - 1);
+			new_ln[total - 1] = '\0';
+			char *p = new_ln + (bp - ln);
+			char *pe = new_ln + (ep - ln);
+			while (p < pe) {
+				int ch = (unsigned char)*p;
+				if (ch <= 0x7f) {
+					if (cmd == 'u')
+						*p = (char)tolower(ch);
+					else if (cmd == 'U')
+						*p = (char)toupper(ch);
+					else
+						*p = (char)(islower(ch) ? toupper(ch) : tolower(ch));
+				}
+				p += uc_len(p);
+			}
+			lbuf_edit(xb, new_ln, r, r + 1, 0, 0);
+			free(new_ln);
+		}
+	} else if (cmd == '>' || cmd == '<')
+		vi_shift(r1, r2, cmd == '>' ? +1 : -1, 1);
+	return 0;
+}
+
+static int vc_visual_op(int cmd)
+{
+	int r1 = vi_vrow, o1 = vi_voff;
+	int r2 = xrow, o2 = xoff;
+	if (r1 > r2 || (r1 == r2 && o1 > o2)) {
+		swap(&r1, &r2);
+		swap(&o1, &o2);
+	}
+	int visual = vi_visual;
+	int lnmode = visual == 'V';
+	vi_visual = 0;
+	if (visual == 'b')
+		return vc_block_op(cmd, r1, r2, MIN(o1, o2), MAX(o1, o2));
+	if (!lnmode) {
+		if (o2 < lbuf_eol(xb, r2, 2))
+			o2++;		/* include char under cursor, like vc_motion */
+		ren_state *r = (ren_state*)lbuf_get(xb, r1);
+		r = r ? ren_position((char*)r) : NULL;
+		o1 = r ? MAX(0, MIN(o1, r->n)) : 0;
+	} else {
+		o1 = 0;
+		o2 = lbuf_eol(xb, r2, r1 >= r2);
+	}
+	int key = 0;
+	int prevlen = lbuf_len(xb);
+	if (cmd == 'y')
+		vi_yank(r1, o1, r2, o2, lnmode);
+	else if (cmd == 'd')
+		vi_delete(r1, o1, r2, o2, lnmode);
+	else if (cmd == 'c')
+		key = vi_change(r1, o1, r2, o2, lnmode);
+	else if (cmd == '~' || cmd == 'u' || cmd == 'U')
+		vi_case(r1, o1, r2, o2, lnmode, cmd);
+	else if (cmd == '!')
+		vi_pipe(r1, r2);
+	else if (cmd == '>' || cmd == '<')
+		vi_shift(r1, r2, cmd == '>' ? +1 : -1, 1);
+	vi_mod |= r1 != r2 || prevlen != lbuf_len(xb) ? 1 : 2;
+	return key;
+}
+
 static int vc_motion(int cmd)
 {
 	int r1 = xrow, r2 = xrow;	/* region rows */
@@ -1287,6 +1511,10 @@ void vi(int init)
 				vi_mod |= 1;
 				break;
 			case 'u':
+				if (vi_visual) {
+					vc_visual_op('u');
+					break;
+				}
 				undo:
 				if (vi_arg >= 0 && !lbuf_undo(xb, &xrow, &xoff)) {
 					vi_mod |= 1;
@@ -1337,6 +1565,10 @@ void vi(int init)
 				vi_lncol = 0;
 				vi_mod |= 1;
 				break;
+			case 'U':
+				if (vi_visual)
+					vc_visual_op('U');
+				break;
 			case 'v':
 				vi_mod |= 2;
 				k = term_read(0);
@@ -1460,7 +1692,15 @@ void vi(int init)
 					xmpt = 1;
 				break;
 			case 'c':
+				if (vi_visual) {
+					k = vc_visual_op('c');
+					goto insert_done;
+				}
 			case 'd':
+				if (vi_visual) {
+					vc_visual_op('d');
+					break;
+				}
 				k = term_read(0);
 				if (k == 'i') {
 					k = term_read(0);
@@ -1509,6 +1749,10 @@ void vi(int init)
 			case '>':
 			case '<':
 			case TK_CTL('w'):
+				if (vi_visual && c != TK_CTL('w')) {
+					vc_visual_op(c);
+					break;
+				}
 				k = vc_motion(c);
 				if (c == 'c')
 					goto insert_done;
@@ -1519,6 +1763,13 @@ void vi(int init)
 			case 'A':
 			case 'o':
 			case 'O':
+				if (vi_visual == 'b' && (c == 'I' || c == 'A')) {
+					int r1b = MIN(vi_vrow, xrow), r2b = MAX(vi_vrow, xrow);
+					int c_left = MIN(vi_voff, xoff), c_right = MAX(vi_voff, xoff);
+					vi_visual = 0;
+					k = vc_block_insert(c, r1b, r2b, c == 'I' ? c_left : c_right);
+					goto insert_done;
+				}
 				insert:
 				k = vc_insert(c);
 				insert_done:
@@ -1637,8 +1888,14 @@ void vi(int init)
 					ex_command(cmd)
 					restore(xled)
 					vi_mod |= 1;
-				} else if (k == '~' || k == 'u' || k == 'U')
+				} else if (k == '~' || k == 'u' || k == 'U') {
 					vc_motion(k);
+				} else if (k == 'v' || k == 'V' || k == 'b') {
+					vi_visual = vi_visual == k ? 0 : k;
+					vi_vrow = xrow;
+					vi_voff = xoff;
+					vi_mod |= 1;
+				}
 				break;
 			case 'x':
 				term_push("d ", 2);
@@ -1653,6 +1910,10 @@ void vi(int init)
 				term_push("yy", 2);
 				goto motion;
 			case '~':
+				if (vi_visual) {
+					vc_visual_op('~');
+					break;
+				}
 				term_push("g~ ", 3);
 				goto motion;
 			case 'C':
@@ -1714,6 +1975,13 @@ void vi(int init)
 				vc_status(0);
 				vi_mod |= 1;
 				break;
+			case TK_ESC:
+				if (vi_visual) {
+					vi_visual = 0;
+					vi_mod |= 1;
+					break;
+				}
+				continue;
 			default:
 				continue;
 			}
@@ -1774,6 +2042,8 @@ void vi(int init)
 				}
 			}
 		}
+		if (vi_visual)
+			vi_mod |= 1;
 		term_record = 1;
 		if (vi_mod & 1 || xleft != oleft
 				|| (vi_lnnum && orow != xrow && !(vi_lnnum == 2))
